### ISSUE TITLE
encrypted ZIPs unzReadCurrentFile -3

### ISSUE THREAD

**Issue by catlan** [nmoinvaz/minizip#100]
When ever I try a password protected ZIP I only get _-3_ from `unzReadCurrentFile`.

Using macOS Sierra zip command to create encrypted zip file:
`zip -re ./PasswordTest.zip ./PasswordTest`

This file works with the build in Archive Utility and third party tools like The Unarchiver. 

See attached sample. Password: passw0rd

[PasswordArchive.zip](https://github.com/nmoinvaz/minizip/files/881222/PasswordArchive.zip)

**Comment by nmoinvaz** [comment]
I do not get this error on Windows when unzipping.

**Comment by catlan** [comment]
I just build it as 32bit and it passed my tests. So it must be an issue related to 64bit.

**Comment by MacGritsch** [comment]
I can confirm this. With AES it works fine but not with the legacy encryption method.

BTW: I was not able to test if it works in 32 bit mode because I have no system that supports 32 bit.

**Comment by nmoinvaz** [comment]
Thanks for reporting. I was able to track it down with the xcode project and fix it.
