### ISSUE TITLE
I can not get it work on linux with password when creating zip file?

### ISSUE THREAD

**Issue by cy99** [nmoinvaz/minizip#104]
Is there a demo for linux to create zip file with password?

**Comment by MacGritsch** [comment]
legacy encryption or with aes?

http://xmodulo.com/how-to-create-encrypted-zip-file-on-linux.html

**Comment by cy99** [comment]
It works, thank you! How can i use minizip to do this with aes? when I   gcc minizip.c minishared.c libminizip.a libaes.a  -o minizip -lz, I get  aes_encrypt_key192 undefined.

**Comment by nmoinvaz** [comment]
Should be fixed now. Thanks!
