### ISSUE TITLE
Can't set crc and uncompressed size in case of raw format

### ISSUE THREAD

**Issue by chrdumont** [nmoinvaz/minizip#106]
As zipCloseFileInZipRaw64 has been removed, there is no more way to set the CRC related to the raw data (zi->ci.raw != 0). Same for the uncompressed size which will then have the value of the "compressed size" when the file is closed.
Can we have a second zipCloseFileInZip method where the CRC and uncompressed size of raw data can be used to skip the related values of the zi structure when closing the file. Thank you

**Comment by nmoinvaz** [comment]
You shouldn't need to set these values as they are calculated when you use zipWriteInFileInZip.

**Comment by chrdumont** [comment]
That's actually the problem, they shouldn't be calculated for raw format, hence the need to provide an API to override the values when closing the zip file.
For instance the raw format is already compressed when invoking zipWriteInFileInZip, and the value for uncompressed size will then be set with the same compressed size value. The zipCloseFileInZipRaw64 was allowing to set the uncompressed size not known by zipWriteInFileZip. Same issue for CRC32.
I did the test with the current zipCloseFileInZip, and it will fail CRC check using different zip tools. If I modify the method to set the CRC, then it passes CRC checks.

**Comment by nmoinvaz** [comment]
I understand your use case. I have added those functions back.
