### ISSUE TITLE
zipCloseFileInZip is setting uncompressed size to 0 (related to issue #106)

### ISSUE THREAD

**Issue by chrdumont** [nmoinvaz/minizip#107]
In zip.c, zipCloseFileInZipRaw64, in case of non raw format, the following 2 lines (#1628 - 1629)
        crc32 = zi->ci.crc32;
        uncompressed_size = zi->ci.total_uncompressed;
shall be moved a few lines down, before the /* Write data descriptor */ section to ensure stream compression has ended to allow proper reading of the uncompressed size value.

**Comment by nmoinvaz** [comment]
It is now fixed. Thanks.
