### ISSUE TITLE
unzLocateFile randomly not working

### ISSUE THREAD

**Issue by camill-a** [nmoinvaz/minizip#108]
I have a problem with my Swift minizip wrapper (creating inputStream from zip to access a particular ressource inside the archive)

It's working, but it crashes around 10% of time.

Sometimes  the unzLocateFile() calls fails, and return the `UNZ_END_OF_LIST_OF_FILE` error. 
It's caused by the sub calls to unzGoToNextFile2().

(unzip.c line 1678) the error is returned here. That mean that one time out of ten the minizip lib can't find the file in my archive? (but the previous times it found it, same file, same archive)

Am I doing something wrong?

**Comment by nmoinvaz** [comment]
Glad to see you got it working. Thanks!

**Comment by camill-a** [comment]
Yes it was actually a problem on the Swift side, when converting the path (filename argument) from a Swift String to a cString. The conversion was producing an optional result, but no `?`or `!` was put since Swift directly convert nil optional string into an empty string.

Now the bridging from Swift string to cString is automatic, so you can just call the minizip methods directly passing Swift Strings, and it's unfailable.

Have a good day, thanks for your work, really unsefull.
