### ISSUE TITLE
zipCloseFileInZipRaw64 Xcode "Dead store" warning when HAVE_APPLE_COMPRESSION is not defined

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#115]
In zip.c, in [`zipCloseFileInZipRaw64` line 1566](https://github.com/nmoinvaz/minizip/blob/master/zip.c#L1566), with undefined HAVE_APPLE_COMPRESSION:

            while (err == ZIP_OK)
            {
                uint32_t total_out_before = 0;
                if (zi->ci.stream.avail_out == 0)
                {
                    err = zipFlushWriteBuffer(zi);

                    zi->ci.stream.avail_out = Z_BUFSIZE;
                    zi->ci.stream.next_out = zi->ci.buffered_data;
                }

    #ifdef HAVE_APPLE_COMPRESSION
                // ...
    #else
                total_out_before = (uint32_t)zi->ci.stream.total_out;
                err = deflate(&zi->ci.stream, Z_FINISH);
                zi->ci.pos_in_buffered_data += (uint16_t)(zi->ci.stream.total_out - total_out_before);
    #endif
            }

On the line `err = zipFlushWriteBuffer(zi);` we are assigning a value to `err`, but on the line `err = deflate(&zi->ci.stream, Z_FINISH);` we are re-assigning a new value to `err` without ever looking at previous value.

**Comment by nmoinvaz** [comment]
I have fixed it. Thanks!
