### ISSUE TITLE
Include minishared.h in public headers

### ISSUE THREAD

**Issue by asmaloney** [nmoinvaz/minizip#118]
There are a few utility functions in minishared that would be useful to expose to users of the lib - e.g. `get_file_date`, `dosdate_to_tm`, `get_file_crc`.

It would be nice to expose them by including minishared.h as a public header.

**Comment by nmoinvaz** [comment]
I'm not sure what you mean. Maybe you can do a pull request so I can see.

**Comment by Coeur** [comment]
@asmaloney it was made public 2 days before this issue: https://github.com/nmoinvaz/minizip/pull/116

**Comment by asmaloney** [comment]
@Coeur That's for Pods which is macOS-specific and not everyone uses - that doesn't do it in general.

I think adding `minishared.h` to `MINIZIP_PUBLIC_HEADERS` in the CMake file would do it. Then it would be installed alongside the other headers.

**Comment by Coeur** [comment]
Oh, right. Please make a pull request for https://github.com/nmoinvaz/minizip/blob/master/CMakeLists.txt

**Comment by nmoinvaz** [comment]
Whenever a pull request is opened I will except it.
