### ISSUE TITLE
warning: "Function cannot return qualified void type 'volatile void'"

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#120]
Opening this issue regarding AES which uses `volatile void` and ugly optimizations. This is a duplicate issue of https://github.com/BrianGladman/aes/issues/24, but for us.

*aes_via_ace.h* uses `volatile void` as a compiler optimization, but at the same time it produces:
> Function cannot return qualified void type 'volatile void'

Why this optimization? [Maybe because this (it's a speculation)](https://stackoverflow.com/a/14325115/1033581):
> The GCC optimizations mean that the calling function's registers, which otherwise would have overwritten the values upon return, are not saved. The results of the calculations in the assembly language functions remain in the registers for subsequent code to use.

The same author of the speculation warns us:
> Extensive use of this technique is definitely discouraged. First, it depends on customization for each compiler. Second, it depends on those compilers not changing how they handle the 'no return' case. Third, it's potentially confusing to subsequent maintainers.

And someone else in the same question comments:
> Declaring a function as doesn't return when it does return to convince the optimizer to do something specific is asking for trouble.

Finally, the maintainer of the code wrote:
> The VIA ACE code hasn't changed for many years now and I no longer have the kit that is necessary to test any changes that I might make in this. I am hence reluctant to make changes unless someone with VIA ACE kit is willing to test any changes that are made. I would expect that removing the volatile keyword would be all that is needed. If you are not using VIA ACE and simply want to remove the warnings, you can turn VIA ACE support off in aesopt.h.

As we are only a zipping/unzipping lib, we shouldn't have our users deal with warnings or manipulating aesopt.h themselves, so I suggest that we disable VIA ACE ourselves by default.

Otherwise, list of alternative AES implementations I could find:
* https://github.com/ARMmbed/mbedtls/tree/development/library
* https://github.com/kokke/tiny-AES128-C
* https://github.com/B-Con/crypto-algorithms
* https://github.com/wolfSSL/wolfssl/tree/master/wolfcrypt/src
* https://github.com/openssl/openssl/tree/master/crypto/aes
* https://github.com/libressl-portable/openbsd/tree/master/src/lib/libcrypto/aes
* https://gitlab.com/gnutls/gnutls/tree/master/lib/nettle/int
* https://github.com/jedisct1/libsodium/tree/master/src/libsodium/crypto_aead/aes256gcm/aesni

Others:
* https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_Sources_Building_Testing
* https://git.gnupg.org/cgi-bin/gitweb.cgi?p=libgcrypt.git;a=tree

**Comment by nmoinvaz** [comment]
The library would also have to support HMAC SHA1.

**Comment by Coeur** [comment]
By the way, I just found this text file in the original repository documenting what is _aes_via_ace.h_:
* https://github.com/BrianGladman/aes/blob/master/via_ace.txt

And a press release from 2009:
* https://www.viatech.com/en/2009/09/via-launches-ace-cnx-customized-security-service/

An indirect mention on Wikipedia:
* https://en.wikipedia.org/wiki/VIA_C3#Nehemiah_cores

**Comment by Coeur** [comment]
> The library would also have to support HMAC SHA1.

Good point. Well, for now I would simply disable VIA ACE optimization.

**Comment by nmoinvaz** [comment]
I think it would be better to just remove all the VIA ACE code.

**Comment by Coeur** [comment]
OK. pull request updated to remove aes_via_ace.h
