### ISSUE TITLE
PKWARE ZIP encryption isn't compatible with 7-zip/WinRAR

### ISSUE THREAD

**Issue by Nekto89** [nmoinvaz/minizip#123]
Minizip produces archive that can't be decrypted via 7-zip and WinRAR. Miniunz still manages to read it.

1) Create file.txt "Hello world"
2) minizip_exec.exe -6 -p 123 file.zip file.txt

CRC looks fine.
Tested on latest  c6d04f9 - Visual Studio 14 2015 (32-bit) and Visual Studio 15 2017 Win64. Zlib 1.2.11. -DUSE_AES=OFF

[file.zip](https://github.com/nmoinvaz/minizip/files/1130047/file.zip)

**Comment by nmoinvaz** [comment]
Looks like it broke in #c798d49c520350452df686afe91ac3b87f379731.

**Comment by nmoinvaz** [comment]
It looks like there was a modification that InfoZIP added to the ZIP format that was not part of the PKZIP app note. I have made the changes to make it work.

**Comment by nmoinvaz** [comment]
I discovered it by looking through the 7zip source code in ZipHandler.c I found:

`/* Info-ZIP modification to ZipCrypto format:
               if bit 3 of the general purpose bit flag is set,
               it uses high byte of 16-bit File Time.
             Info-ZIP code probably writes 2 bytes of File Time.
             We check only 1 byte. */`
