### ISSUE TITLE
invalid archive when compressing a 0 bytes file with password (AES)

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#127]
1. Build minizip with HAVE_AES. (I used minizip.xcodeproj with no changes)
 2. Create an empty file

    $ touch a

 3. compress it with a password (it will call `zipOpenNewFileInZip4_64()` with a password and HAVE_AES)

    $ ./minizip -p a -j a.zip a

4. attempt to unzip it with miniunzip (or Keka, or 7-zip, ...), you'll get a CRC error.

**Comment by Coeur** [comment]
empty files compressed with password `a`:
* [a by keka.zip](https://github.com/nmoinvaz/minizip/files/1172832/a.by.keka.zip)
* [a by minizip.zip](https://github.com/nmoinvaz/minizip/files/1172833/a.by.minizip.zip)

**Comment by nmoinvaz** [comment]
I was able to extract successfully both archives with PKZip, 7-Zip. I also created an archive that had an empty file with AES encryption and it extracted in 7-Zip okay.

**Comment by nmoinvaz** [comment]
Perhaps you are seeing a bug that has recently been fixed: #123.

**Comment by Coeur** [comment]
I was using the latest code, including #123. Did you try with *miniunz*, Nathan? Here are my results on macOS:

"a.by.[keka](http://www.kekaosx.com/)".zip:
* unzip with **Archive Utility** (Apple default, not officially supporting passwords): asks for password, but get stuck in infinite loop...
* unzip with **keka**: OK
* unzip with **miniunz**: OK

"a.by.*minizip*.zip":
* unzip with **Archive Utility** (Apple default, not officially supporting passwords): doesn't ask for password and directly display "Unable to expand a.by.minizip.zip into test. Error 1 - Operation not permitted."
* unzip with **keka**: "Extraction of a.by.minizip.zip failed. Error code 2 using p7zip. Fatal error."
* unzip with **miniunz**: "error -105 with zipfile in unzCloseCurrentFile"

Maybe the issue is only on macOS system?

**Comment by nmoinvaz** [comment]
I've run only tests on Windows.  Do you know which check-in it started failing at?

**Comment by nmoinvaz** [comment]
I have fixed the issue. Let me know if you have any unintended side effects. Thanks.

**Comment by Coeur** [comment]
your fix for unzipping is working, thanks.
