### ISSUE TITLE
Macro warnings

### ISSUE THREAD

**Issue by Nethar** [nmoinvaz/minizip#128]
Hello, have not found a mention about this here. I am building Linux 64 version and getting warnings about macros, but I got quite lost in the definitions and don't know what's the reason behind it:

`/aes/aesopt.h:353:25: note: in definition of macro ‘to_byte’`
` #  define to_byte(x)  ((x) & 0xff)`
`                         ^`
`/aes/aesopt.h:727:12: note: in expansion of macro ‘bval’`
`   ^ tab[2][bval(vf(x,2,c),rf(2,c))] \`
`            ^~~~`
`/aes/aesopt.h:727:17: note: in expansion of macro ‘vf1’`
`   ^ tab[2][bval(vf(x,2,c),rf(2,c))] \`
`                 ^~`
`/aes/aesopt.h:749:29: note: in expansion of macro ‘four_tables’`
` #  define inv_mcol(x)       four_tables(x,t_use(i,m),vf1,rf1,0)`
`                             ^~~~~~~~~~~`
`/aes/aeskey.c:232:17: note: in expansion of macro ‘inv_mcol’`
` #define ff(x)   inv_mcol(x)`
`                 ^~~~~~~~`
`/aes/aeskey.c:491:25: note: in expansion of macro ‘ff’`
`     cx->ks[v(56,(7))] = ff(ss[7] = word_in(key, 7));`
`                         ^~`
`/aes/aeskey.c:491:34: warning: operation on ‘ss[7]’ may be undefined [-Wsequence-point]`
`     cx->ks[v(56,(7))] = ff(ss[7] = word_in(key, 7));`

**Comment by Coeur** [comment]
You may want to report those warnings to where the code is from (https://github.com/BrianGladman/aes/) as well.

**Comment by Nethar** [comment]
Thanks for info, will do.

**Comment by Coeur** [comment]
For reference, the continuation of this issue will be on https://github.com/BrianGladman/aes/issues/28
