### ISSUE TITLE
I can‘t find any demo and have a problem using the tool which seems to be concernd with crc

### ISSUE THREAD

**Issue by Anychnn** [nmoinvaz/minizip#130]
here is the code,since i can't find any demo,and don't know how to resolve it

   char *oldZipPath = "F:/test/test.zip";
    char *newZipPath = "F:/test/test2.zip";
    zipFile zf = zipOpen(newZipPath, APPEND_STATUS_CREATE);
    unzFile uzf = unzOpen(oldZipPath);
    unz_global_info global_info;
    unzGetGlobalInfo(uzf, &global_info);
    long buff_len = 2048 * 4;
    char buffer[buff_len];
    for (int i = 0; i < global_info.number_entry; i++) {
        unz_file_info fileInfo;
        char fileName[1024];
        unzGetCurrentFileInfo(uzf, &fileInfo, fileName, 1024, NULL, 0, NULL, 0);
        unzOpenCurrentFile2(uzf, 0, 0, true);
        zip_fileinfo z_file_info = {0};
        zipOpenNewFileInZip2(zf, fileName, &z_file_info, NULL, 0, NULL, 0, NULL, 0, 0, true);
        long readed = 0;
        do {
            readed = unzReadCurrentFile(uzf, &buffer[0], buff_len);
            zipWriteInFileInZip(zf, buffer, readed);
        } while (readed > 0);
        zipCloseFileInZipRaw(zf, fileInfo.uncompressed_size, fileInfo.crc);
        unzGoToNextFile(uzf);
    }
    zipClose(zf,NULL);

I simplely use this lib to format a zip file using row stream,but found "File format corrupted".

**Comment by Coeur** [comment]
demo for Windows is https://github.com/nmoinvaz/minizip/tree/master/windows

Your code seems to unzip (`unzReadCurrentFile`), but you say you're using it for zipping?

**Comment by Anychnn** [comment]
我想用这个文件生成一个新的zipfile，不通过压缩，仅仅用raw stream，但是打开生成文件时候会提示文件已损坏
[test.zip](https://github.com/nmoinvaz/minizip/files/1211599/test.zip)

**Comment by Coeur** [comment]
@Anychnn did you figure out the issue? (I don't read Chinese)

**Comment by Anychnn** [comment]
int method = 0;
 int compression = 0;
 unzOpenCurrentFile2(uzf, &method, &compression, true);
 zip_fileinfo z_fileInfo = {0};
 zipOpenNewFileInZip2(zf, rename_it->second.c_str(), &z_fileInfo, NULL, 0, NULL, 0, NULL,
                                     method, compression, true);

I fount these two params: (method ,compression) and pass them to the func : zipOpenNewFileInZip2,then i get the zip file I want.
