### ISSUE TITLE
Support external AES encryption

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#152]
Minizip is currently relying on https://github.com/brianGladman/aes.

But:
* How to solve the macro redefinitions of `AES_ENCRYPT` and `AES_DECRYPT` when using both https://github.com/brianGladman/aes and https://github.com/openssl/openssl?
* What if I want to use a different AES lib?

Actually, many systems support natively AES already:
* CommonCrypto in Cocoa/CocoaTouch (macOS, iOS)
* System.Security.Cryptography in .NET (Windows)
* javax.crypto.Cipher in Android

So, it would be nice to have zip.c and unzip.c AES integration less dependent on current "aes/*.h", and instead using a substitutable wrapper.

**Comment by nmoinvaz** [comment]
I would also be in favor of using libraries the system already has available. Maybe once AES code is moved into a stream then we can think about this.

https://en.wikipedia.org/wiki/AES_implementations

**Comment by nmoinvaz** [comment]
It would be nice to one day more to using system AES libraries, but for the time being I am going to leave it to  continue to use Brian Gladman's AES library. It is a lot of work just because a macro is redefined between two libraries.

**Comment by Coeur** [comment]
The Macro issue was actually a mistake from my project, where we were doing `#include <aes.h>` instead of `#include <aes/aes.h>`, thus including the wrong file.

**Comment by Coeur** [comment]
We could leave this issue open, as a future target?
