### ISSUE TITLE
This zip file cannot be unzip (GB2312 encoding)

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#154]
https://github.com/ZipArchive/ZipArchive/files/769125/Calculator.zip

Results with other tools:  
<img width="346" alt="screen shot 2017-09-29 at 6 38 05 pm" src="https://user-images.githubusercontent.com/839992/31012914-44a75bba-a4d9-11e7-804b-fa86129fdf97.png">

Results with miniunz:  
>Calculator.zip opened
error -103 with zipfile in unzOpenCurrentFilePassword
error -102 with zipfile in unzCloseCurrentFile
error -103 with zipfile in unzGoToNextFile

So, miniunz is the only tool unable to unzip this file at all.

In [unzip.c, line 1019](https://github.com/nmoinvaz/minizip/blob/master/unzip.c#L1019), the test `size_filename != s->cur_file_info.size_filename` is failing, as size_filename from filestream ([set on line 1018](https://github.com/nmoinvaz/minizip/blob/master/unzip.c#L1017)) is 27 but from filestream_with_CD ([set on line 751](https://github.com/nmoinvaz/minizip/blob/master/unzip.c#L751)) it's 24.

Commenting out lines 1019 and 1020 and ignoring the differences in size_filename let the file be unzipped correctly.

**Comment by nmoinvaz** [comment]
I’m not sure how important even checking for local header consistency is. It may be possible to get rid of the check some day.
