### ISSUE TITLE
Got exception when trying to unzip a compressed folder using miniunz

### ISSUE THREAD

**Issue by sakthicsk** [nmoinvaz/minizip#157]
As minizip can be used to compress individual files in _.zip_ format (got from the link https://github.com/nmoinvaz/minizip/issues/66), I have compressed the folder (having 13 files) for the format _.zip_ using .7z.

When I tried to decompress the folder using miniunz from the sample project (_zlib-1.2.11\contrib\vstudio\vc12_), I got exception from __inflate_fast_, during the decompression of second file.   

Since miniunz dependency is included in dll format, I am not able to identify the root-cause for this.   But, its working fine for individual files.   Corresponding call-stack and command line arguments and debug prints are given below for your reference and support.   

Call stack
>	zlibwapi.dll!_inflate_fast() Line 669	Unknown
 	zlibwapi.dll!inflate(z_stream_s * strm, int flush) Line 1047	C
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for ntdll.dll]	
 	zlibwapi.dll!win32_seek64_file_func(void * opaque, void * stream, unsigned __int64 offset, int origin) Line 374	C
 	zlibwapi.dll!call_zseek64(const zlib_filefunc64_32_def_s * pfilefunc, void * filestream, unsigned __int64 offset, int origin) Line 44	C
 	zlibwapi.dll!unz64local_GetCurrentFileInfoInternal(void * file, unz_file_info64_s * pfile_info, unz_file_info64_internal_s * pfile_info_internal, char * szFileName, unsigned long fileNameBufferSize, void * extraField, unsigned long extraFieldBufferSize, char * szComment, unsigned long commentBufferSize) Line 1072	C
 	[External Code]	

Command line Arguments:
> -x  24.zip -d .

Debug prints:
>  test_fldr.zip opened
     creating directory: test_fldr/
     extracting: test_fldr/side_left_bottom_0.png
     extracting: test_fldr/side_left_bottom_1.png

Please help me!! Thanks in advance for the same!

**Comment by Coeur** [comment]
If you are talking about https://github.com/madler/zlib/tree/master/contrib/vstudio/vc12, then the minizip version in https://github.com/madler/zlib/tree/master/contrib/minizip is kind of outdated.

**Comment by sakthicsk** [comment]
I have downloaded the zlib 1.2.11 package from http://zlib.net/.    

I would like to explore folder compression and decompression with the minzip.   Could you please provide your input towards the same.

Thanks.

**Comment by sakthicsk** [comment]
Thanks for your input.  Now, folder decompression is working fine as per my expectation.

Is it possible to compress a folder which has multiple files using minizip.   Since it was mentioned that it is not possible to compress folder directly in following link  #66
