### ISSUE TITLE
Change line endings of zip.c to UNIX (LF)

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#158]
Current status of project files:

* crypt.c: UNIX (LF)
* crypt.h: UNIX (LF)
* ioapi_buf.c: UNIX (LF)
* ioapi_buf.h: UNIX (LF)
* ioapi_mem.c: UNIX (LF)
* ioapi_mem.h: UNIX (LF)
* ioapi.c: UNIX (LF)
* ioapi.h: UNIX (LF)
* minishared.c: UNIX (LF)
* minishared.h: UNIX (LF)
* miniunz.c: UNIX (LF)
* minizip.c: UNIX (LF)
* unzip.c: UNIX (LF)
* unzip.h: UNIX (LF)
* zip.c: WINDOWS (CRLF)
* zip.h: UNIX (LF)

And it's quite annoying, as default tool on macOS (Xcode) will always change the CRLF to something else.

I could pull request the change on zip.c, but you may prefer to do it yourself, @nmoinvaz

**Comment by nmoinvaz** [comment]
Please do a pull request. Thanks!
