### ISSUE TITLE
Let's have a Pull Request for dev -> master

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#166]
In order to more easily review and track comments regarding the changes on the dev branch, we could have a pull request from dev to master.

I had to look at https://api.github.com/repos/nmoinvaz/minizip/comments to find my comments for the dev branch:
* https://github.com/nmoinvaz/minizip/commit/b436625e4e7de61deda142243b9d1542e4ab9ead#commitcomment-24780052
* https://github.com/nmoinvaz/minizip/commit/42801b8fb0be11e4d3f9190d74a547894b9617e5#commitcomment-24779828
* https://github.com/nmoinvaz/minizip/commit/a9b8cd886c86e41ee689da963ecabf06cab843b1#commitcomment-24778672

**Comment by Coeur** [comment]
Also, miniunz keeps crashing on  [line with `strncpy((char *)posix->path, path, posix->path_size);`](https://github.com/nmoinvaz/minizip/blob/dev/mz_strm_posix.c#L100).

**Comment by nmoinvaz** [comment]
Thanks opening the issue, I might not have seen the comments in the code. Great that you are helping me with the dev branch, I've put a lot of work into it.
