### ISSUE TITLE
mz_os_file_exists always return 1

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#169]
On https://github.com/nmoinvaz/minizip/blob/dev/mz_strm.c#L413, `mz_stream_os_open(stream, path, MZ_STREAM_MODE_READ)` returns MZ_OK even for non-existing files on macOS.

Basically it's because [mz_stream_posix_open always return MZ_OK](https://github.com/nmoinvaz/minizip/blob/dev/mz_strm_posix.c#L100).

**Comment by nmoinvaz** [comment]
Fixed! Thanks.
