### ISSUE TITLE
use arc4random_buf() instead of "/dev/urandom" when available

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#175]
Regarding **mz_posix_rand** (previously **cryptrand**):
On systems where it's available (BSD, APPLE, ...), arc4random_buf() is preferred to "/dev/urandom". See https://insanecoding.blogspot.com/2014/05/a-good-idea-with-bad-usage-devurandom.html

**Comment by nmoinvaz** [comment]
The article says that /dev/urandom and arc4random_buf are the same thing.

> So, how does one port the arc4random family to Linux? Linux is well known for inventing and supplying two default files, /dev/random and /dev/urandom (unlimited random). The former is pretty much raw entropy, while the latter is the output of a CSPRNG function like OpenBSD's arc4random family.

**Comment by Coeur** [comment]
but "/dev/urandom" uses file descriptors and is subject to the issues from the article, so using `arc4random_buf()` directly would avoid a potential issue of predefined salt for encryption.

**Comment by nmoinvaz** [comment]
I read the rest of the article. Looks like a good idea.

**Comment by nmoinvaz** [comment]
Done.
