### ISSUE TITLE
moving the source files in a subfolder

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#183]
Can we move the sources (*.c *.h) in a **src/** folder or something?
Otherwise scrolling is required to reach the Readme, and file organization is less clear.

**Comment by nmoinvaz** [comment]
Changed in 24ef270bbe9d9d3a366bc27b9600e7543652071e and 84bae188b6910858db0abb3c11fee5afb94820d8.

**Comment by nmoinvaz** [comment]
Thanks for the great suggestion.
