### ISSUE TITLE
can't fully extract a zip file with more than 65535 files

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#184]
Problem reported by @jdeepwell.
http://deepwell.name/Apple_API_Reference.docset.zip is a 968.6 MB archive created by a native macOS tool.

Normally, once uncompressed, it should be roughly 2,129,626,642 bytes (~ 2,031 MB).
But miniunz (from 1.2 branch) will only extract maybe ~298.6 MB and will not report any error. For instance, file `hc8z3wx_vy.html` will be missing when unzipping with miniunz.

To me it seems that `unzReadCurrentFile()` may return Z_BUF_ERROR at some point.

**Comment by Coeur** [comment]
Normally, it should unzip 262657 files in the Documents subfolder.
Actually, MiniUnz 1.2 unzip 22534 files only.

I'll test older versions to see if there was a regression at some point.

**Comment by Coeur** [comment]
Bug was already existing in very first commit of this repository :(
35c6102e21d76019206154de07b8bb8577018825

**Comment by Coeur** [comment]
Seems like
* number_entry and number_entry_cd are reporting 43125 entries, but there are actually much more (at least 262657)
* macOS unzip supports this archive correctly
* macOS Archive Utility supports this archive correctly
* The Unarchiver supports this archive correctly
* keka supports this archive correctly

So we're the only one relying too much on the number of entries from the CentralDir. Or there is a spec of the zip format that we are missing.

Anyway, I found a workaround...
setting `us.gi.number_entry` to `-1` will fully uncompress the file

**Comment by Coeur** [comment]
I count, there are 501877 entries in the archive. And 43125 == 501877 % 65536. So default tools on macOS will zip more than 65535 files by writing a modulo value in **number_entry** and **number_entry_cd**. So we _have to ignore_ the values stored in number_entry and number_entry_cd.

**Comment by Coeur** [comment]
Oh, I only notice now that it was me to accidentally close that Pull Request... sorry about that.

**Comment by nmoinvaz** [comment]
Is there something to be done here?

**Comment by Coeur** [comment]
No, not anymore. But if I had not close it accidentally, you could have had a fix in 2017 instead of year 2019.

**Comment by nmoinvaz** [comment]
No worries.
