### ISSUE TITLE
Minizip 2.0, File not found in the zip file

### ISSUE THREAD

**Issue by syedmaruf** [nmoinvaz/minizip#188]
In the file: **mz_unzip.c**
in the function: 

> extern int ZEXPORT mz_unzip_locate_entry(void *handle, const char *filename, mz_filename_compare_cb filename_compare_cb)

the check (as it is),
```
if (unzip->entry_header_read == 0)
{
	return MZ_END_OF_LIST;
}
```
results in "File %s not found in the zip file\n" inspite of the file being present in the zip file.

However, in the function: 

> extern int ZEXPORT mz_unzip_locate_entry(void *handle, const char *filename, mz_filename_compare_cb filename_compare_cb)

if the check:
```
if (unzip->entry_header_read == 0)
{
	return MZ_END_OF_LIST;
}
```
is placed after the line,
`err = mz_unzip_goto_first_entry(handle);`

That is, like this:
```
err = mz_unzip_goto_first_entry(handle);

if (unzip->entry_header_read == 0)
{
	return MZ_END_OF_LIST;
}
```
Everything works successfully!

I'm changing the order because, in the function: 

> static int mz_unzip_entry_read_header(void *handle)

**unzip->entry_header_read** is assigned **1**, **if (err == MZ_OK)**
and as such the following check:
```
if (unzip->entry_header_read == 0)
{
	return MZ_END_OF_LIST;
}
```
in function: 

> extern int ZEXPORT mz_unzip_locate_entry(void *handle, const char *filename, mz_filename_compare_cb filename_compare_cb)

is looking for a value other than 0 to continue successfully.

I'm using **WinZIP AES Encryption** with
```
#ifndef HAVE_AES
#define HAVE_AES
#endif
```
in **mz_unzip.c**
I'm using **7-Zip 16.04 (x64)** in Windows and these are my settings:
https://i.imgur.com/B2JXBcQ.png

**Comment by nmoinvaz** [comment]
Thank you for the bug report! I have made the correct changes in the dev branch.

**Comment by syedmaruf** [comment]
Happy to help. Minizip is awesome.
