### ISSUE TITLE
Compilation fails if NOCRYPT or NOUNCRYPT is defined

### ISSUE THREAD

**Issue by timothytylee** [nmoinvaz/minizip#189]
When NOCRYPT is defined, the conditional code inside mz_zip_entry_open() does not compile.  The compiler complains that the "password" variable is not defined.

When NOUNCRYPT is defined, the conditional code inside mz_unzip_entry_open() fails to compile due to mismatched brackets.

**Comment by nmoinvaz** [comment]
Thank you for the fix. In the dev branch I have also made it so encryption is conditionally compiled using:
```
cmake -DUSE_CRYPT=OFF
cmake -DUSE_AES=OFF
```
