### ISSUE TITLE
win32_seek_file_func ignores the offset argument

### ISSUE THREAD

**Issue by paul-sh** [nmoinvaz/minizip#19]
Hello,

I noticed the `win32_seek_file_func` function ignores the offset value and uses 0 instead. https://github.com/nmoinvaz/minizip/blob/master/iowin32.c#L454

The counterpart `win32_seek64_file_func` below does use the offset. Also the original minizip (https://github.com/madler/zlib/blob/master/contrib/minizip/iowin32.c#L333) uses the offset value.

Was that zero intentional?

Thanks,
Paul

**Comment by nmoinvaz** [comment]
I have fixed it. Thanks.
