### ISSUE TITLE
conversion issue with localtime

### ISSUE THREAD

**Issue by GenesisBP** [nmoinvaz/minizip#200]
I use the library with the Visual Studio 2013 C++ compiler.

When calling 'mz_zip_entry_write_open', a runtime error occurs during the conversion of the time_t values 'accessed_date' and 'creation_date' into tm-structs.

the call:
memcpy(ptm, localtime(&unix_time), sizeof(struct tm));
in the function:
int32_t mz_zip_time_t_to_tm(time_t unix_time, struct tm *ptm)
fails, due to a null-pointer returned by localtime.

That is my small test scenario: [minitest.zip](https://github.com/nmoinvaz/minizip/files/1418579/minitest.zip)

Another issue is given by the virtual table used in 'mz_strm.h'
the class 'mz_stream_vtbl_s' contains a member called 'delete'.
For C++ compilers this is a reserved keyword, and stops the code from compiling.

**Comment by nmoinvaz** [comment]
I am not sure why it is returning null. I tested trying to extract and it returns a value pointer. Can you tell me what the value of unix_time is?

The issue with delete keyword has been fixed in the master branch. Please pull the latest. Thanks.

**Comment by nmoinvaz** [comment]
Also you might want to make sure that the zip_entry is being zeroed out. I haven't done C++ in quite some time so I could be wrong, but StackOverflow [says](https://stackoverflow.com/questions/1069621/are-members-of-a-c-struct-initialized-to-0-by-default) that structs aren't initialized to zero by default.
```
mz_zip_file zip_entry = { 0 };
```

**Comment by GenesisBP** [comment]
yes, you are right. I actually found that too, 3 minutes ago *facepalm*

Thanks for your help and your great work on refactoring and enhancing this library!
