### ISSUE TITLE
use zlib style compression level "Z_DEFAULT_COMPRESSION" will wrong.

### ISSUE THREAD

**Issue by xwxbug** [nmoinvaz/minizip#202]
Z_DEFAULT_COMPRESSION in zlib is "-1";

see mz_zip_entry_write_open or zipOpenNewFileInZip* to make zlib compatible.

**Comment by nmoinvaz** [comment]
I'm not sure I understand. Can you please provide more details? Thanks.

**Comment by xwxbug** [comment]
sometime thirdparty lib use minizip(version 1.x),move to 2.x will not compatible.
minizip 2.x only support compression level 0~9,if use -1(Z_DEFAULT_COMPRESSION),will make bad zip.

**Comment by xwxbug** [comment]
it's not a bug,just not compatible with 1.x api.

**Comment by nmoinvaz** [comment]
It does support MZ_COMPRESS_LEVEL_DEFAULT which -1.
