### ISSUE TITLE
file handle not close in win32

### ISSUE THREAD

**Issue by xwxbug** [nmoinvaz/minizip#203]
`
zipFile z = zipOpen("./wtf.zip", APPEND_STATUS_CREATE);
	if (z)
	{
		bool result = false;
		zipClose(z, NULL);
		if (_unlink("./wtf.zip") == 0)
			result = true;
		if (result)
			printf("file delete ok\n");
		else
			printf("file delete failed\n");
	}
	else
	{
		printf("zipOpen failed\n");
	}
`

will output "file delete failed"

**Comment by nmoinvaz** [comment]
Thanks it is fixed now.
