### ISSUE TITLE
I find a issue when compile minizip with VS.

### ISSUE THREAD

**Issue by tsxiaofang** [nmoinvaz/minizip#208]
1、mz_stream_zlib_get_crc32_update() function 
void *mz_stream_zlib_get_crc32_update(void)
{
    return (void *)crc32;
}
crc32 is __stdcall calling convention

typedef int32_t (*mz_stream_crc32_update)(int32_t value, const void *buf, int32_t size);
is __cdecl  calling convention
2、minizip.exe -9 file.zip minizip.exe Get a bad zip file.
      minizip.exe -x -d file file.zip 
     ---------------------------------------------------
     Extracting: file/minizip.exe
     Error -105 closing entry in zip file

**Comment by nmoinvaz** [comment]
Ok that should be fixed now. Thanks.
