### ISSUE TITLE
Feature request: Add support for writing raw entries like in 1.2

### ISSUE THREAD

**Issue by chenxiaolong** [nmoinvaz/minizip#217]
It seems that minizip 2.0+ no longer has the ability to write raw (pre-compressed) entries to a zip file. My main use case is copying files from one zip file to another, making changes to certain entries in the process. With minizip 1.2, It was possible to directly copy the compressed data from one file to the other to avoid the CPU overhead of decompression + recompression. This was done by passing `1` for the `raw` parameter in the `unzOpenCurrentFile2` and `zipOpenNewFileInZip2_64` functions.

Are there plans for implementing this in minizip 2.0 as well?

EDIT: For reference, this is an example of the raw entry copy I was doing before: https://github.com/chenxiaolong/DualBootPatcher/blob/f561b2d9d60ca793ab0056c74d603689972eaf1b/libmbpatcher/src/private/miniziputils.cpp#L353-L461

**Comment by nmoinvaz** [comment]
I believe `mz_zip_entry_read_open` has a raw parameter and for `mz_zip_entry_write_open`, use 0 as the compress_level.

**Comment by chenxiaolong** [comment]
@nmoinvaz Thanks! I gave that a try but it seems to produce a zip that's much larger than the original.

Sample code that copies compressed data from one zip to another: https://gist.github.com/chenxiaolong/bcbb0835182ef16a25f09db8d99e0619

```
[minizip] ./a.out /tmp/foobar.zip /tmp/foobar.out.zip
[minizip] ls -sh1 /tmp/foobar.*
367M /tmp/foobar.out.zip
224M /tmp/foobar.zip
```

**Comment by nmoinvaz** [comment]
I used the gist you created (thanks btw!) and tested it against some zips that I created with WinRAR and wasn't able to reproduce those results. I tested a zip with a single file and one with multiple files. Can you try and narrow down what might be the cause? If you delete the output file and try the test again, does it work then? Thanks.

**Comment by chenxiaolong** [comment]
Hmm, that's interesting. Maybe it's a Linux specific issue? I just tried extracting the original zip, packing it again with 7zip, and this time, minizip created a 9.9 GB file. It doesn't seem to matter if I delete the output file first or not.

```
[minizip] ./a.out /tmp/foobar.7zip.zip /tmp/foobar.out.zip
[minizip] ls -sh1 /tmp/foobar.*
220M /tmp/foobar.7zip.zip
9.9G /tmp/foobar.out.zip
```

Not sure if it helps at all, but these are the zips I was testing with:

Original: https://noobdev.io/github/minizip/217/foobar.zip
Repacked with 7zip: https://noobdev.io/github/minizip/217/foobar.7zip.zip

**Comment by nmoinvaz** [comment]
Looks like it was a bug reading entries that are 0-byte.

**Comment by chenxiaolong** [comment]
Thank you! It's looking good in my initial testing. I'll try a couple more things and then close this issue if everything works.

**Comment by chenxiaolong** [comment]
@nmoinvaz I'm not sure if it's caused by the same issue, but if I test the same output zip with the `unzip -t` command (on Linux), I get the following:

```
...
   skipping: META-INF/MANIFEST.MF    unsupported compression method 99
   skipping: META-INF/CERT.SF        unsupported compression method 99
   skipping: META-INF/CERT.RSA       unsupported compression method 99
Caution:  zero files tested in /tmp/foobar.out.zip.
1631 files skipped because of unsupported compression or encoding.
```

`7z -t` reports a similar error as well:
```
...
ERROR: Unsupported Method : META-INF/MANIFEST.MF
ERROR: Unsupported Method : META-INF/CERT.SF
ERROR: Unsupported Method : META-INF/CERT.RSA
                        
Sub items Errors: 1631

Archives with Errors: 1

Sub items Errors: 1631
```

**Comment by chenxiaolong** [comment]
Everything is looking good with respect to copying raw entries now. Thanks again for fixing this.

**Comment by nmoinvaz** [comment]
Compression method 99 is used for AES encryption. Are you using encryption now?

**Comment by chenxiaolong** [comment]
Sorry, that was caused by my own mistake. I deleted the post. I accidentally built the library with `-DHAVE_AES` and my test program without that, so the structs did not match.
