### ISSUE TITLE
I want to extract the data from a Byte array of Zip file in iOS.

### ISSUE THREAD

**Issue by st0326s** [nmoinvaz/minizip#22]
I'd like to extract the data of the Zip file that is a Byte array, do you which files and sample reference is to achieve in Minizip?

**Comment by namar0x0309** [comment]
unzip.c 

Function

local unzFile unzOpenInternal(const void *path, zlib_filefunc64_32_def* pzlib_filefunc64_32_def, int is64bitOpenFunction)


Data should be in the file descriptor.

**Comment by st0326s** [comment]
>namar0x0309 
Thank you answer,
I have to extract the data on the memory using the "unzOpen2".

And I do not know even if the analysis,
Do you actual data that has been decompressed is output to any buffer?
