### ISSUE TITLE
mz_stream_open seg fault

### ISSUE THREAD

**Issue by umberto-sonnino** [nmoinvaz/minizip#225]
Hi there, I've been trying to use minizip for unzipping, I've compiled and set it up locally on my machine, but while trying to run the example (i.e. `minizip.c`), I'm getting a `segmentation fault` on the call to `mz_stream_open`.

I'm on macOS High Sierra 10.13.2

Thanks a lot in advance

**Comment by nmoinvaz** [comment]
Do you have more information such as what line it is occurring on? What command line arguments you are using..

**Comment by umberto-sonnino** [comment]
I'm building the [example file](https://github.com/nmoinvaz/minizip/blob/master/src/minizip.c) like this:
`clang -Wall -g minizip.c -o example -L. -lz -lminizip`
And then running the executable like so:
`./example -l file.zip
**OR**
./example -x file.zip`
And it's failing on line 700, I get a segmentation fault on the call to `mz_stream_open()`
I've got the library compiled statically and available in the current folder.
Let me know if this is any help.

**Comment by melsabagh** [comment]
I am having the same exact issue. Building the executable with cmake didn't help.

**Comment by nmoinvaz** [comment]
I have committed a fix for it. Thank you for reporting.
