### ISSUE TITLE
BUG: No such file or directory  #  include <bsd/stdlib.h>

### ISSUE THREAD

**Issue by KangLin** [nmoinvaz/minizip#229]
Environment: android sdk 16, ndk toolchain 4.9.

D:/Source/minizip/src/mz_os_posix.c:25:26: fatal error: bsd/stdlib.h: No such file or directory
 #  include <bsd/stdlib.h>
                          ^
D:/Source/minizip/src/mz_strm_crypt.c:67:11: error: unknown type name 'z_crc_t'
     const z_crc_t   *crc_32_tab;
           ^
compilation terminated.
D:/Source/minizip/src/mz_strm_crypt.c:93:66: error: unknown type name 'z_crc_t'
 static uint8_t mz_stream_crypt_update_keys(uint32_t *keys, const z_crc_t *crc_32_tab, int32_t c)
                                                                  ^
D:/Source/minizip/src/mz_strm_crypt.c:107:83: error: unknown type name 'z_crc_t'
 static void mz_stream_crypt_init_keys(const char *password, uint32_t *keys, const z_crc_t *crc_32_tab)
                                                                                   ^
D:/Source/minizip/src/mz_strm_crypt.c: In function 'mz_stream_crypt_open':
D:/Source/minizip/src/mz_strm_crypt.c:144:23: warning: assignment from incompatible pointer type
     crypt->crc_32_tab = get_crc_table();
                       ^
make[2]: *** [CMakeFiles/libminizip.dir/build.make:303: CMakeFiles/libminizip.dir/src/mz_strm_crypt.c.o] Error 1

See: https://ci.appveyor.com/project/KangLin/rabbitthirdlibrary/build/v0.0.3.64/job/rasmvfd1n2wvuhm4

**Comment by nmoinvaz** [comment]
Try using the dev branch. It has some changes for android.
