### ISSUE TITLE
Field "disk number start" is not set for files in non-split archives

### ISSUE THREAD

**Issue by juanii** [nmoinvaz/minizip#237]
Since OS/buffered streams do not implement property `MZ_STREAM_PROP_DISK_NUMBER`, the "disk number start" field for files in single-volume archives contain uninitialized memory. In the code cited below, when the `if` condition fails the field is not set.

https://github.com/nmoinvaz/minizip/blob/7a3820c53912d3c004c493b0ad1811864ccfe8c1/src/mz_zip.c#L1291-L1292

There are a few ways to fix it and I would like to know your opinion on which one is the best. I can implement any of them (or some other you come up with).
1. Implement `MZ_STREAM_PROP_DISK_NUMBER` in OS/buffered streams to always return 0. OS streams are used directly (or wrapped in a buffered stream) in single-volume archives, so disk #0 is always correct. When OS/buffered streams are wrapped in a split stream, the latter would get the call to `mz_stream_get_prop_int64` and return the proper disk number.
1. Initialize the whole file_info struct (with calloc or memset to NULL) so any unset fields at least contain null bytes instead of uninitialized memory.
1. Fix the specific lines cited above by not checking the return value of `mz_stream_get_prop_int64` and setting `file_info.disk_number` unconditionally with the contents of `disk_number` variable (which is already initialized to 0) or adding an ugly `else` with the same body as the corresponding `if`.

I started to implement solution number 1 to fix the "total number of disks" issue addressed in commit c65486d and dropped it because I thought it was overkill. But if it fixes other cases and makes the code more clear, by not relying on "I don't care if `mz_stream_get_prop_int64` fails because the variable is initialized to some correct value", maybe it's worth to do it.

Regards

**Comment by juanii** [comment]
After thinking a little more about option 1 and looking at how the various streams are used, shouldn't the buffered and split streams' implementation of `mz_stream_get_prop_int64` pass on calls for unknown properties to their base streams? They're always used as wrappers for other more basic streams. Sorry if this was discarded already, I didn't check all the project history.

**Comment by nmoinvaz** [comment]
It would be best I think to ignore the return value from the stream and always set the disk number.
