### ISSUE TITLE
minizip with Qt5+cmake+zlib+windows 8

### ISSUE THREAD

**Issue by nNullSpace** [nmoinvaz/minizip#244]
(1) I am trying to make minizip(nmoinvaz) with Qt5 on MS Windows 8, but it seems stuck on the flag named "HAVE_ZLIB".
Trying to make it through qmake(Qt5) and mingw32/64-make and get a standalone static executive.
But the tool told me that something wrong:

![1](https://user-images.githubusercontent.com/22057021/36960012-1fd7432c-2080-11e8-9612-7edcaad8e2e7.png)

And I could not find out where to turn the related flag on.

Is the flag "HAVE_ZLIB" generated in some phase before building?

![2](https://user-images.githubusercontent.com/22057021/36945922-d7e6cb22-1fef-11e8-88aa-a576f0364858.png)

**UPDATE >>**
add this line in .pro file to solve:
`DEFINES += HAVE_ZLIB`

(2) While building with cmake in Qt5, some errors were reported.
Some variables seem necessary in the CMakeLists.txt, I tried to set it, but it did not work.
![3](https://user-images.githubusercontent.com/22057021/36946008-2a1e7916-1ff1-11e8-9bcb-33f3dae93699.png)

Is there any clue to fix it?

(3) tried to build it with Qt5 on linux (Manjaro)
in main program:
```
    err = mz_stream_open(split_stream, path, mode);
    if (err != MZ_OK)
    {
        qInfo("Error opening file %s\n", path);
    }
    else
    {
        handle = mz_zip_open(split_stream, mode);
        if (handle == NULL)
        {
            qInfo("Error opening zip %s\n", path);
            err = MZ_FORMAT_ERROR;
        }

    }
```
mz_stream_open() and mz_zip_open() of minizip seem linked successfully, but "deflateInit2_" failed.

![4](https://user-images.githubusercontent.com/22057021/36964637-3eed0ce4-2092-11e8-9ba6-aa2c07c6d40a.png)

Although the static lib (libminizip.a) generated, it still fail in make phase with the main program.

"deflateInit2_" looks like belong to zip?

Does it mean that I have to place the static library file of zlib to somewhere to be referenced?

(I am sorry for that these questions might be noob)

Thank you very much.

**Comment by nmoinvaz** [comment]
I have fixed the issue with missing HAVE_ZLIB. I think the cmake commands to install zlib are (may require admin cmd prompt depending on install dir):

cmake -DCMAKE_INSTALL_PREFIX="C:\Program Files (x86)\zlib\" .
cmake --build . --config Release --target INSTALL

**Comment by nNullSpace** [comment]
nmoinvaz, thank you for your work.

And I found it can be done by this way:

file: minizip/CMakeLists.txt, add:
```
set(ZLIB_LIBRARY "<<< zlib folder >>>")
set(ZLIB_INCLUDE_DIR "<<< zlib folder >>>")
```

and then include zlib library file in Qt project file.
