### ISSUE TITLE
PkgConfig build dependency on macOS

### ISSUE THREAD

**Issue by jthorniley** [nmoinvaz/minizip#245]
I've found that the PkgConfig build dependency does not seem to be required on macOS, as it is only used to find libbsd which is not needed. 

(PkgConfig is not by default installed on macOS - can be obtained fairly easily with homebrew but its an unnecessary step).

It might help mac/bsd users a bit if the find_package for pkgconfig is moved into the linux only section as I've done in this branch: https://github.com/jthorniley/minizip/tree/pkgconfig-linux-only

**Comment by nmoinvaz** [comment]
Please create a merge request and I will accept it. Thanks!

**Comment by nmoinvaz** [comment]
Actually was  able to create one myself. Thanks. Merged.

**Comment by jthorniley** [comment]
Ah ok, just saw you merged it. Thanks!
