### ISSUE TITLE
unzOpenInternal unused parameter leading to question...

### ISSUE THREAD

**Issue by asmaloney** [nmoinvaz/minizip#25]
In **unzip.c** the prototype for unzOpenInternal is:

```c
local unzFile unzOpenInternal(const void *path, zlib_filefunc64_32_def* pzlib_filefunc64_32_def, int is64bitOpenFunction)
```

The parameter ```is64bitOpenFunction``` is unused in the function.

Looks like this is the code where that would have been used:

```c
    if (pzlib_filefunc64_32_def == NULL)
        fill_fopen64_filefunc(&us.z_filefunc.zfile_func64);
    else
        us.z_filefunc = *pzlib_filefunc64_32_def;
```
But then ```unzOpenInternal``` is called like this:
```c
extern unzFile ZEXPORT unzOpen(const char *path)
{
    return unzOpenInternal(path, NULL, 0);
}

extern unzFile ZEXPORT unzOpen64(const void *path)
{
    return unzOpenInternal(path, NULL, 1);
}
```

Clearly expecting different results.

Anyone have any insight into what this was used for and what should happen here?  Without really knowing the code I can only guess at the intent.

**Comment by nmoinvaz** [comment]
It is probably left over from when the library was converted to support ZIP64. I have checked-in a fix to remove this unused variable.
