### ISSUE TITLE
Build without zlib?

### ISSUE THREAD

**Issue by asmaloney** [nmoinvaz/minizip#264]
Am I supposed to be able to build without zlib using `-DUSE_ZLIB=OFF` or is it required?

**Comment by nmoinvaz** [comment]
You can build with it turned off but you have to at least have LZMA turned on. It will use CRC32 functions from ZLib or LZMA so one or the other is required.

**Comment by asmaloney** [comment]
1) If I configure with this (on Windows):
```
  -DUSE_AES=OFF \
  -DUSE_CRYPT=OFF \
  -DUSE_LZMA:BOOL=ON \
  -DUSE_ZLIB:BOOL=OFF \
```

It fails to compile because _mz_compat.h_ includes "zlib.h" and _mz_strm_zlib.h_ and _mz_strm_zlib.cpp_ are included in the build (see **MINIZIP_SRC** and **MINIZIP_PUBLIC_HEADERS** in CMaleLists.txt).

(Aside - also get a lot of conversion warnings when compiling with MSVC 2017.)

2) On macOS it compiles fine (since zlib is included with the OS it finds the headers), but then fails to link with an app unless I link with `-lz`. So effectively `USE_ZLIB:BOOL=OFF` isn't working.

3) If it's just including one of these libs for CRC32 - have you seen/considered [CRCpp](https://github.com/d-bahr/CRCpp)? It's one file & licensed under BSD.

**Comment by asmaloney** [comment]
Thanks Nathan.

There's still the problem with _mz_compat.h_ - is zlib pretty entrenched in the compatibility stuff or would it be possible to make it work with LZMA?

If it's going to require zlib then I'd recommend moving _mz_compat.c_ and _mz_compat.h_ into the **USE_ZLIB** section as well.

**Comment by nmoinvaz** [comment]
I have made some fixes that should solve it for you.

**Comment by asmaloney** [comment]
Getting there! Added a PR for build failure on macOS.

Another issue in _mz_compat.h_ is that `MAX_MEM_LEVEL` is undefined, so it (and therefore `DEF_MEM_LEVEL`) is set to 0. Based on looking at the zlib headers, I _think_ it can be set to 9 by default?

I was also using `MAX_WBITS` in older code. This seems like an important one to define for using functions such as `zipOpenNewFileInZip3_64`. Maybe this should also be defined in _mz_compat.h_ for compatibility?

Compression levels and strategy are also used in all those functions. Not sure how far you want to go with compatibility :-)

**Comment by nmoinvaz** [comment]
I don't have any plans on supporting strategy, memLevel, or windowBits for compatibility purposes. But I have defined those in mz_compat.h.
