### ISSUE TITLE
Link errors on Windows

### ISSUE THREAD

**Issue by asmaloney** [nmoinvaz/minizip#267]
I'm getting link errors in Windows with the current dev branch:

```
minizipd.lib(mz_os_win32.obj) : error LNK2019: unresolved external symbol __imp_CryptAcquireContextA referenced in function mz_win32_rand
minizipd.lib(mz_os_win32.obj) : error LNK2019: unresolved external symbol __imp_CryptReleaseContext referenced in function mz_win32_rand
minizipd.lib(mz_os_win32.obj) : error LNK2019: unresolved external symbol __imp_CryptGenRandom referenced in function mz_win32_rand
```

With the old version of minizip I didn't need to link any extra libs.

Is there another way to do this that doesn't require extra linking? Looks like this method is [deprecated anyway](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379942(v=vs.85).aspx).

(I'm building with `-DUSE_CRYPT=OFF` - I realize that is intended for controlling crypt of the zip file, not this, but it feels strange requiring crypto for random numbers.)

**Comment by nmoinvaz** [comment]
If you are using AES then you will need the crypto random functions.

**Comment by nmoinvaz** [comment]
I see. Do you need to compile in mz_os class? I don't see why you can't link against the lib.

**Comment by asmaloney** [comment]
> Do you need to compile in mz_os class?

I'm not sure what you mean - isn't it required?

> I don't see why you can't link against the lib

I could, but it adds more dependencies to all downstream uses of minizip, and adds extra overhead for the crypto API which seems excessive for this. What drew me to minizip initially was that it was small, self-contained, and an easy static link.

What about using [rand_s](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/rand-s)? 

>The rand_s function uses the operating system to generate cryptographically secure random numbers. 

It uses the same underlying API ([RtlGenRandom](https://msdn.microsoft.com/library/windows/desktop/aa387694)) as _CryptGenRandom_, but doesn't require bringing in crypto.

Maybe we could switch to that? Using it would also get rid of deprecated code.

**Comment by asmaloney** [comment]
Ok. Thanks for all your work on this Nathan!
