### ISSUE TITLE
Add complete instructions in the README for Windows users who are not familiar with cmake?

### ISSUE THREAD

**Issue by dislimit** [nmoinvaz/minizip#269]
How to build it for Windows? How to setup zlib?
Could you please add complete instructions in the README for Windows users who are not familiar with cmake?

Thank you!

**Comment by nmoinvaz** [comment]
Zlib instructions can be found here:
https://github.com/nmoinvaz/minizip/wiki

**Comment by nmoinvaz** [comment]
Done. https://github.com/nmoinvaz/minizip/blob/dev/README.md
