### ISSUE TITLE
Using minizip in a "super cmake build".

### ISSUE THREAD

**Issue by ZeroCrunch** [nmoinvaz/minizip#270]
I'm trying to use either [ExternalProject_Add](https://cmake.org/cmake/help/v3.11/module/ExternalProject.html) or [FetchContent](https://cmake.org/cmake/help/v3.11/module/FetchContent.html) in CMake to include minizip as an importable target, without relying on variables and I just can't make it work.

I think the CMakeLists.txt needs updating to include the headers in the EXPORT - but I've not had much success in my attempts.

**Comment by nmoinvaz** [comment]
I think your cmake skills are beyond mine.

**Comment by ZeroCrunch** [comment]
Well if you're open to Pull Requests, I can try and make this work and then issue a PR (with example of course).

**Comment by nmoinvaz** [comment]
That would be great.
