### ISSUE TITLE
Incomplete instructions for Windows?

### ISSUE THREAD

**Issue by dislimit** [nmoinvaz/minizip#271]
Following your instructions for Windows.
c:\git\zlib>cmake . -DCMAKE_INSTALL_PREFIX=%PROGRAMFILES%\zlib
**CMake Error:** The source directory "C:/git/zlib/Files/zlib" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

- Do we need to download zlib and set a source dir var to its path?
- Do we have to run the command line OR cmake on MInGW?

For people who are new to cmake in Windows.

Thank you!

**Comment by nmoinvaz** [comment]
Let me know if you figure it out and I can update the documentation.
