### ISSUE TITLE
Static x64 library issue

### ISSUE THREAD

**Issue by jackson5-sec** [nmoinvaz/minizip#274]
Hey,

having issues building x64 static lib.
`
cmake . -DTEST_ON=ON -DCMAKE_GENERATOR_PLATFORM=x64

cmake --build . --config Release
`
Is that the correct cmake flag to build x64? Getting LNK1112 machine type conflicts with target error

**Comment by nmoinvaz** [comment]
Have you also built zlib as x64? What are you errors?

**Comment by jackson5-sec** [comment]
im an idiot lol, my build file didn't specify x64 for zlib. thanks!
