### ISSUE TITLE
basing my project on minizip

### ISSUE THREAD

**Issue by dislimit** [nmoinvaz/minizip#278]
Hi @Nathan, I'm considering basing my project on minizip. Would be great to have some expert advice from you. Is there a way we can have a quick discussion please? Sorry to post it here as I can't find your contact method.

Please Feel free to email me the contact method virginia_lee2008 at yahoo dot com.

Looking forward to your reply!

Best regards,

**Comment by nmoinvaz** [comment]
You can e-mail me at nathan@nathanm.com
