### ISSUE TITLE
drop '#ifdef HAVE_ZLIB' from mz_compat.h?

### ISSUE THREAD

**Issue by praiskup** [nmoinvaz/minizip#309]
Commit 41331dd3ec0033c11b023445fbc8ee6b079843fd added:

```patch
+#ifdef HAVE_ZLIB
 #include "zlib.h"
+#endif
```

Which complicates compat work;  simply -> those who want to replace zlib's header by <mz_compat.h> also have to define `HAVE_ZLIB`.

**Comment by nmoinvaz** [comment]
I don’t understand. It is not necessary to compile with zlib. You can compile with only lzma hence the HAVE_ZLIB indicates that you want to use zlib.

**Comment by praiskup** [comment]
well, maybe I am missing something..  I wanted to say that I thought that `mz_compat.h` is supposed to be 1:1 replacement for the headers in zlib/contrib/minizip.  But trying to port two packages, I've faced several incompatibilities .. (being forced to define HAVE_ZLIB explicitly is one of them, there are some missing constants packages seem to use, etc.)

I'm not sure, porting to this minizip implementation is not trivial, is it supposed to be?  Maybe we could make the move easier.

So far I reported psi-im/psi/issues/388 and assimp/assimp/issues/2121.

**Comment by nmoinvaz** [comment]
I see. What are the other constants? If you use CMAKE to compile the project, it automatically adds everything you need. Are you just dropping in the files? I don't know if there is a way to just make it work for those other constants.

**Comment by nmoinvaz** [comment]
In 2.5.2 release, #include "zlib.h" was removed from mz_compat.h. Maybe this is a case of using an older version of the library?

**Comment by praiskup** [comment]
We tried to build against `2.5.0`.

> What are the other constants?

One project required about a dozen of them.  And even after back-porting those, I wasn't able to build (some methods missing, etc.).

I'll give it another run as soon as I have some time and update this ticket;  but some migration docs/guidance for existing projects would be awesome.

**Comment by Coeur** [comment]
>We tried to build against 2.5.0.

Could you give a try against 2.5.2 as recommended by Nathan? The history of this file shows there is a continuous effort to solve compatibility issues: https://github.com/nmoinvaz/minizip/commits/master/mz_compat.h

**Comment by nmoinvaz** [comment]
I have added some upgrade info also to:
https://github.com/nmoinvaz/minizip/wiki
Hopefully that helps.
