### ISSUE TITLE
unzReadCurrentFile crashes if pass NULL as parameter password in method unzOpenCurrentFilePassword

### ISSUE THREAD

**Issue by Pixmap** [nmoinvaz/minizip#32]
Hi!

Crash occurs in line 1408 because parameter s->pcrc_32_tab used without initialization.
Initialization of this parameter occurs in the method unzOpenCurrentFile3 only if password != NULL.
In original minizip 1.1 for this purpose used flag s->encrypted, but it can be fixed without this flag just if 
set s->pcrc_32_tab=0 in unzOpenCurrentFile3 and check it before use  s->pcrc_32_tab in line 1395

``` if ( s->pcrc_32_tab && ( (s->cur_file_info.flag & 1) != 0 ) )
{
...
}```

**Comment by nmoinvaz** [comment]
Thank you, I have updated the code.
