### ISSUE TITLE
New implementation of mz_stream_pkcrypt_update_keys break the "PK Traditional Encryption"

### ISSUE THREAD

**Issue by laveux** [nmoinvaz/minizip#322]
Changes to pkcrypt to use crc32 update function instead of doing calculation from crc32 table will not decrypt zip files created with previous versions (and created zip files will not be compatible with the older versions).

It seems (uint32_t)~pkcrypt->crc32_update(~pkcrypt->keys[0], &buf, 1) != (uint32_t)CRC32((*(keys+0)), c)

**Comment by nmoinvaz** [comment]
Do you have an example of a encrypted zip?

**Comment by nmoinvaz** [comment]
I created a PK encrypted zip file using 7-zip and used minizip to extract it successfully on Windows. Perhaps your issue is compiler specific?

**Comment by laveux** [comment]
It seems you're right. I'll investigate further
