### ISSUE TITLE
want legacy encoding support cjk dbcs codepage

### ISSUE THREAD

**Issue by xwxbug** [nmoinvaz/minizip#328]
in 90's ,many file use dbcs character sets in chinese japanese korea(CJK).or other dbcs  character sets.
minizip support cp437 codepage ,need a option to support cp932 cp936 cp950 and so on.

[test_demo_cp950.zip](https://github.com/nmoinvaz/minizip/files/2527729/test_demo_cp950.zip)

**Comment by nmoinvaz** [comment]
I currently don't have any plans to support additional character sets - only CP437 is named in the ZIP app note. If you make a pull request I will consider it. Thanks.
