### ISSUE TITLE
Update .gitignore for Mac

### ISSUE THREAD

**Issue by catlan** [nmoinvaz/minizip#33]
Please add .DS_Store to your .gitignore. Or better all the lines from https://github.com/github/gitignore/blob/master/Global/OSX.gitignore

Thx for keeping minizip up-to-date!

**Comment by nmoinvaz** [comment]
I don't see a .DS_Store file in the repository though. Thanks for the cool resource!

**Comment by catlan** [comment]
.DS_Store files are created inside every folder you visit with the OS X Finder. So as soon as you visit the folder the repo is dirty. 

Dictated But Not Read

**Comment by nmoinvaz** [comment]
I don't have a .gitignore file in my repository. From what I've read on StackOverflow, the .gitignore file shouldn't be checked in to repositories.
