### ISSUE TITLE
Adding a file currently being written

### ISSUE THREAD

**Issue by chrfle** [nmoinvaz/minizip#332]
Hello

Is there any specific reason minizip does not allow adding files that are open in write mode?

I tracked it down to this line:
https://github.com/nmoinvaz/minizip/blob/master/mz_strm_os_win32.c#L75

Where it's explicitly stated that only files that are open read only are allowed to be added.

Changing it to FILE_SHARE_READ | FILE_SHARE_WRITE seems to solve it for my application. Would you mind such a change upstream?

**Comment by nmoinvaz** [comment]
Can you explain to me the use case a bit more. In what use case would it be okay to simultaneously write to the zip file as another process? Is it another zip file program has opened the zip?

**Comment by chrfle** [comment]
In our case it's two different threads in the same process.

We record one or more streams of data. When the user decides to save the project we create an info file with some metadata and zip that together with the data streams into a single project file. We would like to be able to do this while data is still being recorded.

This used to work in the 1.1 version of minizip. And it works on Linux in 2.5.3 that we are currently using. I assume it works on mac too, but haven't tested. But not on Windows due to the READ share mode.

**Comment by nmoinvaz** [comment]
I have made the commit in the dev branch. Thanks.

**Comment by chrfle** [comment]
Great, any estimate for when it will hit a "stable" (read tagged) release? Our software security department are iffy about using dev branches ^_^

**Comment by nmoinvaz** [comment]
Probably sometime later this week.
