### ISSUE TITLE
Specify which zlib to use

### ISSUE THREAD

**Issue by chrfle** [nmoinvaz/minizip#336]
Hello

Is it possible to specify which zlib to use during compilation. I'm compiling on Ubuntu 16.04 which has 1.2.8 zlib. I would like to use 1.2.11 however. I made some crude hacks in the CMakeList file to not search for zlib but do the git stuff instead.

It would be very nice with something like:
cmake -DZLIB_VERSION=v1.2.11

Which would use the git and checkout the v1.2.11 tag and build that for inclusion into minizip.

I have no knowledge of how cmake works so I don't know if this is possible.

(btw, you seem to have a typo in the url to company page on https://github.com/solidstatenetworks)

**Comment by nmoinvaz** [comment]
Should be gtg in the dev branch now. Use -DZLIB_TAG=v1.2.11. Thanks for letting me know about the URL.
