### ISSUE TITLE
Cannot extract AndroidManifest.xml from valid apk file.

### ISSUE THREAD

**Issue by mstoicoi** [nmoinvaz/minizip#337]
[archive_bug.zip](https://github.com/nmoinvaz/minizip/files/2550110/archive_bug.zip)
Unfortunately minizip is unable to extract the attached archives.
These are valid android applications (apk). They install on the phone and run. They are malware.
```

Minizip 2.7.3 - https://github.com/nmoinvaz/minizip
---------------------------------------------------
Archive 6d60779a0e36bf4f025c60cd403cc646.apk
Extracting META-INF/MANIFEST.MF
Extracting META-INF/NM-2LCA8.SF
Extracting META-INF/NM-2LCA8.RSA
Extracting assets/D5j5-FcgbHGYWvA1IKkiZ7iS.db
Extracting res/drawable/ic_launcher.png
Extracting res/xml/lksxmlvqbsyq.xml
Extracting Ç\ε╓B☻
Error -111 saving zip entries to disk 6d60779a0e36bf4f025c60cd403cc646.apk
```

```
Minizip 2.7.3 - https://github.com/nmoinvaz/minizip
---------------------------------------------------
Archive c6afb83ab23a6e031ced03506d383d4a.apk
Extracting META-INF/MANIFEST.MF
Extracting META-INF/CGEUTKAN.SF
Extracting META-INF/CGEUTKAN.RSA
Extracting assets/_el16j_lk2JuxvXzWSMsEo8_.db
Extracting res/drawable/ic_launcher.png
Extracting res/xml/zypdmtjtbnvb.xml
Extracting ≡C£↓)☻
Error -111 saving zip entries to disk c6afb83ab23a6e031ced03506d383d4a.apk
```

Issue is with AndroidManifest.xml file
![image](https://user-images.githubusercontent.com/44784453/48019695-ba055880-e13c-11e8-8f31-4c19cfa67f5b.png)

**Comment by nmoinvaz** [comment]
Looks like the extrafield is malformed. I have added some extra checks in to make sure that it doesn't cause any damage and fixed the filename so it is read in such cases correctly. Check dev branch for changes. Thanks for reporting.

**Comment by Coeur** [comment]
>They are malware.

Ah ah, so the request is to support malwares? ;)

**Comment by mstoicoi** [comment]
> Check dev branch for changes.

Works great! Thank you, Nathan!
