### ISSUE TITLE
Error opening apks

### ISSUE THREAD

**Issue by mstoicoi** [nmoinvaz/minizip#339]
Hello,

More problems trying to open apks.

[error_opening_115_103.zip](https://github.com/nmoinvaz/minizip/files/2552792/error_opening_115_103.zip)

Archive password is: infected

These are valid apks. They install on Android. Minizip cannot open.

Regards

**Comment by nmoinvaz** [comment]
I was able to extract it properly. Perhaps you didn't use `-p infected`? What is the error you get?

**Comment by mstoicoi** [comment]
the archives with the issue are in the password protected archive.

**Comment by nmoinvaz** [comment]
1a829135600e19cb0b158390589d603a - the size of the comment for the central directory is incorrect.
52d92aa4b550816dcd76f97cb7efb465 - i have compensated for this one, but again I believe the offsets for the central directory is incorrect
ec9fd7edba0a07c309e9538bd0e915a8 - the size of the comment for the central directory is incorrect.
