### ISSUE TITLE
Error -103 saving zip entries to disk

### ISSUE THREAD

**Issue by mstoicoi** [nmoinvaz/minizip#340]
Hello,

Minizip cannot extract AndroidManifest.xml.

[cannot_extract_103.zip](https://github.com/nmoinvaz/minizip/files/2552859/cannot_extract_103.zip)
Archive password is: infected

Regards

**Comment by nmoinvaz** [comment]
It doesn't seem to contain AndroidManifest.xml. Did you upload the correct apk?

**Comment by mstoicoi** [comment]
the problem is with the archive inside the. There is also a log of minizip.exe output.

**Comment by nmoinvaz** [comment]
Looks like the central directory has incorrect offset. I have made some changes that will help to compensate.
