### ISSUE TITLE
Error -103 opening zip file (APK)

### ISSUE THREAD

**Issue by mstoicoi** [nmoinvaz/minizip#342]
Another problem with an Android Application Package

```
Minizip 2.7.4 - https://github.com/nmoinvaz/minizip
---------------------------------------------------
Archive 012bdf6064462522bd052f91e8ebbba7.apk
Error -103 opening zip file 012bdf6064462522bd052f91e8ebbba7.apk
```
Archive password is: `infected`
[Error_103_opening.zip](https://github.com/nmoinvaz/minizip/files/2557507/Error_103_opening.zip)

**Comment by nmoinvaz** [comment]
In this case, I can compensate for incorrect central directory offset - however, local file info offsets are also incorrect. Right now, I don't plan to do anything for that case.
