### ISSUE TITLE
Compile fails when compiling with -Wformat

### ISSUE THREAD

**Issue by akmistry** [nmoinvaz/minizip#344]
On a 64-bit Linux system, compilation fails when compiling with -Wformat:
../../third_party/minizip/src/mz_zip.c:671:13: error: format specifies type 'unsigned long long' but the argument has type 'int64_t' (aka 'long') [-Werror,-Wformat]
            file_info->disk_offset);

https://github.com/nmoinvaz/minizip/commit/effc1428ff3fd3673d9d40deb3c69c4b6e8f25cb made printf non-portable. inttypes.h is the C99 way of portably formatting integers.

**Comment by nmoinvaz** [comment]
I had @vszakats was saying that it requires MSVC2010 to compile at the least. So I think the minimum requirements are going to have to require inttypes.h or not.

**Comment by nmoinvaz** [comment]
I have changed it back the way it was. The cmake script will create a dummy inttypes.h if it doesn't exist.

**Comment by vszakats** [comment]
The problem with C99 is that MSVC to this day doesn’t fully supports it and chances aren’t high that it’ll ever do. Original zlib was C89. So this change makes it harder to use minizip2 as a plug-in replacement. Is there any reason why the previous, more portable solution wasn’t workable here?

**Comment by Coeur** [comment]
PRId32 and PRId64 everywhere was quite ugly for readability.
Having VS2012 or newer as a minimal requirement is also reasonable.

**Comment by vszakats** [comment]
Yes, `printf()` portability oddities don't help with readability, but they are necessary to make certain C compilers/RTLs happy. This isn't just about MSVC, and I'm not even using MSVC specifically, but, if the goal is make minizip2 a plug-in replacement for original minizip, it'd be best to aim for the same level of portability (C89). Otherwise each dependent projects will have to adjust their own portability target accordingly, which may be desired by some of them. (It's still one main reason I keep original minizip as a parallel option, and refrain from adopting native minizip2 APIs.)

**Comment by akmistry** [comment]
@Coeur Yeah, those macros are ugly. But unfortunately, they're the standard (and really, only portable) way of formatting fixed-width types.

Personally, I'm glad minizip2 is using C99 and fixed-width types. I think it makes the code more platform-neutral and eliminates certain poorly behaviour and platform-specific bugs. I get that there are platforms out there that don't support C99 (or do it well), but it's 2018 and I think C99 is a reasonable requirement today. And if your compiler doesn't support stdint and inttypes, then honestly, I think the platform you're using has more fundamental issues.

**Comment by vszakats** [comment]
My point is that such decisions impact all dependent projects upstream, so however much we like the newer/cleaner solution, it's often necessary and/or useful to go for a lower common denominator. Usually there are fairly painless solutions to keep the code clean, while also minding older standards.

**Comment by nmoinvaz** [comment]
I agree that C99 is a reasonable requirement. I’ve advertised mz2 as a modern implementation in the same way that zlib-ng is a modern implementation of zlib. Additionally the liblzma library which I’m using also requires C99.

**Comment by Coeur** [comment]
For the record, (SS)ZipArchive, when used as a pod, is configured to build minizip C files with `[-std=gnu11]` (latest flavor of C available with Xcode).

**Comment by vszakats** [comment]
This is the problem of (SS)ZipArchive. Besides licensing, another critical property of projects is how portable they are, these two determine if a project can be considered at all. The world is wider than iOS-toolchains or even GNU toolchains, and I still cannot see a reason to artificially limit portability for the sake of being "modern", in case there is a better, universal way, with minimal or zero extra effort required.

Requiring GNU11 is a rare luxury that not too many FOSS project would select, unless their target is a specific platform, iOS and the Apple toolchain in case of (SS)ZipArchive. Another minizip2 alternative however, [`libzip`](https://libzip.org/) appears to be highly portable, written in plain C89.

The question isn't even that `inttypes.h` should be used or not, but _how_ to use, and whether to allow this project to compile without it, in case this is required. Current solution of dynamically creating a fake `inttypes.h` inside one specific build-system (CMake) is just quite bad. It's easy to fix though.

**Comment by nmoinvaz** [comment]
Even if the problem with inttypes.h is solved I still use stdint.h which is also C99.

**Comment by vszakats** [comment]
Regarding `stdint.h`, it requires MSVC ~2010 (while also not supported in some more obscure C compilers and older versions of GNU toolchains) and, if I can believe my old ChangeLogs, it's buggy in MSVC 2010 by missing `int32_t`, but I can't double-check that anymore, and maybe it was a hosed environment. Google turns up hits saying MSVC 2010 is missing `stdint.h`, well, anyway, it's messy.

One general solution is to assume that each C89 project have their own home-grown fixed-width types, or their C compiler offers non-standard fixed-width alternatives. Then, short of `stdint.h` support, they may remap the standard types to the ones they have at hand. To let this happen without locally patching minizip2 sources, minizip2 may have a `HAVE_CONFIG_H` macro, which when defined, would include a `config.h` e.g. via `mz.h`. The content of `config.h` is entirely up to the user project. This method may also resolve a missing `inttypes.h` situation and most anything else that may come up in the future. This pushes the task of supporting non-C99 environments entirely to the user.

Slightly more user-friendly method is to provide solutions inside `mz.h` for the more common and/or known `config.h`-workarounds. This is inevitably more "costly" for the maintainer. It's a balance to be made between maintainability/testability and out-of-the-box portability, and wholly optional.

**Comment by nmoinvaz** [comment]
I would support the use of a config. I know liblzma does this too.

https://github.com/nmoinvaz/minizip/blob/master/lib/liblzma/common/sysdefs.h

**Comment by nmoinvaz** [comment]
I have made some changes. Anybody not using cmake will have to set HAVE_INTTYPES_H and HAVE_STDINT_H. This is the way that liblzma works too. 

However, for liblzma, it will also require: HAVE_LIMITS_H, HAVE_STRING_H, HAVE_STRINGS_H, HAVE_MEMORY_H, HAVE_STDBOOL_H and HAVE_IMMINTRIN_H - all of which cmake will auto-detect now too. Before it was just hard coded in lib\liblzma\config.h.
