### ISSUE TITLE
Why the examples are so complicated?

### ISSUE THREAD

**Issue by sukhchainn** [nmoinvaz/minizip#346]
I'm a beginner and I find minzip's examples very difficult. I have used some GUI libs and their examples were very easy and self explanatory. 

Am I too fragile or are these examples designed the way that beginners find them difficult?

**Comment by nmoinvaz** [comment]
What parts are hard to understand?

**Comment by sukhchainn** [comment]
sorry, it just that I'm not accustomed to the code without comments. That's why it seems difficult but I'm starting to follow now.

**Comment by nmoinvaz** [comment]
I will try to add more comments in.
