### ISSUE TITLE
Got files after decompressing a folder

### ISSUE THREAD

**Issue by ozelcan** [nmoinvaz/minizip#347]
I have a directory in a zip file, after i decompress it i got files just like named "foldername1\innerfolder1\file.txt". I was expecting a decompressed folder structure not just files. Is there a way to decompress as folder sutructure?
![capture](https://user-images.githubusercontent.com/36914521/48754984-cba24080-eca4-11e8-8e06-1b6b4c910df4.PNG)

**Comment by nmoinvaz** [comment]
Can you attach the zip file?

**Comment by ozelcan** [comment]
The actual problem is about my compressed file not the minizip. Sorry for the issue:') You can close this issue

**Comment by nmoinvaz** [comment]
I have made a change that will format the paths correctly regardless of the slash. Thanks.

**Comment by ozelcan** [comment]
Thanks for the solution, great!
