### ISSUE TITLE
Error -3 when extracting with AES256

### ISSUE THREAD

**Issue by tamasszarka** [nmoinvaz/minizip#348]
Hi Nathan,
I'm trying to use minizip 2.7.5 to extract a password-protected zip with WinZip AES256.
I tried multiple archives, one generated with .NET [Ionic.Zip](https://archive.codeplex.com/?p=dotnetzip) and another with 7-zip for Windows.

I'm experimenting with the command line minizip.exe app provided, but get the same error for both type of files:

```
d:\minizip\minizip-2.7.5\Debug>minizip.exe -x -d "d:\minizip\test\extract" -s -p lorem "d:\minizip\test\test.zip"
Minizip 2.7.5 - https://github.com/nmoinvaz/minizip
---------------------------------------------------
Archive d:\minizip\test\test.zip
Extracting dir1/
Extracting dir1/x.txt
Error -3 saving zip entries to disk d:\Rhino\minizip\test\test.zip
```

I'm on Windows, using VS 2015 toolset and building x64. I debugged it all the way down to zlib/inflate.c, on the minizip level everything seems reasonable until then.

Here is the file I used, this was created with 7-zip with the below settings: [test.zip](https://github.com/nmoinvaz/minizip/files/2611890/test.zip)

password: lorem
settings used:
![settings](https://user-images.githubusercontent.com/33751967/48962738-a9e6d900-ef84-11e8-8e95-d310af41b206.png)

Any help is greatly appreciated.

**Comment by tamasszarka** [comment]
Thanks for the quick feedback. I confirm it works with `USE_BRG=ON`.

**Comment by nmoinvaz** [comment]
It should be fixed now in the `dev` branch. Thanks!
