### ISSUE TITLE
2.8.0: Inttypes macro re-defined warnings

### ISSUE THREAD

**Issue by evanmiller** [nmoinvaz/minizip#353]
Compiling Minizip 2.8.0 with [Objective-Zip](https://github.com/gianlucabertani/Objective-Zip) produces warnings such as:

```
In file included from /XXX/OZZipWriteStream.m:37:
In file included from /XXX/OZZipWriteStream+Internals.h:36:
In file included from /XXX/usr/include/mz_compat.h:17:
/XXX/usr/include/mz.h:169:11: warning: 'PRId8' macro redefined [-Wmacro-redefined]
#  define PRId8  "hhd"
```

It appears that the PRIxx macros are being re-defined because `HAVE_INTTYPES_H` is not defined in the client application code. I would suggest moving anything to do with `HAVE_INTTYPES_H` or `HAVE_STDINT_H` out of the public API, or else wrapping each macro with a definition check:

```
#ifndef PRId8
#  define PRId8  "hhd"
#endif
```

etc

**Comment by nmoinvaz** [comment]
I do this already in the `dev` branch.
