### ISSUE TITLE
Unable to compile. Tried both VS & CMake standalone.

### ISSUE THREAD

**Issue by Mugsy323** [nmoinvaz/minizip#354]
I'm trying to compile "minizip", but I keep getting the (noted) zlib error.

In "Visual Studio 2017", I get:

_Error - CMake Error at D:/Program Files (x86)/VisualStudio/2017/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/ExternalProject.cmake:2324
(message): - D:/Program Files (x86)/VisualStudio/2017/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/ExternalProject.cmake	2324_

When attempting to compile using the "CMake 3.13.2" standalone GUI, I get:

_error: could not find git for clone of zlib_

(I got this same error the first time I tried to compile using VS.)

I've tried following the instructions on the "wiki" page. I downloaded "Zlib", but the folder contents don't appear to match the instructions. And attempting to compile Zlib using CMake gives me the same error (can't find zlib.)

I've tried all of the suggested solutions from an elevated/Admin command prompt, but nothing works. I'm stumped.

FOLLOW-UP: After much Trial & Error, I was able to "build" the project using CMake (using CMake errors to tell me where to properly place the Zlib files). When complete, it created not a finished DLL but instead a collection of "Visual Studio", "Visual-C" project files. I opened the project in VS and tried to Build the project (using both "Build" & "BUILD_ALL") and neither produced any output (despite reporting "success".)

**Comment by nmoinvaz** [comment]
Looks like you don’t have git installed which is necessary if you are expecting it to clone  zlib repository. Not sure why you aren’t getting any outputs. The projects only build statically linked libraries.

**Comment by nmoinvaz** [comment]
I added a note about git needing to be installed to the wiki. Thanks.

**Comment by nmoinvaz** [comment]
https://git-scm.com/
