### ISSUE TITLE
Support for passwords with NUL character?

### ISSUE THREAD

**Issue by Iniesta8** [nmoinvaz/minizip#356]
Hi,

first of all, thank you for your work.

I was wondering if there is any way to use passwords containing NUL characters. The password given to the zip_writer is only a pointer to char and there is no parameter to pass the length of the given password to the function. When using the OpenSSL's rand_bytes() function to generate random bytes it is absolutely possible to get random data containing the NUL character. When passing these data as password to minizip functions the secret will be truncated.

How can we deal with this issue?

**Comment by nmoinvaz** [comment]
I recommend writing a function that converts the random bytes to a random ascii string. This article may be helpful: https://codereview.stackexchange.com/questions/29198/random-string-generator-in-c

**Comment by vszakats** [comment]
Converting the byte stream to a list of visible characters is one solution. E.g. using base64 encoding, hex representation or similar.

**Comment by Coeur** [comment]
If you want to maximize the possible characters, you could go as far as:
- base1112062 for all unicode scalar endpoints except 0: [1...0xD7FF + 0xE000...0x10FFFF](https://developer.apple.com/documentation/swift/unicode/scalar/2905753-init), but that comes with potential other issues
- base135480 for a reasonable printable [subset of current Unicode](https://en.wikipedia.org/wiki/Template:General_Category_(Unicode)): Letter (L, 125643 chars) + Number (N, 1754 chars) + Punctuation (P, 792 chars) + Symbol (S, 7291 chars)
- base94 for all ascii printable characters
- base64, as there is often a built-in implementation everywhere (.NET, iOS, PHP, ...)
- base16, quite a waste of bytes, so only if you're lazy
