### ISSUE TITLE
 Files are mistakenly listed as encrypted

### ISSUE THREAD

**Issue by Iniesta8** [nmoinvaz/minizip#359]
Hey,

I came across an error when using the example program to list the content of a zip file. Normally, each entry of the minizip_list() output has an asterisk if the respective file is encrypted with a password.
But, when adding files to an existing zip file the output is incorrect right after the first addition of an encrypted file: All unencrypted files that are added after an encrypted file will also be mistakenly listed as encrypted files (by containing an asterisk).

Thanks in advance.

**Comment by nmoinvaz** [comment]
Thanks for reporting. I have fixed the issue in the dev branch.
