### ISSUE TITLE
need cmake/mingw cross-compiling instructions

### ISSUE THREAD

**Issue by hackoon** [nmoinvaz/minizip#360]
I need to compile the windows dll on linux/mingw  
I didn't succeed.
What I did so far:
added a cmake/i686-w64-mingw32.cmake 
```

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR i686)
set(TOOLCHAIN_PREFIX i686-w64-mingw32)

set(CMAKE_C_COMPILER     "${TOOLCHAIN_PREFIX}-gcc")
set(CMAKE_CXX_COMPILER   "${TOOLCHAIN_PREFIX}-g++")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_CROSS_COMPILING TRUE)

```
used:

cmake -DCMAKE_TOOLCHAIN_FILE=./cmake/i686-w64-mingw32.cmake

but in the end I only get:
[100%] Linking C static library libminizip.a
[100%] Built target libminizip

but I need the dll

**Comment by nmoinvaz** [comment]
There currently is no dll.

**Comment by nmoinvaz** [comment]
In the `dev` branch you may be able to build cmake with  `-DBUILD_SHARED_LIBS=ON -DMZ_BUILD_TEST=OFF` and this will create a DLL that exports only the compatibility layer functions on Windows. I haven't tested it on any other platform, but on other platforms it may export all functions.
