### ISSUE TITLE
make install always installing on /usr/local

### ISSUE THREAD

**Issue by gluttony38** [nmoinvaz/minizip#363]
Hi,

First thanks for your work.

I just tried to build and install your lib (last release: v2.8.3) in a different folder than the default one (seems to be _/usr/local_) but it seems not possible, here's what I've done:
```
cmake . -DCMAKE_INSTALL_PREFIX="/tmp/test"
make -j32
make install
```
But I can see in logs (and the files are actually where the log said):
```
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib64/minizip.a
[...]
-- Installing: /usr/local/include/mz_compat.h
[...]
-- Installing: /usr/local/lib64/pkgconfig/minizip.pc
```
I can see in _cmake_install.cmake_ (generated after run of _cmake_) I actually have, at beginning of file:
```
# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/tmp/test")
endif()
```
But after that there is a lot hard coded _/usr/local_, and, in order to have it installed in expected folder I had to do a search and replace all _/usr/local_ by _${CMAKE_INSTALL_PREFIX}_ in this file.

If it's a bug it would be fine to fix this for a next version, else, could you please explain how to perform an installation in a different folder than _/usr/local_.

Thanks.

**Comment by gluttony38** [comment]
Hi again,

In fact after some manipulations (I'm doing a script to extract build and install minizip automatically), I've seen that this issue occurs only on subsequent _cmake_ runs.

For example, with freshly extracted archive, if I run a _cmake . -DCMAKE_INSTALL_PREFIX="/tmp/test"_ it will be OK, but if after that I run for example a _cmake . -DCMAKE_INSTALL_PREFIX="/home/user/minizip"_, the _cmake_install.cmake_ file will still contain hardcoded _/tmp/test_ from previous run.

Thanks

**Comment by nmoinvaz** [comment]
You probably have to delete your cmake cache and _cmake_install.cmake_ between runs that set different values for CMAKE_INSTALL_PREFIX.

**Comment by gluttony38** [comment]
Ok, thanks for your answer, indeed, changing _CMAKE_INSTALL_PREFIX_ on cmake run changes it in _CMakeCache.txt_ but does not change _INSTALL_BIN_DIR_, _INSTALL_CMAKE_DIR_, ...

In any case, on my side I have no more issue since when I need to make/install I always build from scratch (delete build folder, extract tar.gz then run cmake with proper _CMAKE_INSTALL_PREFIX_, build and install).

**Comment by nmoinvaz** [comment]
It might be that INSTALL_BIN_DIR, INSTALL_CMAKE_DIR need FORCE set in CMakeList.txt. For example:

```
set(INSTALL_BIN_DIR ${CMAKE_INSTALL_FULL_BINDIR} CACHE PATH "Installation directory for executables" FORCE)
```
