### ISSUE TITLE
problem with out of tree cmake install

### ISSUE THREAD

**Issue by bartekkr** [nmoinvaz/minizip#371]
replace please following code in CMakeLists.txt:

`set(MINIZIP_PC ${CMAKE_CURRENT_BINARY_DIR}/minizip.pc)`
`if(EXISTS ${MINIZIP_PC}.cmakein)`
`    configure_file(${MINIZIP_PC}.cmakein ${MINIZIP_PC} @ONLY)`
`endif()`

with the:

`set(MINIZIP_PC ${CMAKE_CURRENT_BINARY_DIR}/minizip.pc)`
`set(MINIZIP_PC_IN ${CMAKE_CURRENT_LIST_DIR}/minizip.pc.cmakein)`
`if(EXISTS ${MINIZIP_PC_IN})`
`    configure_file(${MINIZIP_PC_IN} ${MINIZIP_PC} @ONLY)`
`endif()`

because file ${CMAKE_CURRENT_BINARY_DIR}/minizip.pc.cmakein not exists when building out of source

**Comment by nmoinvaz** [comment]
I believe you may be on an older version. Those two lines in master branch are:

```
set(MINIZIP_PC ${CMAKE_CURRENT_BINARY_DIR}/minizip.pc)
configure_file(minizip.pc.cmakein ${MINIZIP_PC} @ONLY)
```

**Comment by bartekkr** [comment]
Hi, yes, indeed i have used version tagged as 2.8.4
regards,
