### ISSUE TITLE
Generated zip archive is empty

### ISSUE THREAD

**Issue by lzzy12** [nmoinvaz/minizip#372]
I am trying to use the library to zip a text file, but instead it is just creating an empty zip archive.
Here is my function which I wrote:
```
    int compress(std::vector<std::string> paths, std::string &destination, const std::string& password, int level) {
    if (level < CS_NO_COMPRESSION || level > CS_BEST_COMPRESSION)
        level = MZ_COMPRESS_LEVEL_DEFAULT;
    void *writer = NULL;
    int err;
    mz_zip_writer_create(&writer);
    mz_zip_writer_set_password(writer, password.c_str());
    mz_zip_writer_set_compress_level(writer, level);
    mz_zip_writer_set_compress_method(writer, MZ_COMPRESS_METHOD_DEFLATE);
    err = mz_zip_writer_open_file(writer, destination.c_str(), originalSize, 0);
    if (err < 0) {
        std::cout << err;
        mz_zip_writer_delete(&writer);
        return err;
    }

    if(err == MZ_OK){
        for (std::string path : paths)
        {
            std::string fileName = path.substr(path.rfind('\\'));
            err = mz_zip_writer_add_path(writer, path.c_str(), NULL, 1, 1);
            if (err < 0)
                return err;
        }
    }
    err = mz_zip_writer_close(writer);
    mz_zip_writer_delete(&writer);
    return err;
}
```
Could you please help me with it?

**Comment by nmoinvaz** [comment]
Try not passing originalSize as the disk size in `mz_zip_writer_open_file`.

**Comment by lzzy12** [comment]
> Try passing 0 instead of originalSize 
value of originalSize is already 0 (I set it in the constructor function of the class I'm writing).

**Comment by lzzy12** [comment]
@nmoinvaz value of originalSize is already 0 (I set it in the constructor function of the class I'm writing).

**Comment by lzzy12** [comment]
Should I try the opposite?

**Comment by nmoinvaz** [comment]
Do you have a full example you can attach?

**Comment by lzzy12** [comment]
@nmoinvaz Hi, I added you as a colaborator. Please accept the request here https://github.com/lzzy12/Compress-Studio/invitations

**Comment by lzzy12** [comment]
did you find any problem with the code?

**Comment by lzzy12** [comment]
@nmoinvaz any help?

**Comment by nmoinvaz** [comment]
I took a look but I'm not exactly sure what is wrong, also for whatever reason I couldn't build the projects. There is very simple example code in minizip.c. Check the values passed to the functions in a debugger and then compare with what you are passing in.

**Comment by nmoinvaz** [comment]
The file it produces is not empty. You can open it up with WinRAR and see that it does contain the file. In Windows Explorer it shows empty because for whatever reason it can't read archives where filenames in the archive contain the full path. You have to either use `mz_zip_writer_add_file` and not specify a full path for filename_in_zip or pass in 0 for include_path when using `mz_zip_writer_add_path`.

**Comment by lzzy12** [comment]
Oh damn it. I could have never ever guessed that. You're genius. Thanks a lot
