### ISSUE TITLE
Wrong number of entries is written if the number of entries is in [UINT16_MAX, UINT32_MAX)

### ISSUE THREAD

**Issue by idezzzz** [nmoinvaz/minizip#373]
https://github.com/nmoinvaz/minizip/blob/4adfffb1dc95ddbed0a1e16aefac449dc4e7ef5f/zip.c#L1906

Here should be `zi->number_entry > UINT16_MAX`

**Comment by lzzy12** [comment]
Hi @idezzzz Can you look into my issue #372 ?
Apparently, the maintainer is busy or no more maintaining the repo

**Comment by nmoinvaz** [comment]
Thanks this has been fixed in 1.2 branch.
