### ISSUE TITLE
Windows Link Error

### ISSUE THREAD

**Issue by ridethepig** [nmoinvaz/minizip#374]
> Error	LNK2019	unresolved external symbol _crc32 referenced in function _mz_crypt_crc32_update  
> Error	LNK2019	unresolved external symbol _deflate referenced in function _mz_stream_zlib_deflate	
> Error	LNK2019	unresolved external symbol _deflateEnd referenced in function _mz_stream_zlib_close		
> Error	LNK2019	unresolved external symbol _inflate referenced in function _mz_stream_zlib_read		
> Error	LNK2019	unresolved external symbol _inflateEnd referenced in function _mz_stream_zlib_close	
> Error	LNK2019	unresolved external symbol _deflateInit2_ referenced in function _mz_stream_zlib_open		
> Error	LNK2019	unresolved external symbol _inflateInit2_ referenced in function _mz_stream_zlib_open		

I have got this when trying to compile minizip.c on Windows10, using VS2017.  
I have checked relevant issues, but they just cannot help.
I built this repo with `-DMZ_BRG` and bzip2 library in the source directory.

**Comment by nmoinvaz** [comment]
It looks like it is not linking zlib correctly. What commands did you run?

**Comment by ridethepig** [comment]
I followed the `configure existing windows installation` section in the wiki.   
I used cmake-gui and added those two configurations.
And by the way, should I add an extra link to zlib.lib when compiling my custom code?

**Comment by nmoinvaz** [comment]
Yeah there is some linking issue with zlib. What if you try both those on one command instead of two like this: 

```
cmake -DZLIB_LIBRARY:FILEPATH="C:\Program Files (x86)\zlib\lib\zlibstaticd.lib" -DZLIB_INCLUDE_DIR:PATH="C:\Program Files (x86)\zlib\include" .
```

**Comment by ridethepig** [comment]
**I think I have solved this problem** by adding an extra link to `zlib.lib` when compiling my custom code like this:
![{36D56AC1-804C-4FDD-8F2F-0664C0CBBEED} png](https://user-images.githubusercontent.com/17285896/54538180-c5ac3a00-49ce-11e9-93aa-cb0882c292fa.jpg)  

Thanks a lot for your time.
(And a notice may be added to the wiki?)

**Comment by nmoinvaz** [comment]
The cmake project should have linked to zlib library. Not sure why it isn't. But glad you got it working.

**Comment by bstaint** [comment]
same question.
must be when compile minizip modify CMakeFiles\minizip.dir\objects1.rsp, add
 > D:/zlib/lib/zlibstaticd.lib

**Comment by nmoinvaz** [comment]
- What version of cmake are you using?
- What is the output from those commands?
- What is the build output?

**Comment by bstaint** [comment]
latest version,
I think this my fault, static library can't link to static library.
