### ISSUE TITLE
memory leakage

### ISSUE THREAD

**Issue by wanfustudio** [nmoinvaz/minizip#376]
Hello,
When I use  version 2.8.5 to extract a zip archive with password, I switch the OPENSSL to ON,  the memory usage is very large.
My zip archive size is about 1.49GB and there are so many tiny files.
The memory will reach about 24GB, which is my physical memory size.
So, Could you please check if it is an issue?
Thanks a lot!

**Comment by wanfustudio** [comment]
Details:
I use this command line to execute a test.
./minizip -x -o -d ~/11231/ -p mypassword /home/wanfustudio/Downloads/myzip.zip

**Comment by nmoinvaz** [comment]
Can you please attach a link to the archive?

**Comment by wanfustudio** [comment]
Thanks for your quick reply.
But I have no upload permission in company. 
I can investigate it further. If I have any news, I 'll comment it here.

**Comment by nmoinvaz** [comment]
I found it. It is fixed in the `dev` branch. Thanks for reporting.
