### ISSUE TITLE
Include limits.h in unzip.c (v1.2 branch)

### ISSUE THREAD

**Issue by exavi** [nmoinvaz/minizip#378]
Thanks for this brilliant repo.

#include <limits.h> to stop the compiler from whining about UINT_MAX not declared.

I have to say that I'm not building with HAVE_AES so perhaps it is being included somewhere in there.

Tested on CentOS x64 (gcc 4.8.5 20150623 RH4.8.5-36)

**Comment by nmoinvaz** [comment]
Thanks!
