### ISSUE TITLE
Add macros for ftello64/ftseeko64 to avoid 64 bit linux crashes (Linux64bit) branch v1.2

### ISSUE THREAD

**Issue by exavi** [nmoinvaz/minizip#380]
On branch 1.2, adding to ioapi.h line 36 the following

`|| (defined(__linux__) && defined(__x86_64__))`

will avoid read/saving crashes.

Tested on CentOS 64 bit (el7) with GCC 4.8.5

**Comment by nmoinvaz** [comment]
Please submit a pull request. Thank you.

**Comment by nmoinvaz** [comment]
I have made some other modification so hopefully that list doesn't have to continue to become super long.
