### ISSUE TITLE
CMAKE_DEBUG_POSTFIX now WIN32 only?

### ISSUE THREAD

**Issue by asmaloney** [nmoinvaz/minizip#382]
I was surprised when I recently built both debug and release on macOS and got the same file name `libminizip.a`.

```cmake
if(WIN32)
    set(CMAKE_DEBUG_POSTFIX "d")
```

Why is this now WIN32 only?

This was changed in commit c4916c971ae975e8344659ea064afcbc24f15a93.

**Comment by nmoinvaz** [comment]
I figured it was only something that WIN32 does or cares about. Shouldn't it be building in separate Debug and Release directories anyways?

**Comment by asmaloney** [comment]
I don't feel super-strongly about it - I can pass it on the command line - I just found it odd based on my experience with other libraries that use cmake.

Maybe my setup is "abnormal" but I build debug & release in their own directories then install them both to the same `lib` directory. My application chooses the correct one from there.

It's also easier to ensure you're linking to the correct build if the name is post-fixed.

**Comment by nmoinvaz** [comment]
I would be more inclined to remove it entirely. I think it can still be specified in the command line ie:
```
cmake . -DCMAKE_DEBUG_POSTFIX="d"
```

**Comment by asmaloney** [comment]
Yes it can - that's what I did.

I just find it useful to have it set by default for all platforms - one less "platform-specific thing".

I took a quick look through the many 3rd party libs I use and it's use is not as consistent as I thought it was.

Just to confuse users, one of them even uses:
```cmake
set(CMAKE_DEBUG_POSTFIX "-dgb")
```
:-)

**Comment by nmoinvaz** [comment]
Interesting. Ok, I have removed it, and it can be set via command line. Thanks for bringing it to my attention.
