### ISSUE TITLE
bzip2: "Use of undeclared identifier 'nBytes'"

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#392]
On iOS, if I try to include the /lib/bzip2/ folder, I get:

>Use of undeclared identifier 'nBytes'

On line:  
https://github.com/nmoinvaz/minizip/blob/4fe06872433fde80652e057d179d5d70a95e8294/lib/bzip2/compress.c#L514

Screenshot:  
<img width="569" alt="Screen Shot 2019-05-06 at 11 50 33 PM" src="https://user-images.githubusercontent.com/839992/57237644-3cbe9000-705a-11e9-998f-8959e7a860dc.png">

**Comment by nmoinvaz** [comment]
Give that a shot.

**Comment by Coeur** [comment]
@nmoinvaz thank you, now it "builds" (Although, I haven't tested the feature itself yet).
Consequently, I've now included bzip2 in the default subspecs: #393.
Still have issues with LZMA, but that's another story.
