### ISSUE TITLE
Can't unzip Brian Gladman AES protected file with Apple CommonCrypto

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#397]
This is a follow up of https://github.com/ZipArchive/ZipArchive/issues/516

1. We create a BRG AES protected file (using ZipArchive based on minizip 1.2), with password "got":
[v1.zip](https://github.com/nmoinvaz/minizip/files/3200472/v1.zip)

2. We build minizip 2.8.7 with Apple Crypt:
```
$ cmake . -DMZ_BZIP2=OFF -DMZ_LZMA=OFF -DMZ_BUILD_TEST=ON
$ cmake --build .
```

3. We attempt to unzip the file:
```
$ ./minizip -x -p got v1.zip 
Minizip 2.8.7 - https://github.com/nmoinvaz/minizip
---------------------------------------------------
-x -p *** v1.zip 
Archive v1.zip
Extracting 1.md
Error -3 saving entries to disk v1.zip
Error -105 closing archive for reading
```

The error is produced on the following line: https://github.com/nmoinvaz/minizip/blob/64c4c7f868467ca21434cced2a418f21d3c6c664/mz_strm_zlib.c#L181

**Comment by nmoinvaz** [comment]
That should fix it. Let me know if you have problems.
