### ISSUE TITLE
zipOpenNewFileInZip()/zipOpenNewFileInZip64() functions missing

### ISSUE THREAD

**Issue by sharkcz** [nmoinvaz/minizip#400]
I have a project which I'm trying to switch to minizip2, but it's using [zipOpenNewFileInZip64()](https://github.com/Sigil-Ebook/Sigil/blob/master/src/Exporters/ExportEPUB.cpp#L146) function that isn't provided by the compat stuff in minizip2, but is available in the original minizip. Is it something that could be easily provided in minizip2?

zipOpenNewFileInZip2()/zipOpenNewFileInZip2_64() seems to be missing too.

**Comment by nmoinvaz** [comment]
I have added them to the dev branch. Thanks.

**Comment by sharkcz** [comment]
Awesome, thanks.
