### ISSUE TITLE
The Problems during compilation

### ISSUE THREAD

**Issue by taozi-xx** [nmoinvaz/minizip#401]
When I use 'cmake CMakeLists.txt' to run cmake in the minizip directory, some errors occured:

> Could` NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 

> No package 'libbsd' found

How to solve these problems?

**Comment by Coeur** [comment]
And your OS and versions are..?

**Comment by taozi-xx** [comment]
OS：ubuntu 16.04
cmake version：3.5.1

**Comment by nmoinvaz** [comment]
Use `cmake . -DMZ_BRG=ON`

**Comment by taozi-xx** [comment]
Ok，thank you very much.
