### ISSUE TITLE
unzOpenCurrentFile returns UNZ_OK on Windows but ZIP_PARAMERROR (-102) on Macos & linux

### ISSUE THREAD

**Issue by Nelson-numerical-software** [nmoinvaz/minizip#403]
When I try to unzip a file, it works on Windows but not on others platforms

see code used here : 
https://github.com/Nelson-numerical-software/nelson/blob/file_archiver/modules/file_archiver/src/cpp/Unzip.cpp

line 94 returns always -102 on linux and macos but OK on windows :(

zip file used for test: 
https://github.com/Nelson-numerical-software/nelson/blob/file_archiver/modules/file_archiver/tests/test_zip.zip

master branch of minizip 2 used.

Bug or did I miss something about minizip ?

**Comment by nmoinvaz** [comment]
Are you able to set a breakpoint on the lines that return UNZ_PARAMERROR & MZ_PARAM_ERROR and see which function is having the problem?

**Comment by Nelson-numerical-software** [comment]
Hi, I digged and found the problem.
on Windows, HAVE_ZLIB is defined and not on others.
I fixed it and it works
Sorry for the noise but it was not easy to localize it.
