### ISSUE TITLE
How to write entries without data descriptors

### ISSUE THREAD

**Issue by kimikage** [nmoinvaz/minizip#407]
In 2.x, entries except directories are stored with the `MZ_ZIP_FLAG_DATA_DESCRIPTOR` flag and followed by their data descriptors.
https://github.com/nmoinvaz/minizip/blob/edebe6891d836f419abc824a706bb021881b0a26/mz_zip.c#L1946-L1954
I know that it is suitable for the stream writers. 
But is there a simple way to write entries without the data descriptors?

**Comment by nmoinvaz** [comment]
There is no simple way to do that. I'm curious what is your use case?

**Comment by nmoinvaz** [comment]
Maybe you can comment out the line:
```
zip->file_info.flag |= MZ_ZIP_FLAG_DATA_DESCRIPTOR;
```
Or pass in to the `mz_zip_entry_write_open` function, `file_info` with negative flag set:
```
file_info->flag = ~MZ_ZIP_FLAG_DATA_DESCRIPTOR;
```

**Comment by kimikage** [comment]
> There is no simple way to do that. I'm curious what is your use case?

In my case, the generated archives are used as something like in-memory key-value store.
The size of each file in a Zip is not so large(< 32 KiB) and the number of the files is large.
The 16 bytes of the data descriptor is negligibly small in the memory capacity of modern PCs, you know.
However, they are wasteful of the L2 or L3 caches.

It would be a best practice to use the optimal key-value store instead of Zip, but I don't want to redesign the current tool-chain.

Thank you for your advice.

**Comment by nmoinvaz** [comment]
There is now a `mz_zip_set_data_descriptor` function that can be used to enable/disable writing data descriptors.
