### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by l0phtgh0st** [nmoinvaz/minizip#41]
When I try to use minizip in my project, I got linking error below. Does minizip depend on any external library and where can I get the library (if it depend on it)?

unzip.obj: -1 : error: LNK2019: unresolved external symbol inflate referenced in function unzReadCurrentFile

unzip.obj: -1 :  error: LNK2019: unresolved external symbol inflateEnd referenced in function unzCloseCurrentFile

unzip.obj: -1 :  error: LNK2019: unresolved external symbol crc32 referenced in function unzReadCurrentFile

unzip.obj: -1 :  error: LNK2019: unresolved external symbol inflateInit2_ referenced in function unzOpenCurrentFile3

unzip.obj: -1 :  error: LNK2019: unresolved external symbol get_crc_table referenced in function unzOpenCurrentFile3

**Comment by nmoinvaz** [comment]
It depends on zlib.
