### ISSUE TITLE
CRC issue with deflate compression and a read loop

### ISSUE THREAD

**Issue by rddesmond** [nmoinvaz/minizip#414]
With a particular output buffer, a zip file with an AES encrypted (this may be red herring) and zlib compressed item fails reading with a CRC error.  I noticed it with a buffer size of 8192 and a uncompressed item of size  7077903, but I saw it at some other combinations. 

On investigation, it appears that zlib::inflate may read data from the input buffer and/or write it to the output buffer, but not neccessarily both. "[If inflate returns Z_OK and with zero avail_out, it must be called again after making room in the output buffer because there might be more output pending.](https://www.zlib.net/manual.html)"  This means: zlib may consume X bytes, decompress them to an internal buffer, and then output the decompressed results over multiple calls.  In the current implementation of `mz_strm_zlib`, the decompress loop will be escaped if there is no data to read and the minizip controlled buffer is empty, though there may be more data to output.

[main.cpp.zip](https://github.com/nmoinvaz/minizip/files/3581666/main.cpp.zip) is a test script that shows the problem.

Tested against minizip 2.8.9 (also 2.8.1) with
- iconv 1.15
- OpenSSL 1.0.2p
- bzip2 1.0.6
- zlib 1.2.11

**Comment by nmoinvaz** [comment]
Does changing mz_strm_zlib.c at line 208 from:

```
while (zlib->zstream.avail_out > 0);
```
To:
```
while ((zlib->zstream.avail_out > 0)  || (flush == Z_FINISH && err == Z_OK));
```

Solve the issue?

**Comment by rddesmond** [comment]
No, but the issue disappears if I comment mz_strm_zlib.c:171 and mz_strm_zlib.c:172, where it doesn't continue to check `inflate` if the parent stream doesn't have any more data.
```
            if (read == 0)
               break;
```

I'm testing to see if that is sufficient and doesn't break anything, though so far it looks like it is working.  Do you think any other decompression libraries need a similar change?  It seems reasonable that because they can decompress unpredictable amounts, they will have to have some internal mechanism to store it when it doesn't fit in the output.

**Comment by nmoinvaz** [comment]
minizip probably uses `inflate` a bit differently than other libraries with the flush parameter  Z_SYNC_FLUSH`. Other libraries might use `Z_NO_FLUSH` followed by `Z_FINISH`.

**Comment by nmoinvaz** [comment]
I have made a similar change to the bzip and lzma streams in case the problem is also there. Thanks reporting and fixing.

**Comment by rddesmond** [comment]
Thank you!

**Comment by nmoinvaz** [comment]
I took another look at this. I'm not so sure ` && (in_bytes > 0 || out_bytes > 0)` is needed. Also I found a bug in the `main.cpp` in the test_assert. It wouldn't return the right error number because `err` would be evaluated twice in a #define.
