### ISSUE TITLE
error C3688: invalid literal suffix 'PRId32'

### ISSUE THREAD

**Issue by Anton-V-K** [nmoinvaz/minizip#416]
It is not possible to compile `minizip\test\test.c` with MS VS 2017 because of numerouse errors of same type:
`error C3688: invalid literal suffix 'PRId32'; literal operator or literal operator template 'operator ""PRId32' not found`

It seems the C++ compiler can't properly handle lines like:
```
        printf("%s encrypted %"PRId32"\n", encrypt_path, written);

```

Adding spaced around `PRId32` and `PRId64` (to separate the tokens) resolves the issue.

It seems the problems is specific to C++ compiler, because similar fragments in other C-files are compiled fine (by C compiler).
The error happens when file is included (in a C++ file) this way:
```
extern "C"
{
#include <minizip/test/test.c>
}
```

**Comment by nmoinvaz** [comment]
`PRId32` is found in inttypes.h. The test.c source file is not intended to be used as an include.

**Comment by nmoinvaz** [comment]
If you want to add spaces around those inttypes.h #defines and submit as a PR.
