### ISSUE TITLE
test_stream_mem() failures

### ISSUE THREAD

**Issue by Anton-V-K** [nmoinvaz/minizip#417]
I'm testing custom build of minizip, and discovered some issues with the tests in `\test\test.c`.

The initial creation of zip in memory stream fails if it is opened in `read-write` mode:
```
    /* Write zip to memory stream */
    mz_stream_mem_create(&write_mem_stream);
    mz_stream_mem_set_grow_size(write_mem_stream, 128 * 1024);
    mz_stream_open(write_mem_stream, NULL, MZ_OPEN_MODE_CREATE);

    mz_zip_create(&zip_handle);
    err = mz_zip_open(zip_handle, write_mem_stream, MZ_OPEN_MODE_READWRITE);
```
The error `-107` (`MZ_EXIST_ERROR`) is returned from `mz_stream_find_reverse` (well, the stream is empty).

Changing `MZ_OPEN_MODE_READWRITE` to `MZ_OPEN_MODE_WRITE` solves the issue.

Is the test supposed to work with `MZ_OPEN_MODE_READWRITE` here?

**Comment by nmoinvaz** [comment]
The open modes on `mz_zip_open` work a bit differently. READ is for reading an existing zip, so it will try to read from the memory stream a zip file. WRITE would do zip creation to memory stream.

**Comment by Anton-V-K** [comment]
Thanks for the reply.
The test stream is created (as new) for writing. So trying to read from it doesn't make much sense. Actually the test fails there in my build.

**Comment by nmoinvaz** [comment]
I have updated the test. Thanks for reporting.
