### ISSUE TITLE
Password protected archive can be opened with WinZip but not 7-Zip

### ISSUE THREAD

**Issue by t0034514** [nmoinvaz/minizip#418]
Created a password protected archive on Win 10 using the 2.8.9 assets minizip-windows.zip
I can extract the archive with WinZip but not 7-zip

The files are added one at a time to the archive using the -a -p -s options.
![error](https://user-images.githubusercontent.com/30174704/64797977-22517180-d57a-11e9-9f47-33f8b33271d4.png)

**Comment by nmoinvaz** [comment]
Can you please let me know what commands you used to create the archive?

**Comment by t0034514** [comment]
Something like:

minizip.exe -a -p zzzzzz -s test.zip document.txt

**Comment by nmoinvaz** [comment]
When I use minizip.exe in minizip-window.zip to zip up the document.txt that you provided that contains "test" - the archive is extractable with 7-Zip 19.02 (alpha). I'm not sure what you are doing to gt it to create the bad archive. I'm using the same arguments you provided.

**Comment by t0034514** [comment]
Try this,
create an archive and use the -o option to ensure it is empty
minizip.exe -o test.zip

then add some a file
minizip.exe -a -p zzzzzz -s test.zip document.txt

I cannot see the added file with 7-zip

**Comment by t0034514** [comment]
Actually the -p -s options are a red herring

minizip.exe -o test.zip
minizip.exe -a test.zip document.txt

is enough to fail.

**Comment by nmoinvaz** [comment]
This is fixed now in the `dev` branch. Thanks for reporting it.
