### ISSUE TITLE
PKWARE ZIP encryption issue

### ISSUE THREAD

**Issue by JoergSchneiderSimon** [nmoinvaz/minizip#42]
When zlib/minizip are built on 64-bit Linux, ZIP archives with password/encryption cannot be unzipped (always getting "invalid password")
The issue does not occur when zlib/minizip is built in 32 bit.

I found the solution to be:

ioapi.h:62
\# ifdef HAS_STDINT_H

which should be

\# ifdef HAVE_STDINT_H

I'm new to GitHub, so pls make the change and commit, as I don't want to "mess up things".

thanks,

Joerg

**Comment by nmoinvaz** [comment]
I have fixed it. Thank you!
