### ISSUE TITLE
Unzip the file and return -105

### ISSUE THREAD

**Issue by binlinrepo** [nmoinvaz/minizip#422]
I create  archive (about 8M) contained a lot of duplicate content with minizip and  Z_DEFLATE mode. But when unzipping the archive, it always failing with error -105.
source file:
`a12345678998765432101000cdsbndjncsjdkakkadlkdkljjdcdmmkkcmdmkscmkkaabbdhsjsjdsjdnsdcnsdcncssldcndks4a12345678998765432101000cdsbndjncsjdkakkadlkdkljjdcdmmkkcmdmkscmkkaabbdhsjsjdsjdnsdcnsdcncssldcndks4a12345678998765432101000cdsbndjncsjdkakkadlkdkljjdcdmmkkcmdmkscmkkaabbdhsjsjdsjdnsdcnsdcncssldcndks... ... ...`

**Comment by nmoinvaz** [comment]
Can you please attach the source file? Thanks.

**Comment by binlinrepo** [comment]
[79e154d2-d3b2-4ad3-98e8-b185949648e6.txt](https://github.com/nmoinvaz/minizip/files/3618804/79e154d2-d3b2-4ad3-98e8-b185949648e6.txt)

**Comment by binlinrepo** [comment]
> Can you please attach the source file? Thanks.

[79e154d2-d3b2-4ad3-98e8-b185949648e6.txt](https://github.com/nmoinvaz/minizip/files/3618806/79e154d2-d3b2-4ad3-98e8-b185949648e6.txt)

**Comment by nmoinvaz** [comment]
I'm not getting an error, here is the commands I used:

```
-o test.zip 79e154d2-d3b2-4ad3-98e8-b185949648e6.txt
-o -x -d xyz test.zip
```

Have you tried the latest `dev` branch?

**Comment by binlinrepo** [comment]
> I'm not getting an error, here is the commands I used for `minizip_cmd`:
> 
> ```
> -o test.zip 79e154d2-d3b2-4ad3-98e8-b185949648e6.txt
> -o -x -d xyz test.zip
> ```
> 
> Have you tried the latest `dev` branch?

No， I tried `master` branch only.
