### ISSUE TITLE
Unzip the file and return -103 （-101）

### ISSUE THREAD

**Issue by VijayMay** [nmoinvaz/minizip#425]
[BaseSynchronousData.zip](https://github.com/nmoinvaz/minizip/files/3661166/BaseSynchronousData.zip)
![231569552830_ pic_hd](https://user-images.githubusercontent.com/8068487/65747285-a6d3f080-e133-11e9-9d01-a0c84967fba0.jpg)

number_entry_cd == 0, zip->number_entry == 4  ,err = MZ_FOEMAT_ERROR

**Comment by nmoinvaz** [comment]
It looks like the central directory on that zip file does not have the correct number of entries value stored in it.
