### ISSUE TITLE
Walkthrough or documentation on how to use minizip

### ISSUE THREAD

**Issue by saj281** [nmoinvaz/minizip#426]
Hi

Is there any sort of documentation available to help me on how to use minizip effectively. I am trying to open a zip file and do the following: 

1. Read and write raw zip entry data.
2. Reading and writing zip archives from memory.

**Comment by Gavin-yb** [comment]
What did you do with it, and why did I use OpenScenGraph my guide to compile the error report missing file.
For example: ioapi. c

**Comment by Gavin-yb** [comment]
What did you do with it, and why did I use OpenScenGraph my guide to compile the error report missing file.
For example: ioapi. c###

**Comment by nmoinvaz** [comment]
I have started adding documentation to the docs folder in the `dev` branch. I plan on doing documentation for mz_zip_rw.h. I don't have any plans to do documentation on mz_compat.h. After that it should be complete.

**Comment by nmoinvaz** [comment]
All the documentation I plan to write is now complete. If anybody has any changes or wants to add more, then I welcome PR. That's it.
