### ISSUE TITLE
Problem at editing created zip files using 7-Zip 

### ISSUE THREAD

**Issue by Iniesta8** [nmoinvaz/minizip#428]
Hi,

I've found out that Zip-Files created by minizip cannot be edited with 7-ZIP. Especially when I try to delete a file from the zip I get an error message like "Not implemented". I don't know if the problem is already known. Maybe I have to set some special attributes or something to enable editing of zip files...?

Thanks in advance.

**Comment by nmoinvaz** [comment]
What commands did you use?

**Comment by Iniesta8** [comment]
I'm using the following functions to add files:

- mz_zip_writer_create()
- mz_zip_writer_set_password()
- mz_zip_writer_set_aes()
- mz_zip_writer_set_compress_method()
- mz_zip_writer_set_compress_level()
- mz_zip_writer_set_entry_cb()
- mz_zip_writer_set_overwrite_cb()
- mz_zip_writer_set_progress_cb()
- mz_zip_writer_set_progress_interval()
- mz_zip_writer_open_file()
- mz_zip_writer_add_file()
- mz_zip_writer_close()
- mz_zip_writer_delete()

I'm calling mz_zip_writer_add_file() in a for loop to add all given files and editing the filename in zip.

Options are: 
- HECZ_COMPRESS_LEVEL_DEFAULT
- HECZ_COMPRESS_METHOD_DEFLATE

Version of 7-ZIP: 19.00
Version of minizip:

**Comment by Iniesta8** [comment]
It seems that the central header is missing in my zip file...

**Comment by Coeur** [comment]
If central header was missing, you wouldn't be able to read it at all, would you?
Please use minizip 2.9.0, follow the exact steps that you've described above and share the resulting zip file (and password) if there is an issue.

**Comment by nmoinvaz** [comment]
You can try to use the recovery method `mz_zip_set_recover` which will scan the whole zip for local file headers and try to recover the zip.
