### ISSUE TITLE
Iconv linking

### ISSUE THREAD

**Issue by BotellaA** [nmoinvaz/minizip#429]
I have an issue while linking (on macOS) my library with `minizip`. Here is the error:
```
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _mz_os_utf8_string_create in libminizip.a(mz_os_posix.c.o)
  "_iconv_close", referenced from:
      _mz_os_utf8_string_create in libminizip.a(mz_os_posix.c.o)
  "_iconv_open", referenced from:
      _mz_os_utf8_string_create in libminizip.a(mz_os_posix.c.o)
ld: symbol(s) not found for architecture x86_64
```

I am not sure to understand why the `Iconv` is optional (according the cmake config https://github.com/nmoinvaz/minizip/blob/master/CMakeLists.txt#L315). If it is really optional, could we have a flag to manually disable it?

cc @benjaminchauvin

**Comment by nmoinvaz** [comment]
https://stackoverflow.com/questions/57734434/libiconv-or-iconv-undefined-symbol-on-mac-osx/57734435

**Comment by BotellaA** [comment]
In this case, I do not understand why Iconv is find in QUIET mode and not REQUIRED.

What is the use of the variable Iconv_IS_BUILT_IN ? https://github.com/nmoinvaz/minizip/blob/master/CMakeLists.txt#L621
Do you provider a way to build it if needed ?

**Comment by nmoinvaz** [comment]
`Iconv_IS_BUILT_IN` is from https://github.com/Kitware/CMake/blob/master/Modules/FindIconv.cmake#L26.

**Comment by BotellaA** [comment]
We did some tests on this `FindIconv.cmake`. It was added to cmake 3.11 (https://cmake.org/cmake/help/v3.11/release/3.11.html#modules). Upgrading our cmake to at lease 3.11 solved this issue.

Should you enfore cmake 3.11? If not how to make sure the code finds Iconv?

**Comment by Coeur** [comment]
I agree that a mention to the minimum required version of CMake should be written on the readme. Feel free to pull request it, @BotellaA.

**Comment by nmoinvaz** [comment]
Windows does not need Iconv so it can probably use a lower CMake version.

**Comment by nmoinvaz** [comment]
On ubuntu with 3.5.1 it compiles fine even though FindIconv.cmake does not exist. That is why the package is QUIET and not REQUIRED. Because it Iconv can be built-in and when that is not case, FindIconv.cmake is not necessary.
