### ISSUE TITLE
macOS and files over 4GB in Finder-created zips

### ISSUE THREAD

**Issue by supersv** [nmoinvaz/minizip#431]
Hey Nathan,

Looking at Issue #5 (https://github.com/nmoinvaz/minizip/issues/5), it seems that the patch didn't make it into the more recent versions (I'm testing with 2.9.0), as the example minizip program is not able to fully extract a zip with large files in it?

The test zip has just 3 files inside -  1-Small, 2-LargeOver4GB, 3-Small - after extracting the second file, it tries to extract the third one, but fails at

    else if ((local) && (magic != MZ_ZIP_MAGIC_LOCALHEADER))
            err = MZ_FORMAT_ERROR;

which is at mz_zip.c:218

Any suggestions on how to make the library accept macOS-originating Zip files?

Thanks,
Vasyl

**Comment by nmoinvaz** [comment]
Do you have an example ZIP file?

**Comment by supersv** [comment]
Sure, here's a zip file with a 5 GB random file (and two small ones) inside, created with Finder:

https://www.dropbox.com/s/lz2t58ai6gaadlt/MacZipDemo-dev-urandom.zip?dl=0

Interestingly enough, if the 5 GB file is all zeroes (and gets compressed nicely, to just 5 MB), the extraction works well; sample file:

https://www.dropbox.com/s/m1sa5avgihm7ssh/MacZipDemo-dev-zero.zip?dl=0

**Comment by nmoinvaz** [comment]
I have made some changes that should fix it. I will attempt to recover the zip entries in a 4gb zip file that contains no zip64 information.

**Comment by supersv** [comment]
Thanks for the patch. I've tried recovering the first sample file linked above, with minizip built from `dev`, but with the same error -103 as the result.

**Comment by nmoinvaz** [comment]
I tested against this [file](https://uce9d58206b68256e605b4113dc2.dl.dropboxusercontent.com/cd/0/get/Aqcbm4ciSUvY5bSgiY4-xdmBzjtzXNAlYY0xKnnWJjxyjvltRacYmwhRS2O_ccnx0ZEoMv3sEGj1X9ZfyEQtIBVgoYI5DylwIC133p6W5J3bQA/file?_download_id=2417371403843647009487183659893191861833529124673258736818204395&_notify_domain=www.dropbox.com&dl=1).

**Comment by nmoinvaz** [comment]
It is working fine for me even with your test file. Not getting -103.

**Comment by supersv** [comment]
Must have been an error on my side - now extraction works on both Mac and Windows. Thanks again.

**Comment by supersv** [comment]
Found another problem. I'm testing on a zip archive with lots of files inside, among them a single large (> 4 GB) file, created with Finder.

Situation:
- commit a44fae3b0cffed80f735e4333e9e38c9e3b305b2 (before the first 431 fix) - extracts up to the big file, then fails (as expected)
- commits be483d8b6ed86ae3b5e5b67ff2ea18c77bc0a4e4, 28d87dd8b8f75c44069d4e524c44c0aced1be844 - fails with -105 on a regular small file (many files before the big file where it failed originally).
- commits 545d729594ce788d3bbe90fa3505228b144e12bd, 75741f4b2cd014a2b368d9103cb9d7347092b29e - fails the same, with -105, but on a different file (so behavior has changed after the second 431 fix).

The failure happens in `mz_zip_entry_read_close()`, on the `zip->entry_crc32 != zip->file_info.crc` check.

I can't share the test zip file in question, but if I manage to create a sample one, I'll post it. This is on a Mac, `cmake -G Xcode .` and using the resulting `minizip -x -d <...> <...zip>`.

**Comment by supersv** [comment]
OK, here's sample zip file - https://www.dropbox.com/s/pjb2v6s4ltblzu3/protobuf.zip?dl=0

Basically a clone of https://github.com/protocolbuffers/protobuf with the 5 GB -dev-urandom.zip file placed inside protobuf/cmake.

Fails at 
`...
Extracting protobuf/benchmarks/util/__init__.py
Error -105 saving entries to disk /.../.../protobuf.zip`

**Comment by Coeur** [comment]
@supersv do you think that you could come up with a fix?

**Comment by supersv** [comment]
@Coeur Let's hear Nathan's verdict first.

**Comment by nmoinvaz** [comment]
macOS archive utility doesn't write zip files that are 4gb properly with ZIP64 extension. This is a long time known mac bug.

**Comment by Coeur** [comment]
@nmoinvaz in that case, I guess I don't need to wait for a fix for that. Do you know how close we are from a minizip 2.9.1 release? I plan to update minizip once you'll be making a release.

**Comment by nmoinvaz** [comment]
I was hoping to get to look at these two issues that are open before I do. Maybe I can get to it by next week. I'm currently working on incorporating code coverage into the build system.

**Comment by nmoinvaz** [comment]
@supersv the zip file is no longer available..

**Comment by supersv** [comment]
@nmoinvaz Try this link: https://www.dropbox.com/sh/me9lzpe1lbnpb8u/AAClsrIrjw4QWJxNf8zx1UsFa?dl=0

**Comment by nmoinvaz** [comment]
I think I have made a change that could possibly fix it so please test. But the problem is that your zip file contains zip files which make it hard to determine where some entries start and end.

**Comment by supersv** [comment]
@nmoinvaz Seems to work like a charm. Congrats!
