### ISSUE TITLE
Memory leak in mz_zip_writer_entry_close detected...

### ISSUE THREAD

**Issue by iecmdev** [nmoinvaz/minizip#435]
Hello!
The function **int32_t mz_zip_writer_entry_close(void *handle)**  contains a memory leak.

During the if statement **"if (writer->sha256 != NULL)"**  the writer's file_extra_stream is allocated but this memory block is never freed.

Best regards,
Sascha

**Comment by nmoinvaz** [comment]
Nice find. Thank you.

**Comment by iecmdev** [comment]
Your fix solves the problem. The memory leak is gone now.
Thank you very much!!!

Best regards,
Sascha
