### ISSUE TITLE
"The same volume can not be used as both source and destination" when extracting the zip file using winzip

### ISSUE THREAD

**Issue by najes** [nmoinvaz/minizip#436]
<p>
The zip file created by minizip 2.9.0 cannot be extracted on the same volume? </br>
I keep getting warning below if i tried to extract zip file using winzip on windows file explorer (it works on 7zip though) : 
</p>

![image](https://user-images.githubusercontent.com/24752804/67933492-7b439a80-fbf8-11e9-8ea0-99385deea2a0.png)

<p>
Did i miss something on the zip options part?
<table>
<tr><td>options.compress_method</td><td>MZ_COMPRESS_METHOD_STORE</td></tr>
<tr><td>options.compress_level</td><td>MZ_COMPRESS_LEVEL_DEFAULT</td></tr>
<tr><td>options.append</td><td>1</td></tr>
<tr><td>options.overwrite</td><td>1</td></tr>
<tr><td>options.follow_links</td><td>0</td></tr>
<tr><td>options.store_links</td><td>0</td></tr>
<tr><td>options.include_path</td><td>0</td></tr>
<tr><td>options.zip_cd</td><td>0</td></tr>
<tr><td>options.aes</td><td>0</td></tr>
<tr><td>options.encoding</td><td>MZ_ENCODING_UTF8</td></tr>
<tr><td>options.disk_size</td><td>512*1024</td></tr>
<tr><td>options.cert_path</td><td>NULL</td></tr>
<tr><td>options.cert_pwd</td><td>NULL</td></tr>
</table>
Thanks!
</p>

**Comment by nmoinvaz** [comment]
Please attach a zip file that reproduces the problem.

**Comment by najes** [comment]
Here is one of the zip file

[test.zip](https://github.com/nmoinvaz/minizip/files/3796474/test.zip)

**Comment by nmoinvaz** [comment]
It looks like you are appending entries to the zip file. Can you please share the command lines that you used to create this archive?

**Comment by najes** [comment]
```
int32_t err = 0;
char* szFile[ ] = { "TEST.EXE", "TEST.INI", .... }
for(int i=0, i<(sizeof(szFile)/sizeof(szFile[0])), i++)
{
  err = (minizip_add(path, password, &options, 1, szFile[i]));
  if(err == !=MZ_OK)
  {
    .....
  }
}
```

**Comment by nmoinvaz** [comment]
The `minizip_add` function is not intended to be used in this manner. You should be using the logic inside `minizip_add` and calling `mz_zip_writer_add_path` for each entry you want to add, otherwise you are opening the zip file over and over to add each file.

**Comment by nmoinvaz** [comment]
It is likely that Windows Explorer does not support split disks. 
https://stackoverflow.com/questions/31286707/the-same-volume-can-not-be-used-as-both-the-source-and-destination
