### ISSUE TITLE
Compilation Question

### ISSUE THREAD

**Issue by taozi-xx** [nmoinvaz/minizip#439]
I tried to compile the source code, but when the compilation completed, the target minizip was not generated.

How to solve this problem?

**Comment by nmoinvaz** [comment]
Can you provide more details?

**Comment by taozi-xx** [comment]
`-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- Using ZLIB https://github.com/madler/zlib master
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1757 (message):
  error: could not find git for clone of zlib
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  CMakeLists.txt:117 (ExternalProject_Add)


-- Configuring incomplete, errors occurred!
`

**Comment by nmoinvaz** [comment]
You have to install git. Please make sure your development environment is setup.
