### ISSUE TITLE
Should zlib update minizip to this fork?

### ISSUE THREAD

**Issue by madler** [nmoinvaz/minizip#441]
The minizip code currently distributed with zlib has not been maintained. What would Nathan think of replacing that with his fork here?

**Comment by nmoinvaz** [comment]
It might be possible to do it; but I would get input from @gvollant first. He might want to continue to have the original minizip as part of zlib. 

My opinion is that I would not have any `contribs` folder in zlib unless you want to be responsible for maintaining or updating those `contribs` on a regular basis. You will continue to end up getting issues related to the contribs as long as they are there. The issue list for zlib is already polluted with a lot of minizip contrib compilation related issues. I think you can save yourself some headache and nuke all of them. There is always the option of including minizip as a git submodule or including it as an ExternalProject in CMake (which will download the minizip repository automatically and compile it). If all else, and you do decide to include this minizip fork source in the zlib source, that's okay. 

P.S. I have an open PR on zlib project if you can take a look at it - looks to be a bug in inflate. https://github.com/madler/zlib/pull/446

**Comment by madler** [comment]
Thanks. I have asked Gilles in another issue. (https://github.com/madler/zlib/issues/463)
