### ISSUE TITLE
Bad zip file check

### ISSUE THREAD

**Issue by willson-chen** [nmoinvaz/minizip#443]
Hi @nmoinvaz,

Could you please help to have a check this zip file [BaseSynchronousData.zip](https://github.com/ZipArchive/ZipArchive/files/3650187/BaseSynchronousData.zip) original from [ZipArchive/Issue #539](https://github.com/ZipArchive/ZipArchive/issues/539).

I use command line tool `7z` and `minizip` to extract files separately. I got a warning while unzipping with 7z

```
WARNINGS:
There are data after the end of archive
```

But no warning with minizip.

So can I tell if there is warning with minizip?

**Comment by nmoinvaz** [comment]
In minizip there is no warning if there is extra data at the end of the zip file.

**Comment by willson-chen** [comment]
@nmoinvaz , Could you kindly help to review the issue from ZipArchive? I found `mz_stream_os_read` only reads 1 bytes so that ZipArchive can not unzip the file.

**Comment by nmoinvaz** [comment]
It looks like PKZIP has cannot open the file or read the fields correctly even after attempting to repair. Some zip files have corrupted central directory. If you set `mz_zip_set_recover(zip_handle, 1)`, then it will attempt to repair the archive by reading all the local file headers. `minizip_cmd` can do this and I attempted it and it extracted ok.
