### ISSUE TITLE
How to zip symlink with APIs in mz_compat?

### ISSUE THREAD

**Issue by willson-chen** [nmoinvaz/minizip#446]
Command line tool `minizip` can store symlink with option `-y`. I anaylized the code of `minizip.c`, and found that it use `mz_zip_writer/reader` APIs and call `mz_zip_writer_set_store_links` to implement the function.

I wonder how to `store symlink` with `mz_compat` APIs, which is used in ZipArchive.

Thanks!

**Comment by nmoinvaz** [comment]
Take a look at this code in `mz_zip_rw.c`. If the item is a symbolic link, it will read the symbolic link using `mz_os_read_symlink`, then it will store the value in `file_info.linkname`. 

https://github.com/nmoinvaz/minizip/blob/370ab036f391a8742e5139a3c9a66e1303145b6e/mz_zip_rw.c#L1711

It is not currently possible to add symbolic link using `zipOpenNewFileInZip5` as you can see here: https://github.com/nmoinvaz/minizip/blob/370ab036f391a8742e5139a3c9a66e1303145b6e/mz_compat.c#L143
