### ISSUE TITLE
Compatibility issues with Zlib filefunc variables

### ISSUE THREAD

**Issue by annewu15** [nmoinvaz/minizip#447]
Hi,
I ran into an issue when trying to move from the original version of Minizip to the newest one. In the original code I reference now deprecated variables like ZLIB_FILEFUNC_MODE_READ, ZLIB_FILEFUNC_MODE_WRITE, ZLIB_FILEFUNC_SEEK_SET, etc. These values used to be defined in ioapi.h which no longer exists. 

Are there variables in the most recent versions of minizip compatible with the ones I mentioned above? 

Thanks.

**Comment by gvollant** [comment]
In an ideal world, we have both source code and binary compatibility between these two versions

**Comment by nmoinvaz** [comment]
How are you using this constant? The newer versions of minizip does not support the old `file_func` interface.

**Comment by nmoinvaz** [comment]
I have noted the incompatibility in the Wiki on this GitHub.

**Comment by ljavorsk** [comment]
@nmoinvaz What wiki? Can you please provide the URL for this exact incompatibility?

It looks like that's an issue for `chromium` project, which requires the ioapi.h header file ([Fedora bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2242271#c2)).

**Comment by nmoinvaz** [comment]
That Wiki for this project was removed some time ago.

I have added a new commit in `develop` which should solve issue for missing `ioapi.h`.
https://github.com/zlib-ng/minizip-ng/commit/e6d334a82b39a318d1b78cd94e21591647766403

**Comment by ngothan** [comment]
the function unzGetCurrentFileZStreamPos64 which is needed to build chromium, is missing. It caused following error in chromium build:

```
tractor.cc -o obj/third_party/tflite_support/tflite_support/metadata_extractor.o  
../../third_party/tflite_support/src/tensorflow_lite_support/metadata/cc/metadata_extractor.cc:107:19: error: use of undeclared identifier 'unzGetCurrentFileZStreamPos64'
  107 |   auto position = unzGetCurrentFileZStreamPos64(zf);
```

Can we have this function back in mz_compat?

Thank!

**Comment by nmoinvaz** [comment]
Sure. I am open to a PR that adds that compatible functionality if anybody wants to add it.

**Comment by ngothan** [comment]
I do not know how many programs are still affected. But for chromium we definitely need it.

Thanks!

**Comment by ljavorsk** [comment]
I think this could also be a big issue when switching from madler/zlib to zlib-ng (minizip will need to transition as well). As MZ_COMPAT flag should ensure it's API/ABI compatible with the old minizip, but right now it's not.

**Comment by berolinux** [comment]
Not sure what exactly that function (which is still used by chromium 133) is supposed to return -- does this look like the correct replacement?

```
uint64_t unzGetCurrentFileZStreamPos64(unzFile file) {
    unz64_file_pos pos;
    unzGetFilePos64(file, &pos);
    return pos.pos_in_zip_directory;
}
```
