### ISSUE TITLE
minizip build failed with zlib-ng-compat

### ISSUE THREAD

**Issue by xuchunmei000** [nmoinvaz/minizip#449]
first i compile zlib-ng with --zlib-compat
then i build minizip with ZLIB_COMPAT=ON
i get this failure:
Scanning dependencies of target minizip
[  2%] Building C object CMakeFiles/minizip.dir/mz_crypt.c.o
/home/minizip/minizip-2.9.1/mz_crypt.c:19:14: fatal error: zlib-ng.h: No such file or directory
 #    include "zlib-ng.h"

/home/minizip/minizip-2.9.1/mz_strm_zlib.c:19:12: fatal error: zlib-ng.h: No such file or directory
 #  include "zlib-ng.h"

i guess include zlib-ng.h should add test for ZLIB_COMPAT, if ZLIB_COMPAT is not set , then include zlib-ng.h？

**Comment by xuchunmei000** [comment]
i create fix in https://github.com/nmoinvaz/minizip/pull/450

**Comment by nmoinvaz** [comment]
Looks good.
