### ISSUE TITLE
minizip installs files named "minizip_cmd" and "minigzip_cmd"

### ISSUE THREAD

**Issue by ryandesign** [nmoinvaz/minizip#451]
At least on macOS 10.13, minizip 2.9.2 installs files named "minizip_cmd" and "minigzip_cmd", instead of "minizip" and "minigzip" as 2.9.1 and earlier did. This is weird. I assume this was caused by 8dae95b53eff474a0959fd2bfe10e86906d33dba.

**Comment by nmoinvaz** [comment]
Yes. I am okay with this change.

**Comment by ryandesign** [comment]
How extremely bizarre.

**Comment by nmoinvaz** [comment]
Do you have a suggestion as to what to do?
