### ISSUE TITLE
Symlink file ziped with minizip_cmd but unziped failed with unzip in Linux

### ISSUE THREAD

**Issue by willson-chen** [nmoinvaz/minizip#455]
It is easy to reproduce. Here is an example.
```
./minizip_cmd -y -b test.zip source.txt link.txt
mv test.zip newDir
cd newDir
unzip test.zip
ls -l
```
And we got the following result:
```
total 0
lrwxrwxrwx 1 myName myGroup 17 Feb 29 21:54 link.txt -> 'ThisIsSourceFile'$'\n'
-rw-rw-rw- 1 myName myGroup  17 Feb 29 21:52 source.txt
-rw-rw-rw- 1 myName myGroup 488 Feb 29 21:53 test.zip
```
`ThisIsSourceFile` is the content of `source.txt`. `link.txt` should be linked to `source.txt`.

**Comment by willson-chen** [comment]
Hi, @nmoinvaz. Did you [reply](https://github.com/ZipArchive/ZipArchive/issues/559#issuecomment-593441776) in the [wrong issue](https://github.com/ZipArchive/ZipArchive/issues/559)? That reply seems match this issue better.

In fact I am developing the zip/unzip symlink feature for `mz_compat`, which port from `mz_zip_reader/writer`. And I found this issue. So I wonder if it will be fixed?

**Comment by nmoinvaz** [comment]
Fixed in `dev`. Thanks for reporting.
