### ISSUE TITLE
Unzipping archives in iOS, created on Windows 10 64 bit

### ISSUE THREAD

**Issue by TobiasWGDE** [nmoinvaz/minizip#46]
I use the zip library 'Zip' from Roy Marmelstein. He has developed that library based on 'minizip'.

Everything works as expected if I create archives with the OS X default compression feature that's integrated in Finder. The archive is getting unzipped successfully by this library.

But as soon as I create an archive on Windows 10 with 7Zip or any other zip program, this archive is recognized as corrupted (bad zip file). If I unzip an archive with Finder, it works. The 'Zip' library throws an exception after calling the function "unzOpenCurrentFile" returned with -103 ('UNZ BADZIPFILE').

I have tried these zip compression algorithms: Deflate, Deflate64, BZip2, LZMA and PPMd.

Is this a known problem, or is a specific compression algorithm necessary?

Thanks in advanced

**Comment by nmoinvaz** [comment]
If you are using a different library, I suggest you contact the author of that library as they may have made changes to minizip that I am not aware of. Thanks!
