### ISSUE TITLE
iconv.h is missing on some android platform

### ISSUE THREAD

**Issue by okhowang** [nmoinvaz/minizip#463]
I want use minizip with Android NDK.
and I found that some ndk version has poor iconv support (only support in 32 bits).

I notice `iconv_*` is only used in `mz_os_utf8_string_create` which is only called by `mz_zip_reader_save_all` with `reader->encoding > 0` and `reader->file_info->flag & MZ_ZIP_FLAG_UTF8`.
it's useless in some situation.

Shall we add a build option to remove iconv dependency for some platform?
or use JNI to call Java API for encoding converting.

**Comment by nmoinvaz** [comment]
We probably need a `HAVE_ICONV` definition added to CMakeLists.txt, then we can check if we have it. If we don't then just put a compiler warning and skip iconv code.

**Comment by nmoinvaz** [comment]
I have made some changes to the `dev` branch. Please try them and let me know how it works for you.

**Comment by okhowang** [comment]
It's OK to me
