### ISSUE TITLE
Files matching -d not found in archive

### ISSUE THREAD

**Issue by DkSuperMan** [nmoinvaz/minizip#464]
I have an error when I use the -d parameter.
Such as: ./minizip_cmd -x XXX.zip -d XXX

**Comment by willson-chen** [comment]
Please specify the error, such as output message or any other related information.

**Comment by DkSuperMan** [comment]
![image](https://user-images.githubusercontent.com/11763987/78871406-3ad72b00-7a7a-11ea-91df-b7279362ab37.png)

**Comment by DkSuperMan** [comment]
> Please specify the error, such as output message or any other related information.

Don't have any error code, just output the error string.

**Comment by nmoinvaz** [comment]
That parameter should come before the name of the zip file.
```
minizip_cmd -x -d /Users/jin/Downloads/ /Users/jin/Downloads/Archive.zip
```
Usage is:
```
Usage: minizip [-x][-d dir|-l|-e][-o][-f][-y][-c cp][-a][-j][-0 to -9][-b|-m][-k 512][-p pwd][-s] file.zip [files]
```
