### ISSUE TITLE
mz_zip_reader_entry_read buffer size

### ISSUE THREAD

**Issue by hsdk123** [nmoinvaz/minizip#465]
Hi, I'm looking at the example here

https://github.com/nmoinvaz/minizip/blob/master/doc/mz_zip_rw.md#mz_zip_reader_entry_read

but it seems there's no way to get the actual size of the entry so that we can preallocate a buffer that's sufficiently large - how do we get the information?

**Comment by nmoinvaz** [comment]
It is not necessary to get the entry size, you can use any buffer length and keep calling `mz_zip_reader_entry_read` until no more data (0 return value). If you want the entry size you can use `mz_zip_reader_entry_get_info`.
