### ISSUE TITLE
zlibstaticd.lib created even if RelWithDebInfo

### ISSUE THREAD

**Issue by hsdk123** [nmoinvaz/minizip#467]
Hi, it seems as if zlibstaticd.lib is created even if RelWithDebInfo - thus creating linking errors, as what's being attempted to link is zlibstatic.lib. 

Setup)
no previous zlib installation, using the default cmakelists which seems to fetch from the repo. 
I'm also fetching minizip by FetchContent_Declare.

**Comment by nmoinvaz** [comment]
I have changed CMakeLists.txt to use FetchContent. See #469

**Comment by nmoinvaz** [comment]
I am having difficulty getting FetchContent to work with madler/zlib CMakeLists.txt. Error about cmake install export..

**Comment by nmoinvaz** [comment]
I think I got it now. Solution is kind of weird adding zlib to install targets.
