### ISSUE TITLE
zlibwapi!zError

### ISSUE THREAD

**Issue by kouzhudong** [nmoinvaz/minizip#468]
0:011> .ecxr
rax=0000000000000000 rbx=0000000000000000 rcx=00000000090268e0
rdx=ffffffffffffffe8 rsi=00000000090e1003 rdi=00000000090e1004
rip=000007feef881c26 rsp=000000000b52e038 rbp=0000000000008000
 r8=000000000000fef9  r9=00000000090e0efa r10=00000000090d1000
r11=0000000000000002 r12=0000000000000000 r13=0000000000000002
r14=000007feef8e2f00 r15=0000000000000000
iopl=0         nv up ei pl zr na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246
zlibwapi!zError+0x1d6:
000007fe`ef881c26 488b441610      mov     rax,qword ptr [rsi+rdx+10h] ds:00000000`090e0ffb=????????????????
0:011> k
  *** Stack trace for last set context - .thread/.cxr resets it
 # Child-SP          RetAddr           Call Site
00 00000000`0b52e038 000007fe`ef8741f0 zlibwapi!zError+0x1d6
01 00000000`0b52e040 000007fe`ef873078 zlibwapi!deflateCopy+0xf00
02 00000000`0b52e090 000007fe`ef880fd7 zlibwapi!deflate+0x778
03 00000000`0b52e0d0 00000001`3f5afe94 zlibwapi!zipWriteInFileInZip+0xb7
...

0:011> db 090e0ff0
00000000`090e0ff0  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  ................
00000000`090e1000  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
00000000`090e1010  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
00000000`090e1020  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
00000000`090e1030  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
00000000`090e1040  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
00000000`090e1050  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????
00000000`090e1060  ?? ?? ?? ?? ?? ?? ?? ??-?? ?? ?? ?? ?? ?? ?? ??  ????????????????

**Comment by nmoinvaz** [comment]
Please provide repo steps.
