### ISSUE TITLE
Problem with finding the the central dir position

### ISSUE THREAD

**Issue by reyhan-sadak** [nmoinvaz/minizip#471]
The issue occurs with the file in the link:
https://drive.mobisystems.com/sharelink/714xQfiNQl3XH9nsYc5iWL2CU0oVTqBmEsnf4ez8fpth
I call unzOpen2_64() and in unzOpenInternal() unz64local_SearchCentralDir64() returns 0.
I tried to debug it and it seems that the reason is that the central dir position is not found:
if (uPosFound == 0)
return 0;

**Comment by nmoinvaz** [comment]
You can use the new minizip2 api to open the zip with recover mode and it will rebuild the central directory when it doesn't exist.
