### ISSUE TITLE
Local file header for stored files have 0 size values

### ISSUE THREAD

**Issue by jimpark** [nmoinvaz/minizip#474]
The local file header for a file using compression method MZ_COMPRESS_METHOD_STORE has 0 values for compressed size and uncompressed size. The central directory has correct values. It would be nice to get the file sizes in the local file header. The biggest problem this solves is with ZipInputStream on Android (https://stackoverflow.com/questions/47208272/android-zipinputstream-only-deflated-entries-can-have-ext-descriptor/54236244#54236244).

**Comment by nmoinvaz** [comment]
I use data descriptor for local file header, so it sets those to 0 and then writes the values at the end of the file marked by a header. This is so I don't have to seek backwarcds.

There is a function called `mz_zip_set_data_descriptor`. I think it is not documented, but it will seek backwards and write those values.

**Comment by jimpark** [comment]
Does the user of the lib call `mz_zip_set_data_descriptor` or is this something that should be done by the library? It seems strange that only STORE compression method does not do this.

**Comment by jimpark** [comment]
Also, the function `mz_zip_set_data_descriptor` doesn't seem to do what you described.
```
int32_t mz_zip_set_data_descriptor(void *handle, uint8_t data_descriptor)
{
    mz_zip *zip = (mz_zip *)handle;
    if (zip == NULL)
        return MZ_PARAM_ERROR;
    zip->data_descriptor = data_descriptor;
    return MZ_OK;
}
```

**Comment by nmoinvaz** [comment]
It sets the flag for it to do it.

**Comment by jimpark** [comment]
In the local file header, the data descriptor is currently set to 0x8. The other fields are all set. Just the CRC-32, compressed size, and uncompressed sizes are set to 0. But fields like last modified date and time are set. So should I call `mz_zip_set_data_descriptor(handle, 0)` ? And where should I do that? Should that be in the calling code?

**Comment by nmoinvaz** [comment]
It should be `mz_zip_set_data_descriptor(handle, 1)` and called prior to writing files to the mz_zip object.

**Comment by jimpark** [comment]
I tried setting this on the zip object right after I open it before I write any files to it and I still get CRC-32: 0, compressed size: 0, uncompressed size: 0.

**Comment by nmoinvaz** [comment]
Can you attach example code? Thanks.

**Comment by jimpark** [comment]
Here's the C++ wrapper I am using with the implementation of the constructor and the add_stream function pasted.
```
class zip_file_impl {
public:
  zip_file_impl(const fs::path &zipFile, bool overWrite);

  ~zip_file_impl();

  void add_file(int compressionLevel, const fs::path &basePath,
                const fs::path &relativePath, const char *password = nullptr);

  void add_file_with_rename(int compressionLevel, const fs::path &srcPath,
                            const fs::path &zipPath,
                            const char *password = nullptr);

  void add_directory(int compressionLevel, const fs::path &basePath,
                     const fs::path &relativePath,
                     const char *password = nullptr);

  void add_stream(int compressionLevel, istream &stream,
                  const fs::path &fileNameInZip,
                  const char *password = nullptr);

  bool is_open() const { return is_open_; }

  fs::path get_path() const {
    if (is_open()) {
      return path_;
    } else {
      return fs::path();
    }
  }

  void close() {
    if (is_open()) {
      zipClose(zf_, nullptr);
      is_open_ = false;
    }
  }

protected:
  static uint32_t compute_crc(const fs::path &filePath);
  static uint32_t compute_crc(istream &stream);
  static int is_large_file(const fs::path &filePath);
  static int is_large_file(istream &stream);

private:
  mutex m_;
  zipFile zf_;
  fs::path path_;
  bool is_open_;
};

//----------------------------------------------------------------------------
// is_large_file
//----------------------------------------------------------------------------

int zip_file_impl::is_large_file(istream &stream) {
  auto pos = stream.tellg();
  stream.seekg(0, stream.end);
  auto len = stream.tellg() - pos;
  stream.seekg(pos);
  return (len >= numeric_limits<uint32_t>::max()) ? 1 : 0;
}

//----------------------------------------------------------------------------
// zip_file_impl
//----------------------------------------------------------------------------

zip_file_impl::zip_file_impl(const fs::path &zipFile, bool overWrite)
    : path_(zipFile), is_open_(false) {
  int opt_overwrite = APPEND_STATUS_CREATE;

  if (!overWrite) {
    opt_overwrite = APPEND_STATUS_ADDINZIP;
  } else {
    // Erase the file since zipOpen2_64 seems to have a problem if the
    // file exists even if APPEND_STATUS_CREATE is used.
    if (exists(zipFile)) {
      remove(zipFile);
    }
  }

#ifdef USEWIN32IOAPI
  zlib_filefunc64_def ffunc;
  fill_win32_filefunc64W(&ffunc);

  zf_ = zipOpen2_64(zipFile.u8string().c_str(), opt_overwrite, nullptr, &ffunc);
#else
  zf_ = zipOpen64(zipFile.u8string().c_str(), opt_overwrite);
#endif

  if (zf_ == nullptr) {
    throw fs::filesystem_error(MF_ERR("Could not create Zip file."), zipFile,
                               error_code(errno, system_category()));
  }

  mz_zip_set_data_descriptor(zf_, 1);
  is_open_ = true;
}

//----------------------------------------------------------------------------
// add_stream
//----------------------------------------------------------------------------

void zip_file_impl::add_stream(int compressionLevel, istream &stream,
                               const fs::path &fileNameInZip,
                               const char *password) {
  if (!is_open()) {
    throw runtime_error(MF_ERR("Cannot add to a closed Zip file."));
  }

  // Acknowledgments: The following is based on "minizip.c" contribution
  // in zlib.

  int opt_compress_level = compressionLevel;
  // int opt_exclude_path_ = 0;
  vector<char> buf(WRITEBUFFERSIZE);

  streamsize size_read;
  zip_fileinfo zi;
  uint32_t crcFile = 0;
  int zip64 = 0;

  zi.tmz_date.tm_sec = zi.tmz_date.tm_min = zi.tmz_date.tm_hour =
      zi.tmz_date.tm_mday = zi.tmz_date.tm_mon = zi.tmz_date.tm_year = 0;
  zi.dosDate = 0;
  zi.internal_fa = 0;
  zi.external_fa = 0;

  utils::current_local_time(zi.tmz_date);

  if (password != nullptr) {
    crcFile = compute_crc(stream); // Restores stream position.
  }

  zip64 = is_large_file(stream);

  // Note: Must use generic_u8string() because forward slashes are required by
  // Zip spec.
  auto utf8RelPath = fileNameInZip.generic_u8string();

  {
    lock_guard<mutex> lock(m_);

    auto err = zipOpenNewFileInZip5(
        zf_, utf8RelPath.c_str(), &zi, nullptr, 0, nullptr, 0,
        nullptr /* comment*/, (opt_compress_level != 0) ? Z_DEFLATED : 0,
        opt_compress_level, 0,
        /* -MAX_WBITS, DEF_MEM_LEVEL, Z_DEFAULT_STRATEGY, */
        -MAX_WBITS, DEF_MEM_LEVEL, Z_DEFAULT_STRATEGY, password, crcFile, 36,
        1 << 11, zip64); // Unicode enabled

    if (err != ZIP_OK) {
      throw fs::filesystem_error(
          MF_ERR("Error in opening new file in Zip file."), fileNameInZip,
          path_, error_code(err, zip_error_category()));
    }

    {
      scope_guard zipGuard([=]() { zipCloseFileInZip(zf_); });

      while (stream) {
        stream.read(&buf[0], buf.size());
        size_read = stream.gcount();

        if (size_read > 0) {
          err = zipWriteInFileInZip(zf_, &buf[0],
                                    static_cast<unsigned int>(size_read));

          if (err < 0) {
            throw fs::filesystem_error(
                MF_ERR("Error writing to Zip file."), // $NON-NLS-1$
                path_, error_code(err, zip_error_category()));
          }
        }
      }
    }
  }
}
```

**Comment by jimpark** [comment]
Regardless of whether I call `mz_zip_set_data_descriptor(handle, 1)` or not, in `mz_zip_entry_write_close` line 2328, the test `((zip->file_info.flag & MZ_ZIP_FLAG_DATA_DESCRIPTOR) == 0)` is `false`.

**Comment by nmoinvaz** [comment]
`zipOpen64` does not return a `mz_zip` object. It returns `mz_compat` object. So you have to add a helper fucntion to extract it.

**Comment by nmoinvaz** [comment]
Maybe something like this:
```
void *unzGetHandle_MZ(unzFile file)
{
    mz_compat *compat = (mz_compat *)file;
    if (compat == NULL)
        return UNZ_PARAMERROR;
    return compat->handle;
}
```

**Comment by jimpark** [comment]
In mz_zip_entry_write_open(), there's this line of code:
```
        if (zip->data_descriptor)
            zip->file_info.flag |= MZ_ZIP_FLAG_DATA_DESCRIPTOR;
```
So if I set zip->data_descriptor to 1, then the flag MZ_ZIP_FLAG_DATA_DESCRIPTOR is set. And the test in line 2328,
```
    /* Update local header with crc32 and sizes */
    if ((err == MZ_OK) && ((zip->file_info.flag & MZ_ZIP_FLAG_DATA_DESCRIPTOR) == 0) &&
        ((zip->file_info.flag & MZ_ZIP_FLAG_MASK_LOCAL_INFO) == 0))
```
would always return false and so the local header file is never set with sizes. So either the logic above is reversed somewhere or I should be doing `mz_zip_set_data_descriptor(handle, 0)`.

**Comment by nmoinvaz** [comment]
I have updated the dev branch and so you can use `mz_zip_set_data_descriptor(zipGetHandle_MZ(zf_), 1);`.

**Comment by nmoinvaz** [comment]
Yes, I think it should be: ~((zip->file_info.flag & MZ_ZIP_FLAG_DATA_DESCRIPTOR) != 0)`

**Comment by jimpark** [comment]
Thanks, but like I said, it was already set to 1 when I debugged it. Please look at the post above. So either it should be set to 0, or the if check with the comment "Update local header with crc32 and sizes" is wrong.

**Comment by nmoinvaz** [comment]
Wait no, sorry you are right, it should be:
```
mz_zip_set_data_descriptor(zipGetHandle_MZ(zf_), 0);
```
You don't want to use the data descriptor, instead u want it to update the local header with crc32 and sizes.

**Comment by jimpark** [comment]
Thanks. Just curious though, is there anything wrong with having **both** the data descriptor and the file sizes and crc32 in the ZIP local file header?

**Comment by jimpark** [comment]
Nevermind. I think that's just not per spec. And also, you lose out on the optimization of having the data descriptor.

**Comment by nmoinvaz** [comment]
I have documented it here: https://github.com/nmoinvaz/minizip/commit/2a2e90870cf71535fde7a388f175aa1c1c09257b. The benefit of doing data descriptors is so that you don't have to seek backwards in the stream.

**Comment by jimpark** [comment]
On Windows, the API `mz_zip_set_data_descriptor` is not DLL exported. Could we make an API like `void zipSetDataDescriptor_MZ(unzFile file, uint8_t data_descriptor)`?

**Comment by nmoinvaz** [comment]
I think you will have to statically link the library. I don't want to keep extending this compatibility layer.
