### ISSUE TITLE
Make [mz_zip.c] more modular

### ISSUE THREAD

**Issue by karimhm** [nmoinvaz/minizip#478]
In `mz_zip.c` the library check for both, `HAVE_ZLIB` and `HAVE_LIBCOMP` flags and then uses the Zlib interface even though on Apple platforms it might use the Libcomp interface that is "Catfishing" Zlib.

https://github.com/nmoinvaz/minizip/blob/b39f7a0e896615833a5af9dc7134563917a3a227/mz_zip.c#L1885-L1888

Wouldn't something like be better?
```C
#if defined(HAVE_ZLIB)
    else if (zip->file_info.compression_method == MZ_COMPRESS_METHOD_DEFLATE)
        mz_stream_zlib_create(&zip->compress_stream);
#endif
#if defined(HAVE_LIBCOMP)
    else if (zip->file_info.compression_method == MZ_COMPRESS_METHOD_DEFLATE)
        mz_stream_libcomp_create(&zip->compress_stream);
#endif
```

**Comment by karimhm** [comment]
When trying to compile the library on Apple platform `mz_strm_zlib.[h/c]` and `mz_strm_libcomp.[h/c]` cannot coexist due to duplicated symbols issue.

**Comment by nmoinvaz** [comment]
Are you using CMake to generate xcode project? It should prevent this type of scenario.

**Comment by karimhm** [comment]
No I'm using [Swift Package Manager](https://swift.org/package-manager). I manually copied source files.

**Comment by SilenceWater** [comment]
Making the project private with CocoapoDS won't unzip
