### ISSUE TITLE
Way to disable 'Warning: Limited encoding support'?

### ISSUE THREAD

**Issue by vszakats** [nmoinvaz/minizip#481]
This warning is now peramanently shown when building without `iconv`. While understanding the drawbacks, I'd argue that there may be cases/platforms where building against `iconv` isn't practical or isn't necessary. E.g. on Windows, building `iconv` is a challenge and even when done, it's a large dependency that needs to be shipped around. In cases where minizip2 is used in a controlled environment with known, or pure-ASCII filenames, it can work well without codepage conversion.

It'd be nice to have a way to avoid this warning and silently fall back to the transparent `strncpy()` method.

**Comment by nmoinvaz** [comment]
Do you have any suggestions? Maybe we should only mention this in CMake?

**Comment by vszakats** [comment]
Moving that (a.) to CMake would be nice, or, (b.) implement a `#define` specifically to enable the non-iconv branch (e.g. `MZ_ENCODING_TRANSPARENT`), or (c.) a `HAVE_NO_ICONV` `#define` which would have the same effect as no `HAVE_ICONV`, but would suppress the warning.

[ My preference is (a.), (c.), (b.) ]

**Comment by nmoinvaz** [comment]
I think we should do CMake. Do you want to do a PR?

**Comment by vszakats** [comment]
I'm not a "CMake-person", so I'd trust yours much better for this solution.

**Comment by jjYBdx4IL** [comment]
btw. there seems to be a rather simple solution on Windows:

https://github.com/brofield/simpleini/blob/f7862c3dd7ad35becc2741f268e3402e89a37666/SimpleIni.h#L3450
