### ISSUE TITLE
Windows DLL created by MinGW-w64 has a duplicate prefix "lib"

### ISSUE THREAD

**Issue by zedxxx** [nmoinvaz/minizip#483]
Now I got a dll named as `liblibminizip.dll`

It happened after [this](https://github.com/nmoinvaz/minizip/commit/b671db3f583363300b182ad8af1acf231089e763#diff-af3b638bc2a3e6c650974192a53c7291R654) change.

**Comment by nmoinvaz** [comment]
I think I need to add `AND NOT MINGW`.

**Comment by zedxxx** [comment]
Output is proper for MS VisualStudio compiler only, not for all compilers for Windows. I think that you should detect only this compiler when adding  an extra "lib" prefix.

I haven't tested it on compilers other than mingw, but there's a big chance that output will be the same.
