### ISSUE TITLE
Undocumented command line options

### ISSUE THREAD

**Issue by bug22** [nmoinvaz/minizip#495]
The minizip command shows:

> `Usage: minizip [-x][-d dir|-l|-e][-o][-f][-y][-c cp][-a][-j][-0 to -9][-b|-m][-k 512][-p pwd][-s] file.zip [files]`

along with explanations of the command line options.

However, the options `-e` and `-j` are not explained.

From the source code it could be seen that `-e` is meant to erase files. But what does `-j` do, is it used at all?

**Comment by nmoinvaz** [comment]
`-j` doesn't appear to be used so I removed it and documented `-e`.
