### ISSUE TITLE
TOC links don't work in API docs

### ISSUE THREAD

**Issue by bug22** [nmoinvaz/minizip#496]
It's inconvenient to navigate through the API functions documentation because clicking on the table of contents links does not work due to missing underscores in the names of the corresponding destination anchors.

For example, https://github.com/nmoinvaz/minizip/blob/master/doc/mz_zip_rw.md#mz_zip_reader_open should be reachable through its TOC entry for `mz_zip_reader_open`, but it isn't, because the anchor name is spelled as `#mzzipreaderopen` (without underscores) in the TOC.

**Comment by joycepg** [comment]
i'm happy to send a pr for this, if is it just editing the .md files manually? or did you use a tool to generate the .md?

**Comment by nmoinvaz** [comment]
I will accept a PR. I used a tool. Some plugin for VSCode.
