### ISSUE TITLE
Add zstd algorithm support in zip.

### ISSUE THREAD

**Issue by fcharlie** [nmoinvaz/minizip#498]
zstd is a very good compression algorithm. In recent years, it has been used by more and more open source projects. Recently, the zstd compression algorithm has been added to the [zip compression specification](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT). The magic number is 20. Now, I suggest that minizip start to add support for zstd .

I use minizip as the implementation of baulk's zip decompression function, and currently implements a zstd support that has not been sufficiently tested for reference:

https://github.com/baulk/baulk/blob/master/lib/archive/minizip/mz_strm_zstd.c

Follow-up of other compression software: 
https://github.com/mcmilk/7-Zip-zstd/issues/132
https://github.com/szcnick/p7zip/issues/25
https://github.com/mholt/archiver/pull/223

Thanks.

**Comment by gvollant** [comment]
see https://github.com/curl/curl/pull/5453 : I approve it

**Comment by nmoinvaz** [comment]
@fcharlie do you want to make a PR also put a comment at the top for credit?

**Comment by fcharlie** [comment]
@nmoinvaz Thank you for your approval, but I have been a little busy lately. When I am free, I will go and see how to better support zstd in minizip.

**Comment by nmoinvaz** [comment]
Ok, if you don't have time I can incorporate it for you. In the comment in the file do you want me to credit you as "Force Charlie"?

**Comment by fcharlie** [comment]
@nmoinvaz You can call me "Force Charlie". Thank you

**Comment by fcharlie** [comment]
@nmoinvaz 

The [zip specification](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) has been updated and the magic number 20 has been deprecated

```
        0 - The file is stored (no compression)
        1 - The file is Shrunk
        2 - The file is Reduced with compression factor 1
        3 - The file is Reduced with compression factor 2
        4 - The file is Reduced with compression factor 3
        5 - The file is Reduced with compression factor 4
        6 - The file is Imploded
        7 - Reserved for Tokenizing compression algorithm
        8 - The file is Deflated
        9 - Enhanced Deflating using Deflate64(tm)
       10 - PKWARE Data Compression Library Imploding (old IBM TERSE)
       11 - Reserved by PKWARE
       12 - File is compressed using BZIP2 algorithm
       13 - Reserved by PKWARE
       14 - LZMA
       15 - Reserved by PKWARE
       16 - IBM z/OS CMPSC Compression
       17 - Reserved by PKWARE
       18 - File is compressed using IBM TERSE (new)
       19 - IBM LZ77 z Architecture 
       20 - deprecated (use method 93 for zstd)
       93 - Zstandard (zstd) Compression 
       94 - MP3 Compression 
       95 - XZ Compression 
       96 - JPEG variant
       97 - WavPack compressed data
       98 - PPMd version I, Rev 1
       99 - AE-x encryption marker (see APPENDIX E)
```

**Comment by gvollant** [comment]
see https://github.com/nmoinvaz/minizip/issues/500 about zstd
