### ISSUE TITLE
The zip(LZMA) archive created by 7z cannot be decompressed.

### ISSUE THREAD

**Issue by fcharlie** [nmoinvaz/minizip#501]
minizip: dev branch.
7z: 20.00 alpha (x64 2020-02-06)
lzma: https://tukaani.org/xz/ 5.2.5
`mz_zip_reader_save_all return -3`

The zip(bzip2) created by 7z can be decompressed correctly.

I doubt it is the problem of decompress loop. If I have time after get off work tomorrow, I will go to see why this problem occurs.

**Comment by fcharlie** [comment]
libzip has disabled magic number 14, which may be related to 7z special implementation.

**Comment by jloqfjgk** [comment]
Using LZMA (Method ID 14) in ZIP probably needs some "magic". For details, please refer to my comment in nih-at/libzip#198.

**Comment by nmoinvaz** [comment]
I had to make modifications to LZMA library.

**Comment by nmoinvaz** [comment]
https://sourceforge.net/p/lzmautils/discussion/708858/thread/84c5dbb9/?limit=25#b563

**Comment by nmoinvaz** [comment]
It might be possible to read and write the custom header needed for ZIP without modifications. I haven't looked at it in some time.
