### ISSUE TITLE
Support for cmake iOS system

### ISSUE THREAD

**Issue by okhowang** [nmoinvaz/minizip#503]
cmake support generate iOS project from 3.14.
but there is some [limits](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#switching-between-device-and-simulator)
> Use explicit -l linker flag, e.g. target_link_libraries(foo PUBLIC "-lz")
> Use explicit -framework linker flag, e.g. target_link_libraries(foo PUBLIC "-framework CoreFoundation")
> Use find_package() only for libraries installed with CMAKE_IOS_INSTALL_COMBINED feature

currently `zlib` `bz2` `iconv` is iOS's system libraries
may be we shouldn't use find_package to find them on build with iOS?

**Comment by nmoinvaz** [comment]
I do use find_package..

**Comment by okhowang** [comment]
I build a dynamic library which depends on minizip on iOS.
I use minizip as sub_directory currently.
because minizip depends on iconv which find by `find_package`
```cmake
if(Iconv_FOUND AND NOT Iconv_IS_BUILT_IN)
    target_link_libraries(${PROJECT_NAME} ${Iconv_LIBRARIES})
endif()
```
I couldn's build it with xcode for iphone simulator.

why we couldn't be compatible with ios?

**Comment by nmoinvaz** [comment]
It uses find_package for iconv elsewhere. Minizip doesn’t require iconv as far as I can remember.

**Comment by okhowang** [comment]
> It uses find_package for iconv elsewhere. Minizip doesn’t require iconv as far as I can remember.

Yes, iconv is not required for minizip now.

there are two `platform` for iOS: iphoneos and iphonesimulator.
for ios system library, there are also two version.
for example libz has
+ /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk/usr/lib/libz.tbd
+ /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk/usr/lib/libz.tbd

when use find_package zlib_libraries will be exactly an absolute path /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk/usr/lib/libz.tbd
which could be used when build for iphonesimulator

this is why cmake has [limits](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#switching-between-device-and-simulator) for ios building.

it's not a problem of iconv, it's a problem for find_package and ios

**Comment by nmoinvaz** [comment]
If I allow setting ZLIB_LIBRARIES and ZLIB_INCLUDE_DIRS manually via cmake, then will that solve the problem?

**Comment by okhowang** [comment]
does cmake will be like below ?
```cmake
if(ZLIB_LIBRARIES)
   target_link_libraries(minizip ${ZLIB_LIBRARIES})
   include_directories(${ZLIB_INCLUDE_DIRS})
else()
  find_package(zlib) # and so on
endif()
```
then I can set ZLIB_LIBRARIES=-lz for iOS.

but this shouldn't be apply to zlib onlt, but also apply to all libraries find by `find_package`

**Comment by nmoinvaz** [comment]
Ok that will work. I think the check should go further up. 
```
    if(NOT ZLIB_FORCE_FETCH AND NOT ZLIB_LIBRARIES)
        find_package(ZLIB QUIET)
    endif()
    if(ZLIB_LIBRARIES AND ZLIB_INCLUDE_DIRS)
        set(ZLIB_FOUND TRUE)
    endif()
    if(ZLIB_FOUND AND NOT ZLIB_FORCE_FETCH)
```

 Do you want to make a PR?

**Comment by nmoinvaz** [comment]
You could just do `-DZLIB_FORCE_FETCH=OFF -DZLIB_FOUND=TRUE -DZLIB_LIBRARIES=z -DZLIB_INCLUDE_DIRS=..` and it would work right, without any changes?

**Comment by nmoinvaz** [comment]
Actually I just remember I documented this in the Wiki (but it got removed some how).. Anyways I reverted it and the documentation is back in the wiki for customizing ZLIB.
https://github.com/nmoinvaz/minizip/wiki

**Comment by okhowang** [comment]
finally, I use `-DZLIB_LIBRARY=-lz -DIconv_LIBRARIES=-liconv -DBZIP2_LIBRARIES=-lbz2 -DIconv_LIBRARY:STRING=-liconv -DZLIB_INCLUDE_DIR=. -DBZIP2_INCLUDE_DIR=. -DIconv_INCLUDE_DIR=.` to override absolute path find by `find_package`.
It's OK for me currently.
