### ISSUE TITLE
Don't link security library when crypto feature is disabled on Apple

### ISSUE THREAD

**Issue by okhowang** [nmoinvaz/minizip#504]
if `MZ_PKCRYPT` and `MZ_WZAES` is OFF.
it's no need to link `CoreFoundation` and `Security` for Apple
there is condition of `(MZ_PKCRYPT OR MZ_WZAES)` for [WIN32](https://github.com/nmoinvaz/minizip/blob/master/CMakeLists.txt#L697) but no condition for Apple

**Comment by nmoinvaz** [comment]
Ok can u submit a PR?

**Comment by okhowang** [comment]
Yes, I will do it later
