### ISSUE TITLE
Compilation Problem

### ISSUE THREAD

**Issue by taozi-xx** [nmoinvaz/minizip#510]
An error occurred  When I tried to run cmake in the minizip directory.
/minizip-master/mz.h:162:44: error: missing binary operator before token "("
    (defined(__has_include) && __has_include(<stdint.h>))
                                            ^
/minizip-master/mz_crypt.c:109:51: error: unknown type name ‘uint8_t’
     int32_t salt_length, int32_t iteration_count, uint8_t *key, int32_t key_length) {
                                                   ^
make[2]: *** [CMakeFiles/minizip.dir/mz_crypt.c.o] Error 1
make[1]: *** [CMakeFiles/minizip.dir/all] Error 2
make: *** [all] Error 2

Any idea on how to resolve this problem?

**Comment by nmoinvaz** [comment]
What is your CMake configure output?

**Comment by taozi-xx** [comment]
-- Using CMake version 3.11.4
-- The C compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Using ZLIB 1.2.11
-- Fetching ZSTD https://github.com/facebook/zstd
-- The CXX compiler identification is GNU 4.8.4
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ZSTD VERSION: 1.4.5
-- Setting build type to 'Release' as none was specified.
-- Performing Test CXX_FLAG_STD_CPLUSPLUS11
-- Performing Test CXX_FLAG_STD_CPLUSPLUS11 - Success
-- Performing Test C_FLAG_STD_C99
-- Performing Test C_FLAG_STD_C99 - Success
-- Performing Test C_FLAG_WALL
-- Performing Test C_FLAG_WALL - Success
-- Performing Test CXX_FLAG_WALL
-- Performing Test CXX_FLAG_WALL - Success
-- Performing Test C_FLAG_WEXTRA
-- Performing Test C_FLAG_WEXTRA - Success
-- Performing Test CXX_FLAG_WEXTRA
-- Performing Test CXX_FLAG_WEXTRA - Success
-- Performing Test C_FLAG_WUNDEF
-- Performing Test C_FLAG_WUNDEF - Success
-- Performing Test CXX_FLAG_WUNDEF
-- Performing Test CXX_FLAG_WUNDEF - Success
-- Performing Test C_FLAG_WSHADOW
-- Performing Test C_FLAG_WSHADOW - Success
-- Performing Test CXX_FLAG_WSHADOW
-- Performing Test CXX_FLAG_WSHADOW - Success
-- Performing Test C_FLAG_WCAST_ALIGN
-- Performing Test C_FLAG_WCAST_ALIGN - Success
-- Performing Test CXX_FLAG_WCAST_ALIGN
-- Performing Test CXX_FLAG_WCAST_ALIGN - Success
-- Performing Test C_FLAG_WCAST_QUAL
-- Performing Test C_FLAG_WCAST_QUAL - Success
-- Performing Test CXX_FLAG_WCAST_QUAL
-- Performing Test CXX_FLAG_WCAST_QUAL - Success
-- Performing Test C_FLAG_WSTRICT_PROTOTYPES
-- Performing Test C_FLAG_WSTRICT_PROTOTYPES - Success
-- CMAKE_INSTALL_PREFIX: /usr/local
-- CMAKE_INSTALL_LIBDIR: lib
-- ZSTD_LEGACY_SUPPORT not defined!
-- ZSTD_MULTITHREAD_SUPPORT is enabled
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for getrandom
-- Looking for getrandom - not found
-- Looking for arc4random_buf
-- Looking for arc4random_buf - not found
-- Looking for arc4random
-- Looking for arc4random - not found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Checking for module 'libbsd'
--   Found libbsd, version 0.6.0
-- Looking for arc4random_buf in bsd
-- Looking for arc4random_buf in bsd - found
-- Performing Test Iconv_IS_BUILT_IN
-- Performing Test Iconv_IS_BUILT_IN - Success
-- Using Iconv
-- Signing not supported with current configuration
-- Looking for limits.h
-- Looking for limits.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Looking for immintrin.h
-- Looking for immintrin.h - found
-- The following features have been enabled:

 * MZ_COMPAT, Enables compatibility layer
 * MZ_ZLIB, Enables ZLIB compression
 * MZ_BZIP2, Enables BZIP2 compression
 * MZ_LZMA, Enables LZMA compression
 * MZ_ZSTD, Enables ZSTD compression
 * MZ_PKCRYPT, Enables PKWARE traditional encryption
 * MZ_WZAES, Enables WinZIP AES encryption
 * MZ_LIBBSD, Build with libbsd for crypto random
 * MZ_BRG, Enables Brian Gladman's encryption library
 * MZ_BUILD_TEST, Builds minizip test executable

-- The following features have been disabled:

 * MZ_LIBCOMP, Enables Apple compression
 * MZ_OPENSSL, Enables OpenSSL for encryption
 * MZ_SIGNING, Enables zip signing support
 * MZ_COMPRESS_ONLY, Only support compression
 * MZ_DECOMPRESS_ONLY, Only support decompression
 * MZ_BUILD_UNIT_TEST, Builds minizip unit test project
 * MZ_BUILD_FUZZ_TEST, Builds minizip fuzzer executables
 * MZ_CODE_COVERAGE, Builds with code coverage flags

-- Configuring done
-- Generating done

**Comment by nmoinvaz** [comment]
Do you have a fix for this?

**Comment by Andrey-N** [comment]
Same here.
__has_include require Visual Studio 2017 version 15.3 and later. In my case i try to build on VS 2015
