### ISSUE TITLE
Broken examples

### ISSUE THREAD

**Issue by Yogurt4** [nmoinvaz/minizip#511]
Hi,

Please fix the examples on the Wiki page. For example, mz_zip_open has three parameters now. Additionally, some mz_zip_close/mz_zip_delete calls may also be missing.

**Comment by nmoinvaz** [comment]
If you have the fixes, I can update them.

**Comment by nmoinvaz** [comment]
I have updated the parameters and added delete calls, but other than that it is meant to be pseudo code not full fledged examples.
