### ISSUE TITLE
add seek support for uncompressed file(MZ_COMPRESS_METHOD_STORE) 

### ISSUE THREAD

**Issue by glanium** [nmoinvaz/minizip#514]
I need to random-access uncompressed file(MZ_COMPRESS_METHOD_STORE).

libzip has this functionality.
https://libzip.org/documentation/zip_fseek.html

**Comment by nmoinvaz** [comment]
Open the zip in raw mode and it will give you access to raw zip data for each entry.

**Comment by glanium** [comment]
After I open zip in raw mode,
How can I seek??
I don't find any API availbale to seek like https://libzip.org/documentation/zip_fseek.html

`        mz_zip_file* file;
        mz_zip_entry_get_info(handle, &file);
        if (file->compression_method == MZ_COMPRESS_METHOD_STORE)
        {
            mz_zip_entry_read_open(handle, 1, nullptr); // raw mode
            // how to seek??

        }`

**Comment by nmoinvaz** [comment]
Take a look at unzSeek64 it does similar to what you want.

**Comment by glanium** [comment]
you mean use minizip 1.2 instead of 2.10??

**Comment by nmoinvaz** [comment]
No take a look at that function in minizip 2 in mz_compat.c and use the same code it uses.

**Comment by glanium** [comment]
oops
I found it.

thx a lot.
