### ISSUE TITLE
Password-protected archives can't be extracted

### ISSUE THREAD

**Issue by Grivus** [nmoinvaz/minizip#523]
Hi!
Currently, I'm unable to create a password-protected archive that could be extracted by 7-Zip or WinZip.
I've tried many times using code (master branch), but now I've tried the commandline test utility from repo, and it seems there is also same problem.
The problem could be reproduced easily:
`minizip -p 1 test.zip 1.txt`
Adding or removing -s option does not affect the extraction problem so I guess there is something bad in both aes and pkw encryptions.
Does anybody know anything about this issue and how to fix it?

**Comment by nmoinvaz** [comment]
This appears to be a problem on Windows only with passwords that are 1 character in length.

**Comment by nmoinvaz** [comment]
I have reported it to Visual Studio Feedback: https://developercommunity.visualstudio.com/content/problem/1215483/cryptimportkey-fails-to-import-plaintext-key-with.html
