### ISSUE TITLE
Not able to build using only Makefile on ubuntu 18.04 intel 64 bit.

### ISSUE THREAD

**Issue by debendrat** [nmoinvaz/minizip#526]
I don't want to use cmake for minizip. Any guidelines to build minizip using only make utility.
I tried to analyze the the Makefiles generated by cmake but could not decode the process. Is there a simple Makefile for my specific platform ubuntu 18.04 intel 64 bit.

**Comment by debendrat** [comment]
How do I build it offline. Build process is always fetching zstd from other git repository.
Thanks
Debendra

**Comment by nmoinvaz** [comment]
cmake. -DMZ_ZSTD=OFF
