### ISSUE TITLE
Cannot call unzGetCurrentFileInfo without pfile_info parameter

### ISSUE THREAD

**Issue by NikoDelarich** [nmoinvaz/minizip#535]
Hi,

I just upgraded minizip from 1.0 (bundled with zlib) to the 2.10.3 release and stumbled upon an issue:
In older minizip versions it was possible to call unzGetCurrentFileInfo with e.g. only the filename & filename_size parameter set.
In the current version the unz_file_info parameter must always be specified - even if just the filename/extrafield/comment is required.

This caused my code to break in a few places - It would be nice if the new version of minizip could be a drop-in replacement for the old version (with MZ_COMPAT set, of course).

BR,
Niko

**Comment by nmoinvaz** [comment]
If you create a PR I can merge it.
