### ISSUE TITLE
make builds a duplicate libzstd.a?

### ISSUE THREAD

**Issue by carlocab** [nmoinvaz/minizip#538]
I recently tried to bump Homebrew's version of minizip here: https://github.com/Homebrew/homebrew-core/pull/66598

CI came back to me with an error complaining about a `lib/libzstd.a` in the install prefix, which duplicates the one that comes with `zstd`.

Is that on purpose? Is the `libzstd.a` built from your tarball different from the one that comes from zstd?

**Comment by carlocab** [comment]
Answered here: https://github.com/Homebrew/homebrew-core/pull/66598

The issue was that cmake couldn't find the pre-provided zstd, so tried to build one itself.

Thanks @nmoinvaz for the quick response.

**Comment by nmoinvaz** [comment]
Thanks for using minizip!
