### ISSUE TITLE
not compiling with AES on windows

### ISSUE THREAD

**Issue by TermeHansen** [nmoinvaz/minizip#64]
in CMakeLists:

```
set_target_properties(aes minizip
   PROPERTIES
   COMPILE_DEFINITIONS "O -DHAVE_AES")

```
does not work on windows with Visual Studio 2015. Changed to

`add_definitions(-DHAVE_AES)`
and it compiles fine.

Also added 
`add_definitions(-D_CRT_SECURE_NO_DEPRECATE)`
 to 
`if(WIN32)`

**Comment by nmoinvaz** [comment]
Can you do a pull request? Thanks!
