### ISSUE TITLE
How to use minizip to compress a directory?

### ISSUE THREAD

**Issue by dafanshu520** [nmoinvaz/minizip#66]
For example, I want to compress my test directory, which own test2 subdirectory and a.txt file, test2 own b.txt and c.txt, just as followings picture:
![image](https://cloud.githubusercontent.com/assets/5927766/17841794/043ad1f0-684f-11e6-8d45-7932c34ae827.png)

I found all of file in test diretory, there are /test/a.txt and /test/test2/b.txt and /test/test2/c.txt, and compress them one by one in test.zip file. But when I decompress the test.zip file, the test2 subdirectory is disappear,just as followings picture:
![image](https://cloud.githubusercontent.com/assets/5927766/17841796/0e773f0a-684f-11e6-8481-dbc65f0a8f9f.png)

Where can I use the wrong? I used the code which as example in minizip,c:
                            ...
                            ...
 err = zipOpenNewFileInZip3(zf,filenameinzip,&zi,
                                 NULL,0,NULL,0,NULL /\* comment_/,
                                 (opt_compress_level != 0) ? Z_DEFLATED : 0,
                                 opt_compress_level,0,
                                 /_ -MAX_WBITS, DEF_MEM_LEVEL, Z_DEFAULT_STRATEGY, */
                                 -MAX_WBITS, DEF_MEM_LEVEL, Z_DEFAULT_STRATEGY,
                                 password,crcFile);

```
            if (err != ZIP_OK)
                printf("error in opening %s in zipfile\n",filenameinzip);
            else
            {
                fin = fopen(filenameinzip,"rb");
                if (fin==NULL)
                {
                    err=ZIP_ERRNO;
                    printf("error in opening %s for reading\n",filenameinzip);
                }
            }

            if (err == ZIP_OK)
                do
                {
                    err = ZIP_OK;
                    size_read = (int)fread(buf,1,size_buf,fin);
                    if (size_read < size_buf)
                        if (feof(fin)==0)
                    {
                        printf("error in reading %s\n",filenameinzip);
                        err = ZIP_ERRNO;
                    }

                    if (size_read>0)
                    {
                        err = zipWriteInFileInZip (zf,buf,size_read);
                        if (err<0)
                        {
                            printf("error in writing %s in the zipfile\n",
                                             filenameinzip);
                        }

                    }
                } while ((err == ZIP_OK) && (size_read>0));
              ....
              .....
```

I called the function three time to compress /test/a.txt , /test/test2/b.txt and /test/test2/c.txt, which pass to the parameter 'filenameinzip',it can work, but the subdirectory test2 is diappear.Please help me!!Thanks!

**Comment by nmoinvaz** [comment]
I don't see anywhere, where you are calling zipCloseFileInZip after each file.

**Comment by dafanshu520** [comment]
I called zipCloseFileInZip after each while((err == ZIP_OK) & ((size_read>0))),in the pirtrue 
![image](https://cloud.githubusercontent.com/assets/5927766/18080672/0fcfb7da-6ec9-11e6-8d2b-ba43bfd1efe1.png)

**Comment by dafanshu520** [comment]
Is it a good way to compress a directory by compressing them one by one ? Is there a way to compress directory directly ?

**Comment by nmoinvaz** [comment]
There is no way to compress it directly. Have you taken a look at the minizip.c example? Do you have a  complete code sample you could attach that can reproduce this issue?

**Comment by dafanshu520** [comment]
I build and run it in linux

**Comment by Jesonchang12** [comment]
You should not delete the slashs in your savefilenameinzip variable to keep your directory instruction.

**Comment by dafanshu520** [comment]
Do you mean I should note the code?
![image](https://cloud.githubusercontent.com/assets/5927766/18502040/33657c10-7a87-11e6-9f4e-296a12e1a297.png)

**Comment by Jesonchang12** [comment]
yes. I'm not very sure, but you can try it.

**Comment by dafanshu520** [comment]
It did not work.

**Comment by nmoinvaz** [comment]
opt_exclude_path might be cutting of the rest of the directory path. I recommend changing your code and pass path also into minizip:
```
listFilesInDirDeep(path, srcfiles);
minizip(ZIP_OVERWRITE, ZIP_STOREONLY, ZIP_EXCLUDE_WITHOUTPATH, zipfile, path, srcfiles);
...
int minizip(ZIP_HANDLE_TYPE type, ZIP_HANDLE_LEVEL level, ZIP_HANDLE_MODE mode, const string & destzipFile, const string &path, const vector < string > vecSrcFile)
```
Savefilenameinzip should actually be initially set to this:
```
savefilenameinzip = curFile.substr(0, path.length()).c_str();
```
And make sure you don't have opt_exclude_path set.
