### ISSUE TITLE
64bit clean

### ISSUE THREAD

**Issue by dbquarrel** [nmoinvaz/minizip#67]
As a suggestion, the code is mixing 64 and 32 bit types in a lot of places, most notably with the CRC calculations which bounce between 32 bit unsigned ints and 64 bit unsigned longs. It's not clear what the intention is then, and you can't cast between these types (uLong and unsigned int) without losing precision. Compiling this for iOS yields a metric ton of assignment errors as 64 bit variables keep getting assigned to 32 bit variables and losing precision. 99% of the time this is going to be OK, but when dealing with encryption and CRC for someone not familiar with the code it's dicey and it's bad practice anyway. 

Typical example is here: pos is set up as an unsigned long, 64 bits and then the result is assigned back into a struct which is only holding 32 bits. With some inspection it looks like this can be fixed just by changing the longs to unsigned ints. But this is just one case of many.

static void encr_data(unsigned char data[], unsigned long d_len, fcrypt_ctx cx[1])
{   unsigned long i = 0, pos = cx->encr_pos;

```
while(i < d_len)
{
    if(pos == AES_BLOCK_SIZE)
    {   unsigned int j = 0;
        /* increment encryption nonce   */
        while(j < 8 && !++cx->nonce[j])
            ++j;
        /* encrypt the nonce to form next xor buffer    */
        aes_encrypt(cx->nonce, cx->encr_bfr, cx->encr_ctx);
        pos = 0;
    }

    data[i++] ^= cx->encr_bfr[pos++];
}

cx->encr_pos = pos;
```

}

This kind of code then needs to have its types modified to be explicit and no assumptions made that long and int are assignable synonyms (they are not). Where width is a necessary part of the calculation I'd suggest using int32_t, uint32_t, int64_t, uint64_t, etc. CRC calculations are one area where bit with should be explicit and you definitely can't accumulate in one type then assign back and forth to a smaller type and expect your results to be consistent.

**Comment by nmoinvaz** [comment]
Yes I have known about this for some time. I think there is a great mismash of different types because the library was edited by so many different people for some time. I do not have the time at the moment to make the necessary changes but I will accept any pull requests.

**Comment by nmoinvaz** [comment]
I have started this work in the dev branch.
