### ISSUE TITLE
Passing incompatible pointer types

### ISSUE THREAD

**Issue by MacGritsch** [nmoinvaz/minizip#71]
There are some warning regarding passing incompatible pointer types:

> unzip.c:898:79: Incompatible pointer types passing 'uLong *' (aka 'unsigned long *') to parameter of type 'int *'
> unzip.c:902:79: Incompatible pointer types passing 'uLong *' (aka 'unsigned long *') to parameter of type 'int *'
> unzip.c:907:79: Incompatible pointer types passing 'uLong *' (aka 'unsigned long *') to parameter of type 'int *'
> unzip.c:1269:72: Passing 'const char *' to parameter of type 'const unsigned char *' converts between pointers to integer types with different sign

**Comment by nmoinvaz** [comment]
This should be fixed now in the dev branch.
