### ISSUE TITLE
Implicit conversion loses precision

### ISSUE THREAD

**Issue by MacGritsch** [nmoinvaz/minizip#72]
There are some warnings regarding implicit conversions:

> aes/fileenc.c:70:20: Implicit conversion loses integer precision: 'unsigned long' to 'unsigned int'
> aes/entropy.c:45:16: Implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int'
> unzip.c:1269:51: Implicit conversion loses integer precision: 'uLong' (aka 'unsigned long') to 'int'
> unzip.c:1269:82: Implicit conversion loses integer precision: 'unsigned long' to 'unsigned int'
> unzip.c:1408:71: Implicit conversion loses integer precision: 'uLong' (aka 'unsigned long') to 'unsigned int'

**Comment by nmoinvaz** [comment]
This should be fixed now in the dev branch.
