### ISSUE TITLE
Unzip with UNZ_BADZIPFILE error (compression_method = 99)

### ISSUE THREAD

**Issue by dttrinh** [nmoinvaz/minizip#74]
Hi, I received a zip file and don't know exactly which OS, as well as which tool or compression method it's zipped by. I've used your lib with latest version to unzip it but it throw UNZ_BADZIPFILE error with the compression_method = 99. (I've debugged and realized that other zip file's compression_method is 8 or something not 99)
(I'm really sorry that I can't upload that file due to its privacy)

![compressionmethoderror](https://cloud.githubusercontent.com/assets/10161363/19337857/bcfb6a1a-9153-11e6-8e7b-9d6b5e775880.png)

The above code snippet is from _unz64local_CheckCurrentFileCoherencyHeader_ method (_unzip.c_ file).
Thank you very much!

**Comment by MacGritsch** [comment]
99 means that it is encrypted. you have to enable encryption support and provide the password.

**Comment by dttrinh** [comment]
Sorry but how to enable encryption support in the code? Can you show me more detail about this?

**Comment by MacGritsch** [comment]
how about reading "readme" file?

> Requires #define HAVE_AES

**Comment by dttrinh** [comment]
Ah, sorry for my careless, I've put `#define HAVE_AES` into `unzip.c` and it's work like a charm!
Thank you so much!
