### ISSUE TITLE
EXC_BAD_ACCESS (code = 1) error when Unzip password protected file with AES method

### ISSUE THREAD

**Issue by dttrinh** [nmoinvaz/minizip#75]
Hi, I have password protected file with AES method created using this library on iOS, then I unzip it also using this library but sometime the error occurred in the method `encr_data` of `fileenc.h` file, and sometime it's extracted successfully. (Ratio is about 2 failed / 10 unzip times)
I think this problem is about memory issue, but I can't find out the reason.

![excbadaccess](https://cloud.githubusercontent.com/assets/10161363/19379186/c42b2356-922b-11e6-9d8e-03e9f4e4455d.png)

Here is the password protected file: https://dl.dropboxusercontent.com/u/38691130/han_kaku123-1.zip, (pass: 123)

Thank you so much!

**Comment by MacGritsch** [comment]
maybe you are providing smaller buffer as specified (we can not see that in your code snippet above).

enable memory-debugging and you should see more info.

**Comment by dttrinh** [comment]
Did you mean this buffer? These code are from my swift file calling `unzip.c`'s `unzReadCurrentFile` method. I have set to 8192 or 16384 but it's not solve the problem.
```
let bufferSize: UInt32 = 4096
var buffer = Array<CUnsignedChar>(repeating: 0, count: Int(bufferSize))
...
let readBytes = unzReadCurrentFile(zip, &buffer, bufferSize)
```

**Comment by MacGritsch** [comment]
Still not enough code.
Create a c++ test project for OS X (not iOS), add the test-zipfile and add it here - then I can test it.

**Comment by dttrinh** [comment]
Thank you for your reply!
I've just created C++ test project for OS X and added the test zipfile.
But I don't know how to call unzip method from unzip.c with C++, sorry for my bad.
If you have time, please take a look at this.
Thank you very much!
https://dl.dropboxusercontent.com/u/38691130/KZipTestProject.zip
(Zip file password: 123)

**Comment by MacGritsch** [comment]
Take miniunz.c and modify the main() method so that it does not require paramters.
directly define your sourcepath, destination and password there.

**Comment by dttrinh** [comment]
I've found the reason why! It's occurred when I try to unzip it with password NULL (for the first time to check it's password protected or not)
I've tested it in C++ project and run many times, sometime the error occurred at the 10th run, sometime at the 2nd run.
Please take a look at my C++ test project:
https://dl.dropboxusercontent.com/u/38691130/KZipTestProject.zip

**Comment by MacGritsch** [comment]
changed password to "123" and executed the executable about 20 times without problems.

**Comment by dttrinh** [comment]
Yes, it's run normally if we set password wrong or true.
But in my application work flow, I'll try to unzip the file with password NULL in the first time.
If byte have read = 0, I'll show the input password dialog for the user.
Can we determine whether the file is password protected or not without try to unzip it with password Null?
The below check password protected file method seem to be useless with AES:
```
func isFilePasswordProtectedAtPath(_ path: String) -> Bool {
        // Begin opening
        let zip = unzOpen64(path)
        if (zip == nil) {
            return false
        }
        
        var ret: Int32 = unzGoToFirstFile(zip)
        if (ret == UNZ_OK) {
            repeat {
                ret = unzOpenCurrentFile(zip);
                if(ret != UNZ_OK ) {
                    return false
                }
                var fileInfo = unz_file_info64()
                ret = unzGetCurrentFileInfo64(zip, &fileInfo, nil, 0, nil, 0, nil, 0);
                if (ret != UNZ_OK) {
                    return false
                } else if((fileInfo.flag & 1) == 1) {
                    return true
                }
                
                unzCloseCurrentFile(zip);
                ret = unzGoToNextFile(zip);
            } while(ret == UNZ_OK && UNZ_OK != UNZ_END_OF_LIST_OF_FILE )
        }
        return false
    }
```

**Comment by MacGritsch** [comment]
Ah, now I get you: it fails when the file is aes-encrypted but you are passing NULL as password.

I think you can add something like this

```
#ifdef HAVE_AES
  if (!password && (int)s->cur_file_info.compression_method == AES_METHOD)
    return UNZ_DEFINE_YOUR_OWN_MISSING_PASSWORD_ERROR;
#endif
```

after

```
if (unz64local_CheckCurrentFileCoherencyHeader(s, &iSizeVar, &offset_local_extrafield, &size_local_extrafield) != UNZ_OK)
        return UNZ_BADZIPFILE;
```

**Comment by dttrinh** [comment]
Ya! Based on your code, I've solved the problem.
Really thank you so much! 😃
