### ISSUE TITLE
Releases and copyright macros

### ISSUE THREAD

**Issue by ferreiradaselva** [nmoinvaz/minizip#77]
I couldn't find any macro in the source that could provide version check and a copyright notice.

``` C
#define MINIZIP_VERSION_MAJOR "1"
#define MINIZIP_VERSION_MINOR "2"
#define MINIZIP_VERSION_PATCH "3"
#define MINIZIP_RELEASE "Minizip " MINIZIP_VERSION_MAJOR "." MINIZIP_VERSION_MINOR "." MINIZIP_VERSION_PATCH

#define MINIZIP_COPYRIGHT MINIZIP_RELEASE "  Copyright (C) 2005-2016 Nathan Moinvaziri"
```

Something like that would be nice :) I want to give credit to minizip in one of my projects. I don't know if I got the date right (and the versioning system).

Also, currently, I'm not sure if the version in the [website](http://www.winimage.com/zLibDll/minizip.html) is the current version. Using the GitHub tab for releases or using tags would make easier to locate stable releases.

**Comment by Coeur** [comment]
In case you are using an Xcode project, you can integrate minizip using CocoaPods, and doing so, the [.podspec](https://github.com/nmoinvaz/minizip/blob/master/Minizip.podspec) is configured to credit the authors.

**Comment by nmoinvaz** [comment]
I have added the tag 1.1 for the current version which is also stable.

**Comment by nmoinvaz** [comment]
The version on the website is an older version. 1.2.3 is the version of zLib. But Minzip has a different versioning scheme. The website contains version 1.01e of Minizip which is inside the contribs/minizip folder in the zlib zips hosted there.
