### ISSUE TITLE
libcompression support 

### ISSUE THREAD

**Issue by catlan** [nmoinvaz/minizip#79]
Apple added in iOS 9 and macOS 10.11 libcompression which optimizes speed and energy efficiency for Apple hardware. They mention 1.57x improvement in zlib decode:

![712_low_energy_high_performance_compression_and_accelerate](https://cloud.githubusercontent.com/assets/45803/20121191/655c1288-a610-11e6-8c25-3bf2f58379b0.png)

More details can be found WWDC 2015 - Session 712 [Low Energy, High Performance: Compression and Accelerate
](https://developer.apple.com/videos/play/wwdc2015/712)

**Comment by nmoinvaz** [comment]
These changes have been incorporated.
