### ISSUE TITLE
Provide do_list and do_extract_* as separate library functions

### ISSUE THREAD

**Issue by ooxi** [nmoinvaz/minizip#82]
Would you consider providing `do_list` and `do_extract_*` as separate library functions? I currently patch minizip just to get these functions without a name conflict with `main` from `miniunz.c`.

If such a patch would be accepted I would be happy to provide one.

**Comment by nmoinvaz** [comment]
I'm not sure I understand. How do you usually patch it? Are you saying you already have functioned named do_list and do_extract_* in your project?

**Comment by ooxi** [comment]
No I do not have `do_list` in my project but `main`. I want to access `do_list` from [miniunz.c](https://github.com/nmoinvaz/minizip/blob/master/miniunz.c#L85) but that file also includes a [`main`](https://github.com/nmoinvaz/minizip/blob/master/miniunz.c#L340) function which results in a name clash with my `main` function :(

**Comment by nmoinvaz** [comment]
I have implemented what you have asked for. The function names now begin with miniunz_*. All you have to do is #define MINISHARED and it will not include main().
