### ISSUE TITLE
unzseek64() compression_method vs. compression level

### ISSUE THREAD

**Issue by roussec** [nmoinvaz/minizip#92]
I am not sure how unzseek() is supposed to work. Line 1897 contains the following code:

`if (pfile_in_zip_read_info->compression_method != 0) return UNZ_ERRNO;`

compression_method is always Z_DEFLATED (8) - althoug it seems it is sometimes used as compression level in the code? I think the idea was to check if compression level was 0 but I am not sure if this info is avaiable. How is this supposed to work?

**Comment by MacGritsch** [comment]
isnt it also used to store if encryption is enabled? (I dont have the code at the moment, and dont have the time to check)

**Comment by roussec** [comment]
Yes  if encryption is enabled it also contains this flag (AES_METHOD), Z_BZIP2ED is also possible. But it is usually not the compression level which I think the above code needs to check instead of the method.

**Comment by nmoinvaz** [comment]
The unzip.h has comment that says it allows seeking in _uncompressed_ data. That is, if the compression method is no compression.
