### ISSUE TITLE
Support Darwin for the latest aes

### ISSUE THREAD

**Issue by Coeur** [nmoinvaz/minizip#93]
[This commit updating aes](https://github.com/nmoinvaz/minizip/commit/d9a932437c0da42ea58675385de4acae22e7ebc1) has broken compatibility with Darwin (iOS/macOS):
* it will `define INTEL_AES_POSSIBLE` on iOS, which is suspicious to me
* aes_ni.h is missing
* [fopen64 is missing](https://stackoverflow.com/questions/4003479/how-to-enable-large-file-support-under-darwin)

**Comment by Coeur** [comment]
I've made an attempt at fixing it with https://github.com/nmoinvaz/minizip/pull/94

**Comment by nmoinvaz** [comment]
I have committed the missing files. Can you tell me if it works when INTEL_AES_POSSIBLE is defined?

**Comment by Coeur** [comment]
when defined, it causes https://github.com/nmoinvaz/minizip/blob/master/aes/aesopt.h#L191 to define USE_INTEL_AES_IF_PRESENT, which causes `include "aes_ni.h"` which doesn't exist, so doesn't compile.

**Comment by Coeur** [comment]
From https://github.com/nmoinvaz/minizip/blob/master/aes/aes_ni.c#L97 and onward I get:

> '__builtin_ia32_aeskeygenassist128' needs target feature aes

**Comment by nmoinvaz** [comment]
It may be best to just not define INTEL_AES_POSSIBLE on Apple devices has you mentioned.

**Comment by Coeur** [comment]
or there is a compilation flag needed. I've never used aes before.
