### ISSUE TITLE
Add xcode project

### ISSUE THREAD

**Issue by nmoinvaz** [nmoinvaz/minizip#96]
This issue is for adding an xcode project to the source code for people on Apple devices.

**Comment by Coeur** [comment]
Oh, I have one on the "Example" branch on my fork. I'll pull request it later.

**Comment by nmoinvaz** [comment]
I am thinking of having three separate projects. One for a minizip.lib, one for miniunz.exe, and one for minizip.exe. And doing the same for xcode.

**Comment by Coeur** [comment]
OK. You can assign the Xcode versions to me. What would be the folder name to put it? *darwin*, *xcode*, *apple*?

**Comment by MacGritsch** [comment]
You can have 3 targets in one Xcode project.

Does it make sense to place the source files in 3 corresponding folders?

**Comment by nmoinvaz** [comment]
I would recommend a folder called xcode.

**Comment by nmoinvaz** [comment]
Thank you!
