### ISSUE TITLE
Add support for zip streaming

### ISSUE THREAD

**Issue by thtrummer** [nmoinvaz/minizip#98]
As far as I can tell there is no support for compression streaming (i.e. using the library without ftell) because after a file is compressed it will fseek back to write the original size, compressed size and CRC32 for the last added file. However, it is supported by the zip standard to write this three values after the last file for especially this purpose.

I would also be willing to supply a pull request with an implementation if someone can propose the necessary change to the interface.

**Comment by nmoinvaz** [comment]
This is a good idea. Let me research it.

**Comment by nmoinvaz** [comment]
I have implemented a change that should remove that seek backwards. Please take a look at it.

**Comment by thtrummer** [comment]
Seems fine. Though I'm not sure if this will break compatibility with older versions of minizip when it's used as default?

**Comment by nmoinvaz** [comment]
The library uses the central directory when unzipping so it should be fine.
